// src/attribution.js — Orphan re-attribution: which combo gets credit when a position record was lost.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { createPublicClient, http } from 'viem';
import { base } from 'viem/chains';
import { DUMP_GRID, POOL_DEPLOY_BLOCK, STATEVIEW, STATEVIEW_ABI, VALUE_GRID } from './config.js';
import { raceTimeout } from './kv.js';
import { poolId } from './market.js';
import { BASELINE_UNATTRIBUTED_KEY, blankQTable, comboKey, snapCd, snapDump, snapMargin, snapSize, snapValue } from './qtable.js';
// ------------------------------------------------------------------ orphan re-attribution ---
// (2026-10-08): orphan positions close with comboKey 'orphan_0_0_0'. The raw orphan key
// must NEVER enter the Q-table — parseCombo yields NaN on it and the bandit could
// then select it (bandit poisoning; the recordClose orphan guard stays). Instead,
// reconstruct the closest HONEST attribution: the onchain market REGIME at the
// wallet's own buy block plus the wallet's seeded params (persistent per-wallet
// thresholds). Real signal (onchain + seeded), not the poisoned orphan key.
// EVERY approximation is documented inline. ANY transport failure -> baseline.
// This function NEVER throws.
async function reconstructBuyCombo(env, publicClient, position, seed, log) {
  // Approximation 0: the wallet's own buy block is unknown in current position
  // records (executeBuy never wrote origBuyBlock — as of 2026-10-08 no record has
  // it). Without a buy block we cannot place the trade in time -> baseline.
  // (review) executeBuy writes `buyBlock`; this used to read only `origBuyBlock`.
  if (position.origBuyBlock == null && typeof position.buyBlock === 'number') position.origBuyBlock = position.buyBlock;
  if (!position.origBuyBlock || typeof position.origBuyBlock !== 'number') {
    log(`reconstructBuyCombo: no origBuyBlock on position — crediting ${BASELINE_UNATTRIBUTED_KEY}`);
    return BASELINE_UNATTRIBUTED_KEY;
  }
  const buyBlock = position.origBuyBlock;
  // Approximation 1: historical price windows as proxies for the LIVE signals:
  //   buyBlock-60   (~2min, Base = 2s blocks) ~ the two-tick drop that fired the buy;
  //   buyBlock-1800 (~1h)                     ~ the 1h-high reference for dip-%;
  //   buyBlock-43200(~24h)                    ~ the 24h-low reference.
  // Approximation 2: dPct is measured from the 1h-AGO PRICE, not the 1h HIGH — the
  // bot buys dips, so price-at-buy vs the hour-ago price is only a proxy for
  // "dip from 1h high" when the high was recent. Documented, not hidden.
  // Approximation 3: windows that predate the pool (buys within ~24h of deploy)
  // clamp to POOL_DEPLOY_BLOCK. A clamped window that still reads zero (slot not
  // yet initialized) is marked UNAVAILABLE and its proxy degrades honestly:
  //   pBuy  (the trade's own block) is REQUIRED — without it, baseline.
  //   p2min unavailable -> dropPct2 = 0 (logged, no fabricated dip).
  //   p1h   unavailable -> dPct falls back to the longest available window
  //          (p2min when present, else 0). The reference is LABELED in the log.
  const blocks = [buyBlock, buyBlock - 60, buyBlock - 1800, buyBlock - 43200]
    .map((b) => Math.max(b, POOL_DEPLOY_BLOCK));
  const pid = poolId();
  const readSlot0At = async (client) => {
    const out = [];
    for (const b of blocks) {
      // Single attempt per block, 15s timeout each. ANY failure -> throw (caller falls back).
      const [sqrtPriceX96] = await raceTimeout(
        client.readContract({
          address: STATEVIEW, abi: STATEVIEW_ABI, functionName: 'getSlot0',
          args: [pid], blockNumber: BigInt(Math.max(b, 0)),
        }), 15000, 'slot0 archive read timeout (15s)');
      out.push(BigInt(sqrtPriceX96) * BigInt(sqrtPriceX96));
    }
    return out;
  };
  // Archive-capable endpoint fallback (2026-10-08): the tick's publicClient is the
  // race winner — publicnode gates archive calls behind a token (2026-10-08 probe:
  // -32602 "Archive requests require a personal token"), drpc and mainnet.base.org
  // serve them. Try the known-good archive hosts FIRST (saves the ~20s token-error
  // round-trip when publicnode won the race), tick client last.
  // Bounded: 3 clients x 4 reads x 15s max. ANY total failure -> baseline.
  // Note: this runs inside the wallet's 45s processing window — 15s/read keeps the
  // common path (~10s/read on drpc) inside it; on timeout the wallet race may
  // abandon this promise but the orphaned continuation still completes the write.
  const mkClient = (url) => {
    try {
      return createPublicClient({ chain: base, transport: http(url, { timeout: 15000 }) });
    } catch { return null; }
  };
  const clients = [
    mkClient('https://base.drpc.org'),
    mkClient('https://mainnet.base.org'),
    publicClient,
  ].filter(Boolean);
  let sqs = null;
  let lastErr = null;
  for (const client of clients) {
    try {
      sqs = await readSlot0At(client);
      break;
    } catch (e) { lastErr = e; }
  }
  if (!sqs) {
    log(`reconstructBuyCombo: archive reads failed on all endpoints (${String((lastErr && lastErr.message) || lastErr).slice(0, 80)}) — crediting ${BASELINE_UNATTRIBUTED_KEY}`);
    return BASELINE_UNATTRIBUTED_KEY;
  }
  // Price proxies: price = (sqrtPriceX96 / 2^96)^2. Ratios only — the 2^192 cancels.
  // The 24h window is advisory only (aboveLowPct is logged, never bucketed): a
  // buy less than 24h after pool deploy reads p24h = 0 (pool didn't exist) — that
  // must not force baseline. The same clamp/degrade logic applies to p2min/p1h:
  // only the trade's own block (pBuy) is required.
  const priceAt = (sq) => Number(sq) / Number(2n ** 192n);
  const [pBuy, p2min, p1h, p24h] = sqs.map(priceAt);
  const winNote = [];
  if (!pBuy || !Number.isFinite(pBuy)) {
    log(`reconstructBuyCombo: no price at buy block ${buyBlock} — crediting ${BASELINE_UNATTRIBUTED_KEY}`);
    return BASELINE_UNATTRIBUTED_KEY;
  }
  const has2min = p2min > 0 && Number.isFinite(p2min);
  const has1h = p1h > 0 && Number.isFinite(p1h);
  if (!has2min) winNote.push('2min window unavailable (pool too young) -> drop proxy 0');
  if (!has1h) winNote.push('1h window unavailable (pool too young)');
  const rawBlocks = [buyBlock, buyBlock - 60, buyBlock - 1800, buyBlock - 43200];
  const clamped1h = rawBlocks[2] < POOL_DEPLOY_BLOCK; // 1h window fell back to pool-birth
  const clampedNote = blocks.some((b, ix) => rawBlocks[ix] < POOL_DEPLOY_BLOCK)
    ? ' (windows clamped to pool deploy block)' : '';
  const dropPct2 = has2min ? (p2min - pBuy) / p2min * 100 : 0;   // % drop over ~2min window (proxy for two-tick drop)
  // dip reference: prefer the 1h window; fall back to 2min when the pool is
  // younger than an hour; 0 only when neither exists. The label says which.
  const dipRef = has1h ? p1h : (has2min ? p2min : 0);
  const dipRefLabel = has1h
    ? (clamped1h ? '~pool-birth price (1h n/a)' : '~1h-ago price')
    : (has2min ? '~2min-ago price (1h n/a)' : 'n/a');
  const dPct = dipRef > 0 ? (dipRef - pBuy) / dipRef * 100 : 0;  // % dip from dip-ref price (proxy for dip-from-1h-high)
  if (winNote.length) log(`reconstructBuyCombo: ${winNote.join('; ')}${clampedNote}`);
  const aboveLowNote = (p24h && Number.isFinite(p24h))
    ? `+${(((pBuy - p24h) / p24h) * 100).toFixed(1)}% vs 24h-ago`
    : '24h-ago n/a (pool did not exist)';
  // Approximation 3: the wallet's seeded params stand in for the firing combo's
  // thresholds — seed is per-wallet persistent (margin/size/cooldownMin) and the
  // dump/value regime comes from the archive reads above.
  // (review) HONESTY CHECK. snapDump(0) = 30 and snapValue(0) = 70, so a buy with NO
  // dip at all used to be credited to the 30%-dump / 70%-dip cell — a combo that could
  // not have fired. That is where every "learned" 30_70_* Q-value in the live tables
  // came from: fabricated attribution. If no grid cell's gate would have fired at the
  // reconstructed regime, the only honest key is the baseline.
  if (dropPct2 < Math.min(...DUMP_GRID) && dPct < Math.min(...VALUE_GRID)) {
    log(`reconstructBuyCombo: regime at buy (drop ~${dropPct2.toFixed(1)}%, dip ~${dPct.toFixed(1)}%) would not fire any grid combo — crediting ${BASELINE_UNATTRIBUTED_KEY}`);
    return BASELINE_UNATTRIBUTED_KEY;
  }
  const dumpB = snapDump(Math.max(0, dropPct2));
  const valueB = snapValue(Math.max(0, dPct));
  const marginB = snapMargin(Number(seed && seed.margin) || 1);
  const sizeB = snapSize(Number(seed && seed.size) || 60);
  const cdB = snapCd(Number(seed && seed.cooldownMin) || 11);
  const key = comboKey(dumpB, valueB, marginB, sizeB, cdB);
  // Sanity: the result must be a real grid cell. An off-grid key would plant the
  // same dead-key poison class as the orphan key itself — never write it.
  if (!(key in blankQTable())) {
    log(`reconstructBuyCombo: off-grid key ${key} — crediting ${BASELINE_UNATTRIBUTED_KEY}`);
    return BASELINE_UNATTRIBUTED_KEY;
  }
  log(`reconstructBuyCombo: orphan re-attributed -> ${key} (proxies: 2min drop ~${dropPct2.toFixed(1)}%, dip-from-${dipRefLabel} ~${dPct.toFixed(1)}%, ${aboveLowNote}; seed margin/size/cd)`);
  return key;
}

export { reconstructBuyCombo };
