// src/bandit.js — Epsilon-greedy combo selection (the "Q-learning", which is really a bandit).
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { EPSILON } from './config.js';
import { parseCombo, rngNext } from './qtable.js';
// ------------------------------------------------------------------ RL bandit ---
// Adaptive exploration (2026-10-07 23:05 EDT, superintelligence #8): epsilon
// scales with the fleet's recent learning velocity. Flatline (avg reward < 10)
// -> explore more (break deadlocks). Learning well (avg > 100) -> exploit more.
// WREN — two known weaknesses of this bandit (not changed here, on purpose; test any
// change in sim/tournament.mjs first):
//  (a) SAMPLE SIZE. 432 arms per wallet, ~3 closes per wallet per day. Each arm needs
//      maybe 5-10 samples before its average means anything -> years. Options: a
//      FACTORED bandit (learn dump, value, margin, size, cd as 5 small independent
//      tables: 4+3+3+3+4 = 17 arms), or Thompson sampling instead of epsilon-greedy.
//  (b) RE-ROLL BIAS. While flat, a new combo is drawn EVERY tick and the buy fires if
//      THAT combo's gate passes. Exploration therefore over-credits loose-threshold
//      combos (they pass more often). Fix: draw once after each close and keep it until
//      it trades or N ticks pass.
function selectCombo(qtable, rngState, log, epsilon = EPSILON) {
  // Defense-in-depth (2026-10-08): keys whose parseCombo yields non-finite fields
  // (e.g. 'baseline_unattributed', and any raw 'orphan_*' key that somehow lands in
  // the table) are selectable-IN-table but NEVER selected — a NaN threshold in the
  // live strategy is bandit poisoning. The bandit only ever picks real grid cells.
  let keys = Object.keys(qtable).filter((k) => {
    const p = parseCombo(k);
    return Number.isFinite(p.dump) && Number.isFinite(p.value) && Number.isFinite(p.margin) && Number.isFinite(p.size);
  });
  if (!keys.length) { // unreachable on a sane table (432 grid keys) — fall back loudly, never crash
    log('selectCombo: no finite-parse keys found — falling back to full key set');
    keys = Object.keys(qtable);
  }
  if (rngNext(rngState) < epsilon) {
    const k = keys[Math.floor(rngNext(rngState) * keys.length)];
    log(`bandit EXPLORE (eps ${epsilon.toFixed(2)}): trying combo ${k}`);
    return k;
  }
  let best = keys[0], bestV = -Infinity;
  const tied = [];
  for (const k of keys) {
    if (qtable[k] > bestV) { bestV = qtable[k]; best = k; tied.length = 0; tied.push(k); }
    else if (qtable[k] === bestV) tied.push(k);
  }
  const pick = tied[Math.floor(rngNext(rngState) * tied.length)];
  log(`bandit EXPLOIT: combo ${pick} (Q=${qtable[pick].toFixed(2)})`);
  return pick;
}
// (parseCombo defined with the combo helpers above; carries the learnable cd)

export { selectCombo };
