// src/buy.js — executeBuy — MONEY PATH. Write-ahead record, broadcast, position record.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { formatEther } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { heartbeatPts } from './close.js';
import { BRAWL, BURNERS, ERC20_ABI, GAS_RESERVE_WEI } from './config.js';
import { getQuote, sendRawTx, txCostUsd, waitReceipt } from './execution.js';
import { kvGet, kvPut, kvPutCritical } from './kv.js';
import { clampCd, comboKey } from './qtable.js';
// ------------------------------------------------------------------ buy ---
// %-SIZED: buy combo.size % of post-reserve balance (Anthony 2026-10-07 14:11 —
// fixed $ is wrong; sizing scales with portfolio. The % is learnable via the RL grid).
async function executeBuy(ctx, i, combo, dipPct, log) {
  const { env, publicClient, ethUsd, priceWeth, dryRun } = ctx;
  const addr = BURNERS[i];

  const ethBal = await publicClient.getBalance({ address: addr });
  // Reserve: gas for this buy + gas for the eventual sell + dust.
  // (Anthony 2026-10-07 16:28: lowered from 4x to 1x GAS_RESERVE so the
  //  $0.27-funded burners can trade — 0.00005 reserve leaves ~$0.10/trade.)
  const reserve = env.GAS_RESERVE_WEI ? BigInt(env.GAS_RESERVE_WEI) : GAS_RESERVE_WEI;
  if (ethBal <= reserve) {
    log(`SKIP buy: balance ${formatEther(ethBal)} ETH <= reserve ${formatEther(reserve)} ETH`);
    return null;
  }
  const avail = ethBal - reserve;
  const buyWei = (avail * BigInt(combo.size)) / 100n;
  const buyUsd = Number(formatEther(buyWei)) * ethUsd;
  log(`buy ${combo.size}% of available: ${formatEther(buyWei)} ETH ($${buyUsd.toFixed(4)})`);

  const q = await getQuote(env, {
    tokenIn: { type: 'eth' },
    tokenOut: { type: 'erc20', address: BRAWL },
    amountInWei: buyWei, sender: addr, log,
  });
  const target = q.call.target;
  log(`quote target=${target} amountOut=${q.quote.amountOut} brawl-wei`);

  if (dryRun) { log('DRY_RUN: skip buy broadcast'); return null; }

  // (review) Q-credit key = the GRID cell the bandit picked. The old code rebuilt the
  // key from combo.size, which the NN overrides with any integer 10-100 — so a close
  // was credited to e.g. "30_70_3_47_cd6", a key that is not in the grid, and the
  // combo that actually fired never learned anything.
  const creditKey = combo.key || comboKey(combo.dump, combo.value, combo.margin, combo.size, clampCd(combo.cd));
  // (review) WRITE-AHEAD: record what we are about to do BEFORE broadcasting. If the
  // tx lands but the position write below fails, orphan reconciliation reads this and
  // keeps the true combo key instead of inventing one. This is the root fix for the
  // "everything lands in baseline_unattributed" problem.
  await kvPutCritical(env, `wallet:${i}:pendingBuy`, { comboKey: creditKey, sizePct: combo.size, ts: Date.now() }, log);

  const account = privateKeyToAccount(env[`BURNER_KEY_${i}`]);
  let hash, gasPrice;
  try {
    ({ hash, gasPrice } = await sendRawTx(publicClient, account, {
      to: target, data: q.call.data, value: BigInt(q.call.value || '0'),
    }, log, { signal: ctx.signal }));
  } catch (e) {
    // Nothing was broadcast — a stale write-ahead record would mislabel a later orphan.
    await kvPut(env, `wallet:${i}:pendingBuy`, null).catch(() => {});
    throw e;
  }
  let rc = null;
  try {
    rc = await waitReceipt(publicClient, hash, log);
    if (rc && rc.status !== '0x1') throw new Error(`buy reverted: ${hash}`);
    if (!rc) throw new Error('receipt unavailable — balance-delta fallback');
  } catch (e) {
    if (String(e.message || '').startsWith('buy reverted')) {
      await kvPut(env, `wallet:${i}:pendingBuy`, null).catch(() => {}); // reverted = no tokens = no orphan
      throw e;
    }
    log(`buy waitReceipt failed (${String(e.message).slice(0, 80)}) — balance-delta fallback`);
    // Retry: the buy often lands 10-40s after the receipt poll gives up.
    let balCheck = 0n;
    for (let attempt = 0; attempt < 6; attempt++) {
      balCheck = await publicClient.readContract({
        address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
      }).catch(() => 0n);
      if (balCheck > 0n) break;
      if (attempt < 5) await new Promise((r) => setTimeout(r, 10000));
    }
    if (balCheck === 0n) throw new Error(`buy unconfirmed after 60s: no receipt and zero BRAWL balance`);
    log(`RECEIPT-FALLBACK: buy confirmed via BRAWL balance ${balCheck}, proceeding without receipt`);
  }
  const buyGasUsd = txCostUsd(rc ? BigInt(rc.gasUsed) : 300000n, gasPrice, ethUsd);

  // Actual received = onchain balance (exact, not quote estimate).
  const balAfter = await publicClient.readContract({
    address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
  });
  const buyCostUsd = Number(formatEther(buyWei)) * ethUsd;
  const buyGasWei = gasPrice * (rc ? BigInt(rc.gasUsed) : 300000n);
  const position = {
    buyCostUsd, buyGasUsd,
    amountWei: balAfter.toString(),
    buyPriceWeth: priceWeth,
    comboKey: creditKey,
    marginAtOpen: combo.margin,
    sizeAtOpen: combo.size,
    buyTx: hash, buyTs: Date.now(),
    // Buy block for honest combo re-attribution (2026-10-08 deadlock breaker):
    // if this position ever closes as an orphan, reconstructBuyCombo uses the
    // onchain regime at THIS block. Null when the receipt was unavailable.
    buyBlock: rc ? Number(rc.blockNumber) : null,
    // Post-buy ETH balance — stale-clear profit reconstruction baseline:
    // a later sale shows up as ethNow - ethBalPostBuy > 0.
    ethBalPostBuy: (ethBal - buyWei - buyGasWei).toString(),
  };
  await kvPutCritical(env, `wallet:${i}:position`, position, log);
  // Write-ahead consumed. Must NOT throw: on Cloudflare KV this is the 2nd write to the
  // same key within ~1s (limit 1 write/s/key -> 429), and a throw here would abort
  // executeBuy AFTER the buy landed, skipping lastTrade + buyLog. A stale record is harmless.
  await kvPut(env, `wallet:${i}:pendingBuy`, null).catch(() => {});
  await kvPutCritical(env, `wallet:${i}:lastTrade`, Date.now(), log);
  log(`BOUGHT ${formatEther(balAfter)} BRAWL for $${buyCostUsd.toFixed(4)} (+$${buyGasUsd.toFixed(4)} gas) tx ${hash}`);
  // ---- Fleet buy log (2026-10-07 23:05 EDT, superintelligence #3 FOMO-exploit) ----
  // Sellers check this log: if someone buys within 2 min after your sell at a
  // higher price, you sold into their FOMO (+200pts). Prune to 15 min on write.
  try {
    const buyLog = (await kvGet(env, 'fleet:buyLog', [])) || [];
    const cutoff = Date.now() - 15 * 60e3;
    const pruned = buyLog.filter((b) => b.ts > cutoff);
    pruned.push({ ts: Date.now(), walletIdx: i, priceSq: ctx.nowSq.toString() });
    await kvPut(env, 'fleet:buyLog', pruned);
  } catch (e) { /* buy log is advisory — never block the buy */ }
  // ---- Swing bonus (2026-10-07 23:37 EDT): bought back in below last sell price.
  // Full swing-trade cycle: sell high -> buy the dip -> bonus scales with the dip.
  // sold $100, rebought $90 = 10% dip = +100pts. Goes to stats.points directly
  // (post-hoc style reward, like the ruthlessness bonuses — not Q-attributable
  // to the entry combo). Clears lastSell so it can't double-count.
  try {
    const ls = await kvGet(env, `wallet:${i}:lastSell`, null);
    if (ls && ls.sq) {
      const sellSqN = Number(BigInt(ls.sq));
      const buySqN = Number(ctx.nowSq);
      if (sellSqN > 0 && buySqN > 0 && buySqN < sellSqN) {
        // (review) sq = sqrtPriceX96^2 is LINEAR in price (price = sq / 2^192), not
        // price^2 — the old sqrt() here halved every swing bonus.
        const dipFrac = 1 - buySqN / sellSqN; // price dip fraction
        const swingBonus = Math.round(dipFrac * 1000);
        if (swingBonus > 0) {
          const st = (await kvGet(env, `wallet:${i}:stats`, null)) || { points: 0 };
          st.points = (st.points || 0) + swingBonus;
          await kvPut(env, `wallet:${i}:stats`, st);
          const sellPx = sellSqN / 2 ** 192, buyPx = buySqN / 2 ** 192;
          log(`SWING BONUS: +${swingBonus}pts (sold ${sellPx.toExponential(3)}, rebought ${buyPx.toExponential(3)}, ${(dipFrac * 100).toFixed(1)}% dip)`);
        }
      }
      await kvPut(env, `wallet:${i}:lastSell`, null); // consumed — one bonus per sell
    }
  } catch (e) { /* swing bonus is advisory — never break the buy */ }
  // #7 HEARTBEAT (Anthony 2026-10-08 00:58 EDT): buys keep the market alive too.
  // Base points scaled by flow — rewards trading, not just profit.
  try {
    const hb = heartbeatPts(ctx);
    if (hb > 0) {
      const sth = (await kvGet(env, `wallet:${i}:stats`, null)) || { points: 0 };
      sth.points = (sth.points || 0) + hb;
      await kvPut(env, `wallet:${i}:stats`, sth);
      log(`HEARTBEAT: +${hb}pts (buy kept the market alive)`);
    }
  } catch (e) { /* heartbeat is advisory — never break the buy */ }
  return position;
}

export { executeBuy };
