// src/close.js — Rewards and recordClose: the Q-update, NN training, stats after every close.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { base } from 'viem/chains';
import { reconstructBuyCombo } from './attribution.js';
import { ALPHA, HEARTBEAT_BASE_PTS, HEARTBEAT_HIGH_FLOW_USD, HEARTBEAT_MED_FLOW_USD, HOLDING_TAX_FLAT_PCT, HOLDING_TAX_PER_15MIN, SEED_BASE, SEED_STEP, SELL_PROFIT_MULT } from './config.js';
import { kvGet, kvPut } from './kv.js';
import { NN_IN, nnForward, nnLoad, nnPendingKey, nnSave, nnTrain } from './nn.js';
import { BASELINE_UNATTRIBUTED_KEY, blankQTable, comboKey } from './qtable.js';
// ------------------------------------------------------------------ close accounting ---
// Shared trade-close accounting (Anthony 2026-10-07 15:25): ROI is the goal,
// profit-per-hour is the speed metric.
//   ROI       = profitUsd / (buyCostUsd + buyGasUsd)   [realized portion only]
//   holdHours = (sellTs - buyTs) / 3600000            [>= 1s epsilon]
//   reward    = round(ROI * 10000 / (1 + holdHours))   [ROI in basis points, time-discounted]
// (2026-10-07 22:00 EDT, arena upgrade): reward is now PURE ROI — the old
// formula (profitUsd * 100 * (1+ROI) / (1+hh)) scaled with position SIZE, so
// Q-values reflected capital allocation, not strategy quality. A 50% ROI in 1h
// now scores ~3333 whether the position was $0.10 or $10. Q-values are comparable
// across the 16-wallet heterogeneous fleet. (Historical note: this comment once said
// "QGRID_VER bumped to 5" — the live const is 10; see the QGRID_VER declaration.)
// #7 HEARTBEAT helper: base points per trade, scaled by market flow volume.
// ctx.volumeStats = { buyVol, sellVol } in USD (from swap flow). More flow = higher multiplier.
// Rewards keeping the market alive; profit remains the main driver.
function heartbeatPts(ctx) {
  let mult = 1;
  try {
    const vs = ctx && ctx.volumeStats;
    if (vs) {
      const flow = (vs.buyVol || 0) + (vs.sellVol || 0);
      if (flow >= HEARTBEAT_HIGH_FLOW_USD) mult = 3;
      else if (flow >= HEARTBEAT_MED_FLOW_USD) mult = 2;
    }
  } catch (e) { /* fail-soft: 1x */ }
  return HEARTBEAT_BASE_PTS * mult;
}
// A 20% ROI in 0.5h scores ~1333; a 10% ROI in 0.03h scores ~970. The 1.5x-gas hard
// gate remains the floor.
// (review 2026-10-08) Losses are NOT time-discounted any more. Dividing a negative ROI
// by (1+hours) made a -30% loss held 10h score -273 vs -2000 for the same loss cut in
// 30 min — the bandit was being paid to hold losers. Time only discounts gains.
function closeReward(roi, holdHours) {
  const hh = Math.max(holdHours, 1 / 3600);
  return Math.round(roi >= 0 ? (roi * 10000) / (1 + hh) : roi * 10000);
}
async function recordClose(env, i, position, o, log) {
  const { profitUsd, sellGasUsd, costUsd, costGasUsd, holdHours, hash, reason, estimated,
    firstOutBonus, heartbeatBonus } = o;
  const totalCost = costUsd + costGasUsd;
  const roi = totalCost > 0 ? profitUsd / totalCost : 0;
  const hh = Math.max(holdHours, 1 / 3600); // >= 1s epsilon, no div-by-zero on instant flips
  const gasThreshold = SELL_PROFIT_MULT * (costGasUsd + sellGasUsd);
  // (2026-10-08: points-vs-P&L dominance fix) the Q-table learns ONLY the pure
  // economic signal. Behavioral shaping (first-out bonus, holding tax, heartbeat)
  // goes to `reward` → points/leaderboard/exploration, NEVER to Q. Previously a
  // +500 first-out bonus could flip a -30% ROI loss into a positive Q-update,
  // teaching the bandit that a losing regime was good.
  const baseReward = closeReward(roi, hh);
  let reward = baseReward;

  // #4 FIRST-OUT BONUS (2026-10-07 23:05 EDT): broke the standoff when crowded.
  // Passed in via o.firstOutBonus by executeSell (computed pre-close from fleet state).
  if (firstOutBonus > 0) {
    reward += firstOutBonus;
    log(`FIRST-OUT BONUS: +${firstOutBonus}pts (sold first while fleet crowded)`);
  }

  // #5 HOLDING TAX (2026-10-07 23:05 EDT, 15min 2026-10-07 23:33 EDT): every 15min held with <1% price move
  // bleeds 10pts. Sitting still is not free — forces action, breaks standoffs.
  // Flatness measured by |ROI| (realized return ~ price move net of gas).
  let holdingTax = 0;
  const quarters = hh * 4;
  if (quarters >= 1 && Math.abs(roi) * 100 < HOLDING_TAX_FLAT_PCT) {
    holdingTax = Math.floor(quarters) * HOLDING_TAX_PER_15MIN;
    reward -= holdingTax;
    log(`HOLDING TAX: -${holdingTax}pts (${Math.floor(quarters)}x15min held, |ROI| ${(Math.abs(roi) * 100).toFixed(2)}% < ${HOLDING_TAX_FLAT_PCT}%)`);
  }

  // #7 HEARTBEAT (Anthony 2026-10-08 00:58 EDT): +pts for trading (keeping the market alive).
  // Passed in via o.heartbeatBonus by executeSell (computed from ctx flow). Scales with volume.
  if (heartbeatBonus > 0) {
    reward += heartbeatBonus;
    log(`HEARTBEAT: +${heartbeatBonus}pts (trade kept the market alive)`);
  }

  const qtable = (await kvGet(env, `wallet:${i}:qtable`)) || blankQTable();
  const ck = position.comboKey;
  // Orphan positions have no attributable combo (the firing combo's KV write was
  // lost) — crediting Q['orphan_0_0_0'] would plant a dead key that parseCombo
  // turns into {dump: NaN,...} and the bandit could then select. Stats below
  // still record the real P&L.
  // (2026-10-07 18:40 EDT: orphan Q-attribution fix.)
  // (2026-10-08: HONEST RE-ATTRIBUTION replaces the skip — the raw orphan key is
  // still NEVER written to the table (poisoning guard stays); the close is credited
  // under the reconstructed regime-at-buy combo, or the visible baseline when
  // reconstruction fails. Q stays learnable: 0/16 wallets would otherwise accrue
  // zero signal forever.)
  let oldQ = 0, newQ = 0, creditedKey = ck;
  if (ck && ck.startsWith('orphan')) {
    const seed = (await kvGet(env, `wallet:${i}:seed`, null)) || {};
    const creditKey = await reconstructBuyCombo(env, o.publicClient, position, seed, log)
      .catch(() => BASELINE_UNATTRIBUTED_KEY);
    creditedKey = creditKey;
    oldQ = qtable[creditKey] ?? 0;
    newQ = oldQ + ALPHA * (baseReward - oldQ);
    qtable[creditKey] = newQ;
    await kvPut(env, `wallet:${i}:qtable`, qtable);
    log(`orphan close: Q credited under ${creditKey} — ${oldQ.toFixed(2)} -> ${newQ.toFixed(2)} (base ${baseReward}, shaped ${reward})`);
  } else {
    oldQ = qtable[ck] ?? 0;
    newQ = oldQ + ALPHA * (baseReward - oldQ);
    qtable[ck] = newQ;
    await kvPut(env, `wallet:${i}:qtable`, qtable);
  }

  // ---- NN online training: one SGD step per head, on the RIGHT features ----
  // ROI-aware targets (Anthony 2026-10-07 15:25): 20% ROI is the "good trade" bar.
  // tBuy: 1 if ROI >= 20%, scaled ROI/0.20 below that, 0 on loss.
  // tSell: 1 if exit cleared the 1.5x bar AND ROI >= 20%, 0.5 if profitable but
  //   below either, 0 on loss. tSize: reinforce the used size (unchanged).
  // (2026-10-08: train/serve skew fix) the buy/size heads train on BUY-time
  // features (nn:pending:{i}, snapshotted by the buy gate); the sell head trains
  // on HOLDING-time features (nn:sellfeat:{i}, snapshotted by the per-tick sell
  // scorer). Previously all three heads trained on buy-time features while the
  // sell head inferred on holding-time features — a real train/serve skew.
  try {
    const pending = await kvGet(env, nnPendingKey(i), null);
    const rngS = (await kvGet(env, `wallet:${i}:rng`)) || { s: (SEED_BASE + i * SEED_STEP) >>> 0 };
    const nnw = await nnLoad(env, i, rngS);
    if (pending && pending.features && pending.features.length === NN_IN) {
      const fwd = nnForward(nnw, pending.features);
      const tBuy = profitUsd <= 0 ? 0 : (roi >= 0.20 ? 1 : Math.max(0, Math.min(1, roi / 0.20)));
      // (review) The old target echoed the size that was used, win or lose — the size
      // head could only learn to imitate itself. Now: winners nudge size up 10 points,
      // losers nudge it down 10. Still crude, but it is an actual learning signal.
      const usedSize = pending.buySizePct || 70;
      const tSizePct = Math.max(10, Math.min(100, usedSize + (profitUsd > 0 ? 10 : -10)));
      const tSize = (tSizePct - 10) / 90;
      nnTrain(nnw, fwd.cache, [tBuy, tSize, 0], [1, 1, 0]);
      log(`NN trained buy/size heads on buy-time features: buy->${tBuy.toFixed(2)} size->${tSize.toFixed(2)}`);
    }
    const pendingSell = await kvGet(env, `nn:sellfeat:${i}`, null);
    if (pendingSell && pendingSell.features && pendingSell.features.length === NN_IN) {
      const fwdS = nnForward(nnw, pendingSell.features);
      const tSell = profitUsd <= 0 ? 0 : ((profitUsd >= gasThreshold && roi >= 0.20) ? 1 : 0.5);
      nnTrain(nnw, fwdS.cache, [0, 0, tSell], [0, 0, 1]);
      log(`NN trained sell head on holding-time features: sell->${tSell.toFixed(2)} (ROI ${(roi * 100).toFixed(1)}%)`);
    }
    // (review) count training closes; the NN only gets authority after NN_MIN_TRAINED.
    if (pending || pendingSell) nnw.nTrained = (nnw.nTrained || 0) + 1;
    await nnSave(env, i, nnw);
    await kvPut(env, nnPendingKey(i), null); // consume
    await kvPut(env, `nn:sellfeat:${i}`, null); // consume
  } catch (e) {
    log(`NN train failed (${e.message}) — bandit Q-update still applied`);
  }

  // ---- First-class ROI facts (Anthony 2026-10-07 15:25) ----
  const stats = (await kvGet(env, `wallet:${i}:stats`)) || { points: 0, trades: 0, wins: 0, losses: 0, pnlUsd: 0, rewards: [] };
  stats.points += reward;
  stats.trades += 1;
  stats.pnlUsd += profitUsd;
  // (review 2026-10-08) win/loss and the tilt streak are judged on REAL P&L, not on
  // the shaped reward — a -$0.01 trade plus a +5 heartbeat used to count as a "win",
  // which corrupted F[41] win rate and F[42] tilt.
  if (profitUsd > 0) stats.wins += 1; else stats.losses += 1;
  // Self-awareness bookkeeping (2026-10-07 23:41 EDT, trader-needs audit F[42]/F[43]):
  // streak = consecutive losses (tilt detector), peakPoints = high-water mark (drawdown).
  if (profitUsd > 0) { stats.streak = 0; } else { stats.streak = (stats.streak || 0) + 1; }
  stats.pnlHistory = [...(stats.pnlHistory || []), profitUsd].slice(-20);
  stats.peakPoints = Math.max(stats.peakPoints || 0, stats.points);
  stats.rewards.push(reward);
  if (stats.rewards.length > 20) stats.rewards.shift();
  stats.totalBuyCostUsd = (stats.totalBuyCostUsd || 0) + totalCost;
  stats.totalHoldHours = (stats.totalHoldHours || 0) + hh;
  stats.avgRoi = stats.totalBuyCostUsd > 0 ? stats.pnlUsd / stats.totalBuyCostUsd : 0;
  stats.profitPerHourUsd = stats.totalHoldHours > 0 ? stats.pnlUsd / stats.totalHoldHours : 0;
  stats.avgHoldMin = stats.trades > 0 ? (stats.totalHoldHours / stats.trades) * 60 : 0;
  stats.bestRoi = Math.max(stats.bestRoi ?? -Infinity, roi);
  await kvPut(env, `wallet:${i}:stats`, stats);

  // ---- Fleet sell log (arena opponent-awareness, 2026-10-07 22:00 EDT) ----
  // Append this close to the fleet-wide sell log so the next tick's fleet stats
  // can compute recent_fleet_sells (sell pressure). Prune to 15 min on write.
  try {
    const sellLog = (await kvGet(env, 'fleet:sellLog', [])) || [];
    const cutoff = Date.now() - 15 * 60e3;
    const pruned = sellLog.filter((ts) => ts > cutoff);
    pruned.push(Date.now());
    await kvPut(env, 'fleet:sellLog', pruned);
  } catch (e) { /* sell log is advisory — never block the close */ }

  // ---- #8 Adaptive exploration tracking (2026-10-07 23:05 EDT) ----
  // Rolling avg of the last 50 rewards across the fleet. Drives dynamic epsilon
  // in selectCombo: flatline (<10) -> explore more; learning well (>100) -> exploit.
  try {
    const recent = (await kvGet(env, 'arena:recentRewards', [])) || [];
    recent.push(reward);
    if (recent.length > 50) recent.splice(0, recent.length - 50);
    await kvPut(env, 'arena:recentRewards', recent);
    const avgR = recent.reduce((a, b) => a + b, 0) / recent.length;
    await kvPut(env, 'arena:avgReward', avgR);
  } catch (e) { /* exploration tracking is advisory */ }

  return { profitUsd, reward, roi, stats, oldQ, newQ, ck, creditedKey, gasThreshold };
}

export { heartbeatPts, closeReward, recordClose };
