// src/config.js — Every constant, address, ABI and tunable. Change numbers HERE, nowhere else.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { rngNext } from './qtable.js';
// ---------------------------------------------------------------- constants ---
const BRAWL = '0x1378d6A633E64f4abc22c07541473e3551E39b3F';
// BRAWL pool init tx 0x805bd0c37846fd569daf74776f73f138344846f49906506160a044a70d7f3f4d
// (2026-10-07 22:35 EDT). Archive reads for historical price windows must never
// target blocks before this — the pool slot doesn't exist there and getSlot0
// returns zeros, which poisons regime proxies. Clamp windows to >= this block.
// (2026-10-08: this was the true cause of the "non-finite price proxy" failures —
// the 24h-window patch fixed only the advisory window; buys happened ~10 min
// after deploy so the 1h window ALSO predated the pool and hit the same zeros.)
const POOL_DEPLOY_BLOCK = 52318773;
const WETH = '0x4200000000000000000000000000000000000006';
const STATEVIEW = '0xA3c0c9b65baD0b08107Aa264b0f3dB444b867A71';
const PERMIT2 = '0x000000000022D473030F116dDEE9F6B43aC78BA3';
const POOLMANAGER = '0x498581ff718922c3f8e6a244956af099b2652b2b'; // canonical V4 PoolManager on Base (code verified 2026-10-03)
const SWAP_TOPIC0 = '0x40e9cecb9f5f1f1c5b9c97dec2917b7ee92e57ba5563708daca94dd84ad7112f'; // Swap(bytes32,address,int128,int128,uint160,uint128,int24,uint24)
// --- PLUS ULTRA senses (Anthony 2026-10-07 23:07: "superhuman eyes and ears") ---
const SWAP_LOOKBACK_BLOCKS = 300;   // ~10 min on Base (2s blocks) — volume/whale window
const WHALE_BRAWL = 1000000;        // single swap moving >1M BRAWL = whale flow
const CIRCUIT_MOVE_PCT = 20;        // >20% in 1 min = halt all trading (ruthless, not reckless)
const CIRCUIT_HALT_MS = 5 * 60e3;   // 5-min cooling halt after a trip
const TWAP_WINDOW_MS = 10 * 60e3;   // 10-min time-weighted average price (manipulation-resistant)
// PoolKey as deployed (birth tick -246000, fee 1%, tickSpacing 200, Zora V4 hook).
// currency0 < currency1: 0x1378... < 0x4200... so BRAWL is currency0.
const POOL_KEY = {
  currency0: BRAWL,
  currency1: WETH,
  fee: 8388608,
  tickSpacing: 200,
  hooks: '0x0469a4Bd3724DC86C9542F4694c976DA13C450c0',
};
const CHAIN_ID = 8453;
const QUOTE_URL = 'https://api-sdk.zora.engineering/quote';
const SLIPPAGE = 0.25; // 25% — BRAWL v2 pool is extremely thin; $0.01 buys revert at 5%

// 16 burner EOAs (addresses are public; PRIVATE KEYS live in Workers secrets).
// `let` so the fork tournament (local-runner/fork-tournament.mjs) can swap in throwaway
// test wallets via env.BURNER_ADDRESSES. On live, leave BURNER_ADDRESSES unset.
let BURNERS = [
  '0x35CdcDe2f918F777edeB72B8dA4928Ce657fdADF',
  '0x191C4bC7D5e70a64ba30A9903C1De4dA75589F23',
  '0xB2f12BC661CE239Ba7607bf7C6b995A8379057E3',
  '0x48F474f5a6211Ae4AB205783F0E0098AB9C71892',
  '0x0C653cb3ECE75Da0ca1A59cAAd4895DA20aAC467',
  '0xaBE70D3707fe5cC1552D234304DF5E9068452c56',
  '0x8260b667eDc1bC004f5B21136E72C0F5EEfB580B',
  '0xF347Df4158BB34019E546284A46197135899EC5a',
  '0x698e5D4E7A49aaDD9d12211edD013F7A05fF0f50',
  '0xf9668E42073c627Eceb6FA2503329AC8708f58aD',
  '0x9aDc821d6022F255660858debAF397bA8cb2a833',
  '0xAdfc49eC07d54308c79a5168eD250D8Bd54a07e5',
  '0x9ae7D79d78bb4925d87394Db2e82C24756CABA7a',
  '0x4fE0e46C0BcCE7AeBe0723f881d0496522221520',
  '0xB72e58C2103F5355f201F8ddfC2EfBe4B850727c',
  '0x9C44D6dF5dDd6fcF9A836Bb11272b1eBac64b9E5',
];

// RL bandit config
let DUMP_GRID = [30, 40, 50, 60];   // crash-buy: sudden-dump entry threshold % (learnable)
                                      // (Anthony 2026-10-07 14:26: thresholds must be learned, not fixed)
let VALUE_GRID = [70, 80, 90];      // value-buy: >=X% below 1h high = cheap (learnable)
const MARGIN_GRID = [1, 3, 5];    // profit margin %
const SIZE_GRID = [60, 70, 80];   // % of post-reserve balance spent per buy — LEARNABLE
                                  // (Anthony 2026-10-07 14:11: fixed $ is wrong; sizing scales with portfolio)
const CD_GRID = [3, 6, 11, 20];   // cooldown minutes between trades — LEARNABLE
                                  // (Anthony 2026-10-07 15:32: fixed cooldowns are bad unless learnable)
const CD_MIN = 2;                 // hard floor: relay/rate sanity
const CD_MAX = 30;                // hard ceiling: no multi-hour stalls from one bad combo pick
const QGRID_VER = 10;             // bump to reset stale Q-tables when the grid changes
                                // v9 (2026-10-07 23:41 EDT): trader-needs audit — NN 39->44 inputs
                                // (F[39] trend efficiency, F[40] level pressure, F[41] win rate,
                                //  F[42] tilt, F[43] drawdown). Old v8 Q-values are
                                //  incompatible with the new feature semantics. Clean reset.
const EPSILON = 0.10;             // base explore rate (dynamically adjusted by arena:avgReward — see #8)
const EPSILON_MIN = 0.05;         // floor for adaptive exploration
const EPSILON_MAX = 0.30;         // ceiling for adaptive exploration
const ALPHA = 0.25;               // Q-learning rate (0.25: ~4 updates to converge — market moves in minutes)
// --- Superintelligence bonuses (Anthony 2026-10-07 23:05: "raise our babies to be super fucking intelligent") ---
const TOP_TICK_DROP_PCT = 5;      // #1: sell, then price drops >=5% in 10 min = called the top
const TOP_TICK_WINDOW_MS = 10 * 60e3;
const TOP_TICK_BONUS_PER_PCT = 500;
const LOSS_CUT_BONUS_PER_PCT = 300; // #2: sold at a loss, price dropped further = smart cut
const FOMO_WINDOW_MS = 2 * 60e3;  // #3: another wallet buys within 2 min after your sell at higher price
// DISABLED (review 2026-10-08): fleet:buyLog only contains OUR wallets, so this bonus
// only ever paid a baby for selling into a SIBLING's buy — same beneficial owner on
// both sides of the flow. That is the onchain shape of a wash trade. Points-only, so
// zeroing it changes no Q-learning; it just stops rewarding self-dealing.
const FOMO_BONUS = 0;             //     (was 200)
const FIRST_OUT_CROWD_THRESH = 0.9; // #4: crowdedness > 0.9 (14.4+/16 holding)...
const FIRST_OUT_WINDOW_MS = 30 * 60e3; // ...and first sell in 30 min = standoff-breaker
const FIRST_OUT_BONUS = 500;
const HOLDING_TAX_PER_15MIN = 10;  // #5: every 15min held with <1% price move bleeds 10pts. No free standoffs. (Anthony 2026-10-07 23:33 EDT: 15min not 1hr)
const HOLDING_TAX_FLAT_PCT = 1.0;
// #7 HEARTBEAT (Anthony 2026-10-08 00:58 EDT): keep the market alive. Every trade (buy or sell)
// earns base heartbeat points, scaled by market flow. Prevents "kill a coin by not doing shit" —
// on a dead coin, trading IS the job (bootstrap momentum). When externals join, the multiplier
// rewards fighting in a live arena. Profit still dominates; heartbeat is the nudge, not the goal.
// DISABLED (review 2026-10-08): paying points for trading-to-keep-a-coin-alive is a
// volume incentive, and 16 wallets with one owner churning a coin for activity is
// exactly what "no fake volume" forbids. Profit is the only thing worth paying for.
const HEARTBEAT_BASE_PTS = 0;       // per trade (was 5)
const HEARTBEAT_MED_FLOW_USD = 1.0; // $1+ volume in window = 2x
const HEARTBEAT_HIGH_FLOW_USD = 10.0; // $10+ volume in window = 3x
const TOURNAMENT_INTERVAL_MS = 24 * 3600e3; // #6: daily zero-sum ranking
const TOURNAMENT_TOP_BONUS = [1000, 600, 300];
const TOURNAMENT_BOT_PENALTY = [300, 600, 1000]; // applied as negative
const SEED_BASE = 1337;
const SEED_STEP = 7919;

// Risk config
const SPIKE_PCT = 10;             // >10% up in one tick = likely Anthony -> sell into it
// (Wren 2026-10-08: spike-pass fix) owner/fleet attribution set for spike exits.
// If a spike's dominant buy volume came from these addresses, the fleet HOLDS —
// selling into the owner's (or its own siblings') buy is the same beneficial
// owner on both sides of the flow.
const OWNER_EOA = '0xa0ed3829C5d349833a7096181A14E5784962f8cb';   // Anthony's EOA
const ORBX_WALLET = '0x430e239b96d9a8fbafdbed30405d8f14d0b36631';  // @orbx
const FLEET_SW = '0x295Df5a0E7462f3Ce8929C3722CD17E257BA98B5';     // smart wallet (babies' home)
const SPIKE_MAX_EXITS_PER_TICK = 4;  // stagger: at most 4 spike exits per tick
const SPIKE_ATTRIB_BLOCKS = 60;      // attribution window: ~2 min of swaps
const SPIKE_ATTRIB_MAX_TX = 12;      // cap tx lookups per spike
const QUIET_MOVE_BPS = 50;        // <0.50% tick-to-tick move = quiet tick, skip trading (Anthony 2026-10-07)
const STOP_LOSS_PCT = 18;         // down 18%+ ... (WAS 20, deadlock breaker 2026-10-08 01:20 EDT)
// TEMPORARY (Anthony 2026-10-08 01:20 EDT "get them trading NOW"): 24h -> 2h to break the
// 16-way holding deadlock. Babies are -18% to -20% underwater, 2.4h held, 0 trades in hours.
// Once they're trading again, restore to 24h.
const STOP_LOSS_HOLD_MS = 2 * 3600 * 1000; // ... held 2h+ -> sell anyway (WAS 24h, deadlock breaker)
// Per-wallet stop-loss desync (2026-10-08): a single fixed threshold made all 16
// wallets fire stop-loss within minutes of each other (observed 13:01–13:02 EDT:
// 6 exits in ~90s on a thin pool — emergent synchronized choreography, which
// Anthony forbids). Each wallet derives its OWN threshold deterministically from
// its index (independent mulberry32 stream from seedParams — no KV migration,
// reproducible across ticks). Heterogeneous risk tolerance = 16 independent
// traders, not a herd.
function walletStopLoss(i) {
  const st = { s: (SEED_BASE + i * 7919 + 13) >>> 0 };
  return {
    pct: 14 + rngNext(st) * 12,               // 14–26% (fleet mean ≈ fixed 18)
    holdMs: (1.5 + rngNext(st) * 3) * 3600e3, // 1.5–4.5h (fleet mean ≈ fixed 2h)
  };
}
// MAX-HOLD (deadlock breaker 2026-10-08): orphan-reconciled positions sit underwater
// vs the 1.5x sell gate on a fictional cost basis, and one-position-per-wallet blocks
// fresh buys — structural freeze, 0/16 learning. Orphan positions older than 8h from
// entry (position.buyTs, the reconciliation time) may exit at market, intentionally
// bypassing the 1.5x gate; max ONE exit per tick (precomputed in runTick in index
// order — race-safe across the 4-way batch). Stop-loss is the precedent: exits that
// knowingly lose money to unfreeze a wallet are discipline, not failure.
const ORPHAN_MAX_HOLD_MS = 8 * 3600 * 1000;
const HIGH_WINDOW_MS = 3600 * 1000;         // 1h rolling high for dip detection
const LOW_WINDOW_MS = 24 * 3600 * 1000;     // 24h rolling low for selective entries
const NEAR_LOW_PCT = 10;           // "near 24h low" = within 10% of it (bottom-buy signal)
const STABLE_MAX_DROP_PCT = 10;      // value-buy stability gate: this tick's drop must be <10%
                                     // (not catching a falling knife mid-crash — the crash gate handles those)
const SELL_PROFIT_MULT = 1.5;     // sell only when profit >= 1.5x total gas (Anthony 2026-10-07)
const PARTIAL_SELL_MIN_USD = 5;   // target-hit: at/above this sell value, take 50% + keep a runner (Anthony 2026-10-07)
const PARTIAL_SELL_FRACTION = 0.5;// tranche size on big positions — runner keeps trailing/stop-loss logic
const RUNNER_DUST_USD = 0.01;     // remaining value below this -> just sell 100% (not worth the extra tx)
// NOTE (review 2026-10-08): the ops brief says "0.0002 ETH is untouchable" but this
// was 0.00005. At ~$0.25/wallet a 0.0002 reserve means NO wallet can buy, so the
// default is left as-is; set env GAS_RESERVE_WEI to enforce the documented rule.
const GAS_RESERVE_WEI = 50000000000000n;     // 0.00005 ETH kept back for future txs
// Catastrophic stop (review 2026-10-08): the per-wallet stop-loss only fires after
// 1.5-4.5h held, so a position down 60% in 10 minutes just sat there. This one has
// no time gate.
const HARD_STOP_PCT = 40;
// Bottom-buy structural fix (review 2026-10-08): "within 10% of the 24h low" fired
// on EVERY new low (low resets to now -> 0% above it), i.e. it bought falling knives.
// Now the low must have held for a while AND price must have bounced off it.
const BOTTOM_MIN_LOW_AGE_MS = 30 * 60e3;   // no new low for 30 min
const BOTTOM_MIN_BOUNCE_PCT = 2;            // at least 2% off the low
// Stored lows more than this many x below spot are treated as corrupt (unit mix-ups,
// pre-pool zero reads, inverted pools) — the cause of the "7e29% above low" logs.
const LOW_SANITY_MAX_RATIO = 1000n;
// NN gate (review 2026-10-08): a ~1.6k-param net trained on a handful of closes is a
// random filter. Veto/sizing/early-exit only switch on after this many trained closes;
// before that the NN is scored and logged but has no say.
const NN_MIN_TRAINED = 100;
const BOARD_LOG_MS = 24 * 3600 * 1000;       // log leaderboard every 24h

const ERC20_ABI = [
  { name: 'balanceOf', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'a', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'allowance', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'o', type: 'address' }, { name: 's', type: 'address' }],
    outputs: [{ type: 'uint256' }] },
  { name: 'approve', type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 's', type: 'address' }, { name: 'a', type: 'uint256' }],
    outputs: [{ type: 'bool' }] },
];
// Permit2 AllowanceTransfer.allowance(owner, token, spender) -> (uint160 amount, uint48 expiration, uint48 nonce)
const PERMIT2_ABI = [
  { name: 'allowance', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }, { name: 'token', type: 'address' }, { name: 'spender', type: 'address' }],
    outputs: [{ name: 'amount', type: 'uint160' }, { name: 'expiration', type: 'uint48' }, { name: 'nonce', type: 'uint48' }] },
];
// EIP-712 types for Permit2 PermitSingle (mirrors @zoralabs/coins-sdk tradeCoin.ts)
const PERMIT_SINGLE_TYPES = {
  PermitSingle: [
    { name: 'details', type: 'PermitDetails' },
    { name: 'spender', type: 'address' },
    { name: 'sigDeadline', type: 'uint256' },
  ],
  PermitDetails: [
    { name: 'token', type: 'address' },
    { name: 'amount', type: 'uint160' },
    { name: 'expiration', type: 'uint48' },
    { name: 'nonce', type: 'uint48' },
  ],
};
const STATEVIEW_ABI = [
  { name: 'getSlot0', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'poolId', type: 'bytes32' }],
    outputs: [
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tick', type: 'int24' },
      { name: 'protocolFee', type: 'uint24' },
      { name: 'lpFee', type: 'uint24' },
    ] },
  // PLUS ULTRA (2026-10-07 23:07): pool liquidity for the 2%-depth market-impact estimate.
  { name: 'getLiquidity', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'poolId', type: 'bytes32' }],
    outputs: [{ name: 'liquidity', type: 'uint128' }] },
];

// Runtime overrides (fork tournament / experiments). ES module bindings can only be
// reassigned by the module that declares them, hence setters.
function setBurners(v) { BURNERS = v; }
function setDumpGrid(v) { DUMP_GRID = v; }
function setValueGrid(v) { VALUE_GRID = v; }

export { BRAWL, POOL_DEPLOY_BLOCK, WETH, STATEVIEW, PERMIT2, POOLMANAGER, SWAP_TOPIC0, SWAP_LOOKBACK_BLOCKS, WHALE_BRAWL, CIRCUIT_MOVE_PCT, CIRCUIT_HALT_MS, TWAP_WINDOW_MS, POOL_KEY, CHAIN_ID, QUOTE_URL, SLIPPAGE, BURNERS, DUMP_GRID, VALUE_GRID, MARGIN_GRID, SIZE_GRID, CD_GRID, CD_MIN, CD_MAX, QGRID_VER, EPSILON, EPSILON_MIN, EPSILON_MAX, ALPHA, TOP_TICK_DROP_PCT, TOP_TICK_WINDOW_MS, TOP_TICK_BONUS_PER_PCT, LOSS_CUT_BONUS_PER_PCT, FOMO_WINDOW_MS, FOMO_BONUS, FIRST_OUT_CROWD_THRESH, FIRST_OUT_WINDOW_MS, FIRST_OUT_BONUS, HOLDING_TAX_PER_15MIN, HOLDING_TAX_FLAT_PCT, HEARTBEAT_BASE_PTS, HEARTBEAT_MED_FLOW_USD, HEARTBEAT_HIGH_FLOW_USD, TOURNAMENT_INTERVAL_MS, TOURNAMENT_TOP_BONUS, TOURNAMENT_BOT_PENALTY, SEED_BASE, SEED_STEP, SPIKE_PCT, OWNER_EOA, ORBX_WALLET, FLEET_SW, SPIKE_MAX_EXITS_PER_TICK, SPIKE_ATTRIB_BLOCKS, SPIKE_ATTRIB_MAX_TX, QUIET_MOVE_BPS, STOP_LOSS_PCT, STOP_LOSS_HOLD_MS, walletStopLoss, ORPHAN_MAX_HOLD_MS, HIGH_WINDOW_MS, LOW_WINDOW_MS, NEAR_LOW_PCT, STABLE_MAX_DROP_PCT, SELL_PROFIT_MULT, PARTIAL_SELL_MIN_USD, PARTIAL_SELL_FRACTION, RUNNER_DUST_USD, GAS_RESERVE_WEI, HARD_STOP_PCT, BOTTOM_MIN_LOW_AGE_MS, BOTTOM_MIN_BOUNCE_PCT, LOW_SANITY_MAX_RATIO, NN_MIN_TRAINED, BOARD_LOG_MS, ERC20_ABI, PERMIT2_ABI, PERMIT_SINGLE_TYPES, STATEVIEW_ABI, setBurners, setDumpGrid, setValueGrid };
