// src/ethusd.js — ETH/USD price (median of 3 APIs, Chainlink fallback, cache).
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { kvGet, kvPut } from './kv.js';
// ------------------------------------------------------------------ ETH/USD ---
// Chainlink ETH/USD feed on Base (read-only fallback when HTTPS price APIs die).
const CHAINLINK_ETHUSD = '0x71041dddad3595F9CEd3DcCFBe3cf133aF4fd0a4';
const CHAINLINK_AGG_ABI = [
  { name: 'latestRoundData', type: 'function', stateMutability: 'view',
    inputs: [], outputs: [
      { name: 'roundId', type: 'uint80' }, { name: 'answer', type: 'int256' },
      { name: 'startedAt', type: 'uint256' }, { name: 'updatedAt', type: 'uint256' },
      { name: 'answeredInRound', type: 'uint80' } ] },
  { name: 'decimals', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
];
const saneEthPrice = p => p > 100 && p < 1000000 && isFinite(p);
async function fetchEthUsd(env, log, publicClient = null) {
  const cached = await kvGet(env, 'ethusd:last', null);
  const tryApi = async (name, url, pick) => {
    try {
      // 25s timeout: degraded egress proven at 8-30s latency (2026-10-02); 10s always dies there.
      const r = await fetch(url, { signal: AbortSignal.timeout(25000) });
      const j = await r.json();
      const p = Number(pick(j));
      if (saneEthPrice(p)) return { name, price: p };
      throw new Error('bad payload');
    } catch (e) {
      log(`${name} failed (${e.message || e})`);
      return null;
    }
  };
  const save = async (p, via) => {
    await kvPut(env, 'ethusd:last', { price: p, ts: Date.now() });
    log(`ETH/USD $${p.toFixed(2)} via ${via}`);
    return p;
  };
  // PLUS ULTRA #9 (2026-10-07 23:07): median-of-3 — query the big three in PARALLEL
  // (one 25s window instead of three sequential), take the median, reject any source
  // more than 2% from the median. A single lying or stale feed can't move us anymore.
  const trio = await Promise.all([
    tryApi('coinbase', 'https://api.coinbase.com/v2/prices/ETH-USD/spot', j => j?.data?.amount),
    tryApi('coingecko', 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd', j => j?.ethereum?.usd),
    tryApi('kraken', 'https://api.kraken.com/0/public/Ticker?pair=ETHUSD', j => j?.result?.XETHZUSD?.c?.[0]),
  ]);
  const good = trio.filter(Boolean);
  if (good.length >= 2) {
    const sorted = [...good].sort((a, b) => a.price - b.price);
    const median = sorted.length === 3 ? sorted[1].price : (sorted[0].price + sorted[1].price) / 2;
    const agreeing = sorted.filter(s => Math.abs(s.price - median) / median <= 0.02);
    if (agreeing.length >= 2) {
      const mp = agreeing.length >= 3 ? agreeing[1].price : (agreeing[0].price + agreeing[1].price) / 2;
      return save(mp, `median-of-3 (${agreeing.map(s => s.name).join('+')})`);
    }
    log(`median-of-3: only ${agreeing.length} agree within 2% of median $${median.toFixed(2)} — falling through`);
  } else {
    log(`median-of-3: only ${good.length}/3 feeds answered — falling through`);
  }
  // Backup: binance (single source).
  const b = await tryApi('binance', 'https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT', j => j?.price);
  if (b) return save(b.price, 'binance');
  // Onchain last resort: Chainlink ETH/USD via the already-working RPC path
  // (pool price reads succeed when HTTPS APIs die — different route).
  if (publicClient) {
    try {
      const [, answer, , updatedAt] = await publicClient.readContract({
        address: CHAINLINK_ETHUSD, abi: CHAINLINK_AGG_ABI, functionName: 'latestRoundData',
      });
      const cp = Number(answer) / 1e8;
      const ageHrs = (Date.now() / 1000 - Number(updatedAt)) / 3600;
      if (saneEthPrice(cp) && ageHrs < 24) {
        return save(cp, `chainlink-onchain (${ageHrs.toFixed(1)}h old round)`);
      }
      log(`chainlink onchain bad (price=${cp}, age=${ageHrs.toFixed(1)}h)`);
    } catch (e) {
      log(`chainlink onchain failed (${e.message || e})`);
    }
  }
  if (cached && Date.now() - cached.ts < 10 * 60 * 1000) {
    log(`using stale ETH/USD $${cached.price} (${Math.round((Date.now() - cached.ts) / 60000)}m old)`);
    return cached.price;
  }
  log('ETH/USD UNKNOWN — skipping USD-dependent logic this tick');
  return null;
}

export { CHAINLINK_ETHUSD, CHAINLINK_AGG_ABI, saneEthPrice, fetchEthUsd };
