// src/execution.js — Talking to the chain: Zora quotes, Permit2 signatures, sending txs, receipts, approvals. MONEY PATH.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { encodeFunctionData, formatEther, maxUint256 } from 'viem';
import { BRAWL, CHAIN_ID, ERC20_ABI, PERMIT2, PERMIT2_ABI, PERMIT_SINGLE_TYPES, QUOTE_URL, SLIPPAGE } from './config.js';
import { raceTimeout } from './kv.js';
// ------------------------------------------------------------------ Zora quote ---
// POST /quote -> {call:{data,value,target}, quote:{amountOut}} — same contract the SDK uses.
async function getQuote(env, { tokenIn, tokenOut, amountInWei, sender, log, signatures }) {
  const body = {
    tokenIn, tokenOut,
    amountIn: amountInWei.toString(),
    slippage: SLIPPAGE,
    chainId: CHAIN_ID,
    sender, recipient: sender,
  };
  if (signatures) body.signatures = signatures;
  const r = await fetch(QUOTE_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'api-key': env.ZORA_API_KEY },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(20000),
  });
  const j = await r.json();
  if (!j?.call?.data || !j?.call?.target) {
    throw new Error(`quote failed: ${JSON.stringify(j).slice(0, 200)}`);
  }
  return j; // {success, call:{data,value,target}, quote:{amountOut, slippage}, permits?}
}

// Resolve Permit2 permits for a sell quote (mirrors @zoralabs/coins-sdk resolveTradePermits):
// for each quote.permits entry, read the FRESH on-chain nonce, sign EIP-712 PermitSingle,
// and re-request the quote with signatures so the API returns final calldata
// (no REPLACE_WITH_PERMIT_SIGNATURE placeholder).
async function resolveSellPermits(env, publicClient, account, quote, amountInWei, log) {
  if (!quote.permits || quote.permits.length === 0) return quote;
  const owner = account.address;
  const signatures = [];
  for (const p of quote.permits) {
    const det = p.permit.details;
    const token = det.token;
    const spender = p.permit.spender;
    // Fresh on-chain nonce (quote's nonce may be stale)
    const [, , nonce] = await publicClient.readContract({
      address: PERMIT2, abi: PERMIT2_ABI, functionName: 'allowance',
      args: [owner, token, spender],
    });
    const message = {
      details: {
        token,
        amount: BigInt(det.amount),
        expiration: Number(det.expiration),
        nonce: Number(nonce),
      },
      spender,
      sigDeadline: BigInt(p.permit.sigDeadline),
    };
    log(`permit debug: quoteNonce=${det.nonce} onchainNonce=${nonce} amount=${det.amount} exp=${det.expiration} sigDeadline=${p.permit.sigDeadline} spender=${spender.slice(0, 10)}`);
    const signature = await account.signTypedData({
      domain: { name: 'Permit2', chainId: CHAIN_ID, verifyingContract: PERMIT2 },
      types: PERMIT_SINGLE_TYPES,
      primaryType: 'PermitSingle',
      message,
    });
    log(`permit signed: token=${token.slice(0, 10)}... amount=${det.amount} nonce=${nonce}`);
    signatures.push({
      signature,
      permit: {
        details: {
          token: message.details.token,
          amount: String(message.details.amount),
          expiration: message.details.expiration,
          nonce: message.details.nonce,
        },
        spender: message.spender,
        sigDeadline: String(message.sigDeadline),
      },
    });
  }
  // Re-quote with signatures -> final calldata (placeholder replaced by API)
  const final = await getQuote(env, {
    tokenIn: { type: 'erc20', address: BRAWL },
    tokenOut: { type: 'eth' },
    amountInWei,
    sender: owner, log, signatures,
  });
  if ((final.call.data || '').includes('REPLACE_WITH_PERMIT')) {
    throw new Error('requote still has permit placeholder — signature not accepted');
  }
  log('permit resolved: final calldata has real signature');
  return final;
}

// ------------------------------------------------------------------ tx send ---
async function sendRawTx(publicClient, account, { to, data, value }, log, opts = {}) {
  // (2026-10-08: cooperative wallet deadline) a timed-out wallet must NEVER
  // broadcast after its deadline — the tick has moved on and a late broadcast
  // risks double-sells or phantom positions. The abort ONLY gates new
  // broadcasts; in-flight settlement (waitReceipt → recordClose) always runs to
  // completion so a broadcast tx is never left unaccounted.
  if (opts.signal && opts.signal.aborted) {
    throw new Error('sendRawTx: wallet deadline exceeded — refusing post-timeout broadcast');
  }
  let nonce, gasPrice, gasEst;
  try { nonce = await publicClient.getTransactionCount({ address: account.address, blockTag: 'pending' }); }
  catch (e) { throw new Error(`sendRawTx: getTransactionCount failed: ${e.message}`); }
  try { gasPrice = await publicClient.getGasPrice(); }
  catch (e) { throw new Error(`sendRawTx: getGasPrice failed: ${e.message}`); }
  const gasPriceBuf = (gasPrice * 110n) / 100n; // +10%
  try { gasEst = await publicClient.estimateGas({ account: account.address, to, data, value }); }
  catch (e) {
    // Diagnose: run eth_call with identical params to capture the revert data (error selector).
    let selector = 'unknown';
    try {
      await publicClient.call({ account: account.address, to, data, value });
    } catch (ce) {
      const m = String(ce.message || ce).match(/0x[0-9a-fA-F]{8,}/);
      selector = m ? m[0].slice(0, 10) : String(ce.message || ce).slice(0, 120);
    }
    log(`REVERT-DIAG to=${to} selector=${selector} dataLen=${(data || '').length}`);
    throw new Error(`sendRawTx: estimateGas failed: ${e.message} [revert=${selector}]`);
  }
  const gasLimit = (gasEst * 120n) / 100n; // +20% buffer
  const signed = await account.signTransaction({
    to, data, value, nonce, gas: gasLimit, gasPrice: gasPriceBuf, chainId: CHAIN_ID,
  });
  const hash = await publicClient.request({ method: 'eth_sendRawTransaction', params: [signed] });
  log(`sent ${hash} (nonce ${nonce}, gas ${gasLimit}, ${formatEther(gasPriceBuf)} gwei-equiv)`);
  return { hash, gasLimit, gasPrice: gasPriceBuf };
}
async function waitReceipt(publicClient, hash, log, timeoutMs = 90000) {
  const t0 = Date.now();
  let errStreak = 0;
  while (Date.now() - t0 < timeoutMs) {
    try {
      // Per-call timeout: a hung RPC must not wedge the tick (2026-10-07 16:45:
      // w8 stuck 16 min on a non-returning receipt call, flock blocked all ticks).
      const rc = await raceTimeout(
        publicClient.request({ method: 'eth_getTransactionReceipt', params: [hash] }),
        15000, 'receipt call timeout');
      if (rc && rc.blockNumber) return rc;
      errStreak = 0;
    } catch (e) {
      // Some RPCs (e.g. publicnode) reject eth_getTransactionReceipt with
      // "Invalid parameters" — this is an RPC limitation, not a bad tx.
      // Don't throw; return null and let the balance-delta fallback confirm.
      // (2026-10-08: w0 sells were failing because this threw instead of falling back.)
      const msg = String(e.message || e);
      if (msg.includes('Invalid parameters')) {
        log(`waitReceipt: RPC rejects receipt method (${msg.slice(0, 60)}) — using balance-delta fallback`);
        return null;
      }
      // RPC may reject receipt calls (e.g. publicnode archive limits) — don't abort, keep polling.
      errStreak++;
      if (errStreak === 1 || errStreak % 10 === 0) log(`waitReceipt: rpc error (streak ${errStreak}): ${String(e.message || e).slice(0, 80)}`);
    }
    await new Promise((r) => setTimeout(r, 3000));
  }
  throw new Error(`no receipt for ${hash} after ${timeoutMs}ms`);
}
const txCostUsd = (gasUsed, gasPriceWei, ethUsd) =>
  Number(formatEther(gasUsed * gasPriceWei)) * ethUsd;

// Approvals for sells: the quote target may pull via Permit2 (Universal Router pattern).
// Approve both target and canonical Permit2 once per wallet — one-time, logged, auditable.
async function ensureSellApproval(publicClient, account, target, amountWei, env, log, dryRun, signal) {
  for (const spender of [target, PERMIT2]) {
    const al = await publicClient.readContract({
      address: BRAWL, abi: ERC20_ABI, functionName: 'allowance',
      args: [account.address, spender],
    });
    if (al >= amountWei) { log(`allowance ok for ${spender.slice(0, 10)}...`); continue; }
    log(`approving ${spender} for BRAWL (maxUint)`);
    if (dryRun) { log('DRY_RUN: skip approve broadcast'); continue; }
    const { hash, gasLimit, gasPrice } = await sendRawTx(publicClient, account, {
      to: BRAWL,
      data: encodeFunctionData({ abi: ERC20_ABI, functionName: 'approve', args: [spender, maxUint256] }),
      value: 0n,
    }, log, { signal });
    const rc = await waitReceipt(publicClient, hash, log);
    if (rc && rc.status !== '0x1') throw new Error(`approve reverted: ${hash}`);
    if (!rc) {
      // 2026-10-08: waitReceipt can return null (RPC rejects the receipt method).
      // NEVER read .status on null (that was the "Cannot read properties of null"
      // crash that aborted sells after a broadcast approve). Confirm via fresh
      // onchain state instead: re-read allowance. Failed/insufficient read =
      // UNKNOWN — throw descriptively, keep the position, NEVER clear or proceed.
      const al2 = await publicClient.readContract({
        address: BRAWL, abi: ERC20_ABI, functionName: 'allowance',
        args: [account.address, spender],
      }).catch(() => null);
      if (al2 === null || al2 < amountWei) {
        throw new Error(`approve UNKNOWN (no receipt, allowance ${al2 === null ? 'read failed' : 'insufficient'}): ${hash} — position retained`);
      }
      log(`approve confirmed via allowance state: ${hash}`);
      continue;
    }
    log(`approve confirmed: ${hash} (gas ${formatEther(BigInt(rc.gasUsed) * gasPrice)} ETH)`);
  }
}

export { getQuote, resolveSellPermits, sendRawTx, waitReceipt, txCostUsd, ensureSellApproval };
