// src/features.js — The 48 NN input features (units: sq is LINEAR in price).
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { HOLDING_TAX_FLAT_PCT, HOLDING_TAX_PER_15MIN } from './config.js';
import { dipBps } from './market.js';
import { NN_IN } from './nn.js';
// ------------------------------------------------------------------ NN features ---
// 38-feature vector. See NN-DESIGN.md for the full table.
// All values normalized to [-1,1] or [0,1]. Missing data -> neutral 0.5 / 0.
function buildFeatures(o) {
  const {
    buckets,       // [{ts, sq:BigInt}] recent price history (ascending ts)
    nowSq, highSq, low24Sq, prevSq, moveBps,
    pattern,       // {avgPumpPct, avgDumpPct, avgCycleMs, lastExtremeDir}
    ethBal, brawlBal, position, stats,
    gasPriceWei, ethUsd, ethUsdPrev1h, now,
    fleet,         // {holdingCount, avgPnlUsd, avgPnlPct, recentSells, ownPnl[]} — arena opponent-awareness
    walletIdx,     // this wallet's index (for own-vs-fleet comparison)
    // PLUS ULTRA senses (2026-10-07 23:07) — computed once per tick, shared via ctx
    volumeStats,   // {buyVol, sellVol} BRAWL over last ~10 min (from Swap events)
    depth2pctWeth, // WETH that moves price 2% (from pool liquidity)
    positionWeth,  // this wallet's position value in WETH (for market impact)
    gasSpike,      // tanh((gwei - lastTickGwei)/5) — gas momentum
    whaleNetBrawl, // whale (>1M BRAWL) net flow, + = net buying
    priceVelAnn,   // annualized volatility from 1-min returns
    lastSell,      // {ts, sq} of this wallet's most recent sell (swing-cycle, 2026-10-07 23:37)
    dataQuality,   // 0..1 fraction of critical tick reads that succeeded (NEVER BE BLIND)
  } = o;
  const F = new Array(NN_IN).fill(0);
  const clip01 = (v) => Math.max(0, Math.min(1, v));
  const tanh10 = (r) => Math.tanh(r * 10); // log-return -> [-1,1]

  // Helper: log return between two sq values over the bucket history.
  const sqAt = (tsAgoMs) => {
    const t = now - tsAgoMs;
    for (let k = buckets.length - 1; k >= 0; k--) {
      if (buckets[k].ts <= t) return buckets[k].sq;
    }
    return buckets.length ? buckets[0].sq : nowSq;
  };
  const logRet = (fromSq, toSq) => {
    if (!fromSq || fromSq <= 0n || !toSq || toSq <= 0n) return 0;
    // (review) sq = sqrtPriceX96^2 = price * 2^192, i.e. LINEAR in price. The old code
    // assumed sq = price^2 and halved every return/volatility feature.
    return Math.log(Number(toSq) / Number(fromSq));
  };

  // 1-5: multi-timeframe returns
  F[0] = tanh10(logRet(sqAt(5 * 60e3), nowSq));
  F[1] = tanh10(logRet(sqAt(15 * 60e3), nowSq));
  F[2] = tanh10(logRet(sqAt(60 * 60e3), nowSq));
  F[3] = tanh10(logRet(sqAt(4 * 3600e3), nowSq));
  F[4] = tanh10(logRet(sqAt(24 * 3600e3), nowSq));

  // 6-7: volatility (stdev of 1-min log returns)
  const rets5m = [], rets1h = [];
  for (let k = 1; k < buckets.length; k++) {
    const dt = buckets[k].ts - buckets[k - 1].ts;
    if (dt <= 0 || dt > 5 * 60e3) continue;
    const r = logRet(buckets[k - 1].sq, buckets[k].sq);
    const age = now - buckets[k].ts;
    if (age <= 5 * 60e3) rets5m.push(r);
    if (age <= 60 * 60e3) rets1h.push(r);
  }
  const stdev = (a) => {
    if (a.length < 2) return 0;
    const m = a.reduce((s, v) => s + v, 0) / a.length;
    return Math.sqrt(a.reduce((s, v) => s + (v - m) * (v - m), 0) / a.length);
  };
  F[5] = clip01(stdev(rets5m) * 20);
  F[6] = clip01(stdev(rets1h) * 20);

  // 8-9: dip below 1h high / above 24h low
  F[7] = clip01(dipBps(highSq, nowSq) / 100 / 100); // dipBps->pct->0..1
  const aboveLow = nowSq > low24Sq ? Number((nowSq - low24Sq) * 10000n / low24Sq) / 100 : 0;
  F[8] = clip01(aboveLow / 200);

  // 10-11: tick move + acceleration
  F[9] = Math.tanh((moveBps / 100) / 5);
  const prevMove = o.prevMoveBps != null ? o.prevMoveBps / 100 : 0;
  F[10] = Math.tanh(((moveBps / 100) - prevMove) / 5);

  // 12: position in 1h range
  const hi = Number(highSq), lo = Number(low24Sq), px = Number(nowSq);
  F[11] = (hi > lo) ? clip01((px - lo) / (hi - lo)) : 0.5;

  // 13-18: pattern regime
  F[12] = clip01((pattern?.avgPumpPct || 0) / 100);
  F[13] = clip01((pattern?.avgDumpPct || 0) / 100);
  F[14] = clip01(Math.log10(1 + (pattern?.avgCycleMs || 0) / 60000) / 3);
  F[15] = pattern?.lastExtremeDir === 'pump' ? 1 : 0;
  F[16] = pattern?.lastExtremeDir === 'dump' ? 1 : 0;
  F[17] = clip01((pattern?.swings1h || 0) / 10);

  // 19-24: wallet state
  const ethN = Number(ethBal) / 1e18;
  const slipN = Number(brawlBal) / 1e18;
  F[18] = clip01(Math.log10(1 + ethN) / 2);
  F[19] = clip01(Math.log10(1 + slipN) / 7);
  if (position && position.buyCostUsd > 0) {
    const pnlPct = o.unrealizedPnlPct != null ? o.unrealizedPnlPct : 0;
    F[20] = Math.tanh(pnlPct / 50);
    F[21] = clip01((now - position.buyTs) / (24 * 3600e3));
    F[22] = 1;
  } else {
    F[20] = 0; F[21] = 0; F[22] = 0;
  }
  F[23] = Math.tanh((stats?.points || 0) / 500);

  // 25-28: market
  const gwei = Number(gasPriceWei) / 1e9;
  F[24] = clip01(Math.log10(1 + gwei) / 2);
  const ethRet = (ethUsdPrev1h && ethUsdPrev1h > 0)
    ? (ethUsd - ethUsdPrev1h) / ethUsdPrev1h : 0;
  F[25] = Math.tanh(ethRet * 50);
  const d = new Date(now);
  const hr = d.getUTCHours() + d.getUTCMinutes() / 60; // UTC hour (fine for cyclical)
  F[26] = Math.sin(2 * Math.PI * hr / 24);
  F[27] = Math.cos(2 * Math.PI * hr / 24);

  // 29-32: fleet opponent-awareness (arena, 2026-10-07 22:00 EDT)
  // Each baby sees the competition: crowdedness, relative standing, sell pressure.
  // Neutral fallbacks preserve v1 behavior when fleet data is unavailable.
  if (fleet) {
    // F[28]: fleet crowdedness — fraction of the 16 currently holding
    F[28] = clip01(fleet.holdingCount / 16);
    // F[29]: fleet average ROI — is the arena winning or losing overall?
    F[29] = Math.tanh((fleet.avgPnlPct || 0) / 50);
    // F[30]: own P&L vs fleet average — am I beating the competition?
    const own = (walletIdx != null && fleet.ownPnl) ? (fleet.ownPnl[walletIdx] || 0) : (stats?.pnlUsd || 0);
    F[30] = Math.tanh((own - (fleet.avgPnlUsd || 0)) * 200); // $0.005 diff -> ~0.76
    // F[31]: recent fleet sell pressure — sells in last 10 min (0-8+ -> 0..1)
    F[31] = clip01((fleet.recentSells || 0) / 8);
  } else {
    F[28] = 0.5; F[29] = 0.5; F[30] = 0.5; F[31] = 0.5;
  }

  // F[32]: max regret — (highest price since entry - current price) / entry price
  // (2026-10-07 23:05 EDT, superintelligence #7). If you held through a 20%
  // peak-to-trough, F[32] ≈ 0.20. The NN learns: high regret = should have sold.
  // Computed from bucket history: peak sq since buyTs vs entry sq vs current.
  F[32] = 0;
  if (position && position.buyTs && buckets && buckets.length > 0 && nowSq > 0n) {
    try {
      const entrySq = sqAt(now - position.buyTs);
      if (entrySq > 0n) {
        let peakSq = entrySq;
        for (const b of buckets) {
          if (b.ts >= position.buyTs && b.sq > peakSq) peakSq = b.sq;
        }
        // regret = (peakPrice - nowPrice) / entryPrice  (sq is linear in price)
        const eN = Number(entrySq);
        const regret = (Number(peakSq) - Number(nowSq)) / eN;
        F[32] = clip01(Math.max(0, regret));
      }
    } catch (e) { F[32] = 0; /* regret is advisory — never break features */ }
  }

  // F[33]-F[37]: PLUS ULTRA senses (2026-10-07 23:07) — superhuman eyes and ears.
  // F[33]: buy/sell volume ratio (last ~10 min, from Swap events). 0.5 = balanced.
  //   Buys >> sells → momentum up. Neutral 0.5 when no swaps seen.
  F[33] = (volumeStats && (volumeStats.buyVol + volumeStats.sellVol) > 0)
    ? clip01(volumeStats.buyVol / (volumeStats.buyVol + volumeStats.sellVol)) : 0.5;
  // F[34]: market impact — my position as a fraction of the 2%-move depth.
  //   1.0 = exiting all at once eats ~2% slippage. w0 (57M BRAWL) watches this.
  //   0 = flat (no impact). Neutral 0 when depth unknown.
  F[34] = (depth2pctWeth && depth2pctWeth > 0 && positionWeth)
    ? clip01(positionWeth / depth2pctWeth) : 0;
  // F[35]: gas spike — tanh((gwei - lastTickGwei)/5). Spiking gas → re-time the
  //   exit; the 1.5x profit gate is gas-sensitive in real time. 0 = stable.
  F[35] = gasSpike != null ? Math.max(-1, Math.min(1, gasSpike)) : 0;
  // F[36]: whale net flow (last ~10 min, BRAWL, swaps >1M). + = whales net buying.
  //   The NN already sees fleet flow (F[28-31]); F[36] lets it learn the difference
  //   between fleet moves and true external whales.
  F[36] = whaleNetBrawl != null ? Math.tanh(whaleNetBrawl / 10000000) : 0;
  // F[37]: price velocity — annualized volatility from 1-min returns.
  //   1000% ann vol → 1.0. Fast = opportunity or danger. 0 = dead flat.
  F[37] = priceVelAnn != null ? clip01(priceVelAnn / 10) : 0;

  // F[38]: time since last sell — swing-cycle awareness (2026-10-07 23:37 EDT).
  //   0 = just sold (within 5 min, re-entry window open), 1 = sold >24h ago or
  //   never sold. Helps the NN learn: "I just sold — buy the dip back now or wait?"
  //   Works with the swing bonus: low F[38] + price below last sell = buy-back setup.
  F[38] = 1;
  if (lastSell && lastSell.ts) {
    const sinceSellMs = now - lastSell.ts;
    F[38] = clip01(sinceSellMs / (24 * 3600e3));
  }

  // F[39]-F[43]: trader-needs audit (2026-10-07 23:41 EDT, Anthony: "do it").
  //   What a real trader knows that the babies couldn't see: regime, levels, self.
  // F[39]: trend efficiency — Kaufman Efficiency Ratio over 30 one-min buckets.
  //   |P_now - P_30m_ago| / sum|P_t - P_{t-1}|. 0 = pure chop (every move reverses),
  //   1 = straight trend (every move continues). The #1 trader question: trending
  //   or ranging? Trends → buy dips, let winners run. Ranges → fade extremes.
  //   Fail-soft 0.5 (neutral) when <10 buckets.
  F[39] = 0.5;
  try {
    if (buckets && buckets.length >= 10) {
      // Take up to 31 most recent buckets for 30 one-min intervals.
      const n = Math.min(buckets.length, 31);
      const recent = buckets.slice(buckets.length - n);
      const px = (sq) => Number(sq); // linear in price (review fix: was sqrt)
      const pNow = px(recent[recent.length - 1].sq);
      const pAgo = px(recent[0].sq);
      let pathSum = 0;
      for (let k = 1; k < recent.length; k++) {
        pathSum += Math.abs(px(recent[k].sq) - px(recent[k - 1].sq));
      }
      if (pathSum > 0) {
        F[39] = clip01(Math.abs(pNow - pAgo) / pathSum);
      }
    }
  } catch (e) { F[39] = 0.5; /* regime is advisory — never break features */ }

  // F[40]: level pressure — support/resistance battle detector.
  //   (touches of 1h high - touches of 1h low) in last 4h, tanh-normalized.
  //   +1 = pressing resistance (breakout brewing), -1 = hammering support
  //   (breakdown brewing). Touch = bucket close within 0.5% of the level
  //   (sq is linear in price, so 0.5% in sq = 0.5% in price). Traders trade levels.
  //   Fail-soft 0 when levels unknown.
  F[40] = 0;
  try {
    if (highSq > 0n && low24Sq > 0n && highSq > low24Sq && buckets && buckets.length > 0) {
      const hiN = Number(highSq), loN = Number(low24Sq);
      const cutoff4h = now - 4 * 3600e3;
      let touchHi = 0, touchLo = 0;
      for (const b of buckets) {
        if (b.ts < cutoff4h) continue;
        const sqN = Number(b.sq);
        if (sqN <= 0) continue;
        // Within 0.5% of the level (sq is linear in price — review fix: was 1%).
        if (Math.abs(sqN - hiN) / hiN < 0.005) touchHi++;
        if (Math.abs(sqN - loN) / loN < 0.005) touchLo++;
      }
      F[40] = Math.tanh((touchHi - touchLo) / 4);
    }
  } catch (e) { F[40] = 0; /* levels are advisory — never break features */ }

  // F[41]: win rate — self-awareness. (wins_last20 / 20 - 0.5) * 2 → [-1, 1].
  //   +1 = hot (20/20 wins), -1 = ice cold (0/20). Lets the NN learn Kelly-style
  //   sizing: big when proven, small when cold. Fail-soft 0 for fresh wallets.
  F[41] = 0;
  try {
    if (stats && stats.trades > 0) {
      // (review) prefer real P&L history; shaped rewards are a fallback for old stats.
      const rw = stats.pnlHistory && stats.pnlHistory.length ? stats.pnlHistory : (stats.rewards || []);
      if (rw.length > 0) {
        const wins20 = rw.filter((r) => r > 0).length;
        F[41] = (wins20 / rw.length - 0.5) * 2;
      } else {
        // Fall back to cumulative counters when rewards history is absent.
        F[41] = ((stats.wins || 0) / stats.trades - 0.5) * 2;
      }
    }
  } catch (e) { F[41] = 0; /* self-stats are advisory */ }

  // F[42]: tilt — consecutive-loss detector. tanh(streak / 3) → [0, 1).
  //   0 = no tilt (last trade won or fresh), →1 = deep tilt (5+ straight losses).
  //   After repeated losses the learned policy is likely miscalibrated to the
  //   current regime — size should shrink until edge re-proves. Fail-soft 0.
  F[42] = 0;
  try {
    const streak = (stats && stats.streak) || 0;
    F[42] = Math.tanh(streak / 3);
  } catch (e) { F[42] = 0; /* tilt is advisory */ }

  // F[43]: drawdown — distance from peak equity. (peakPoints - points) / peakPoints.
  //   0 = at all-time high, →1 = deep hole. Capital preservation mode: deep
  //   drawdown → fewer chances, tighter exits. Fail-soft 0 (fresh or at peak).
  F[43] = 0;
  try {
    const pts = (stats && stats.points) || 0;
    const peak = (stats && stats.peakPoints) || 0;
    if (peak > 0 && pts < peak) {
      F[43] = clip01((peak - pts) / peak);
    }
  } catch (e) { F[43] = 0; /* drawdown is advisory */ }

  // F[44]: holding bleed — LIVE accrued holding-tax liability (2026-10-08 00:04 EDT,
  //   Anthony: "yea we need to improve that line of thinking...").
  //   The tax itself is still deducted at recordClose(); this feature exposes the
  //   accruing bill so the NN FEELS the clock ticking instead of sitting free.
  //   Same rule as recordClose: 10pts per 15min held while |ROI| < 1%.
  //   F[44] = clip01(accruedPts / 100). 0 = fresh or winning (no bleed),
  //   →1 = 100+ pts bleeding (deep standoff). Fail-soft 0 (no position).
  F[44] = 0;
  try {
    if (position && position.buyTs && now > position.buyTs) {
      const pnlPctLive = o.unrealizedPnlPct != null ? o.unrealizedPnlPct : 0;
      if (Math.abs(pnlPctLive) < HOLDING_TAX_FLAT_PCT) {
        const holdMinutes = (now - position.buyTs) / 60000;
        const periods = Math.floor(holdMinutes / 15);
        if (periods >= 1) {
          const accrued = periods * HOLDING_TAX_PER_15MIN;
          F[44] = clip01(accrued / 100);
        }
      }
    }
  } catch (e) { F[44] = 0; /* bleed is advisory — never break features */ }

  // F[45]: data quality — NEVER BE BLIND (Anthony 2026-10-08 00:17 EDT:
  //   "they can never be blind. they can never fail.")
  //   What % of critical data reads succeeded this tick?
  //   1.0 = all fresh, 0.0 = flying blind. Low quality → DO NOT TRADE.
  //   This is intelligent abstention, not the tournament exploit.
  //   Fail-soft: 1.0 (assume good if missing — the tick aborted already if truly blind)
  //   (2026-10-08 fix: was reading out-of-scope `ctx.dataQuality` — always 1.0.
  //   Now passed explicitly through buildFeatures' input object.)
  F[45] = 1.0;
  try {
    if (typeof dataQuality === 'number') {
      F[45] = clip01(dataQuality);
    }
  } catch (e) { F[45] = 1.0; }

  // F[46]: my rank — where do I stand vs the other 15? (Anthony 2026-10-08 00:45 EDT)
  //   1.0 = #1 (leader), 0.0 = #16 (last). Loser takes risks, winner protects.
  //   Fail-soft 0.5 (middle) if fleet data missing.
  F[46] = 0.5;
  try {
    if (fleet && fleet.rank && typeof walletIdx === 'number' && fleet.rank[walletIdx] != null) {
      F[46] = clip01(fleet.rank[walletIdx] / 15);
    }
  } catch (e) { F[46] = 0.5; }

  // F[47]: leader gap — how far behind #1 am I, in USD? (Anthony 2026-10-08 00:45 EDT)
  //   0.0 = I'm the leader, →1.0 = far behind. Creates urgency.
  //   Normalized: $0.50 gap = 1.0 (babies trade in cents, not dollars).
  //   Balanced for wild competition: based on realized P&L (public onchain), not perfect info.
  //   Fail-soft 0 (assume leader) if missing.
  F[47] = 0;
  try {
    if (fleet && fleet.leaderGapUsd && typeof walletIdx === 'number' && fleet.leaderGapUsd[walletIdx] != null) {
      F[47] = clip01(fleet.leaderGapUsd[walletIdx] / 0.5);
    }
  } catch (e) { F[47] = 0; }

  return F;
}

export { buildFeatures };
