// src/fleet.js — Fleet-wide stats each tick (who holds, P&L ranks).
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { BURNERS } from './config.js';
import { kvGet } from './kv.js';
// ------------------------------------------------------------------ fleet stats ---
// Arena opponent-awareness (2026-10-07 22:00 EDT): computed once per tick,
// shared via ctx.fleet to all wallets. Each baby sees the fleet's posture.
//   holdingCount  — wallets currently holding a position (0-16)
//   avgPnlUsd     — mean realized P&L across ALL wallets (competition baseline)
//   avgPnlPct     — mean ROI across wallets with trades (for NN normalization)
//   recentSells   — fleet sells in the last 10 min (sell-pressure signal)
async function computeFleetStats(env, log) {
  const now = Date.now();
  let holdingCount = 0;
  let pnlSum = 0, roiSum = 0, roiN = 0;
  const ownPnl = [];
  for (let i = 0; i < BURNERS.length; i++) {
    try {
      const pos = await kvGet(env, `wallet:${i}:position`, null);
      if (pos) holdingCount++;
      const st = (await kvGet(env, `wallet:${i}:stats`, null)) || {};
      const pnl = st.pnlUsd || 0;
      pnlSum += pnl;
      ownPnl.push(pnl);
      if (st.trades > 0 && st.avgRoi != null) { roiSum += st.avgRoi; roiN++; }
    } catch (e) { ownPnl.push(0); /* one bad wallet never blocks fleet stats */ }
  }
  let recentSells = 0;
  try {
    const sellLog = (await kvGet(env, 'fleet:sellLog', [])) || [];
    const cutoff = now - 10 * 60e3;
    recentSells = sellLog.filter((ts) => ts > cutoff).length;
  } catch (e) { /* advisory */ }
  const fleet = {
    holdingCount,
    avgPnlUsd: pnlSum / BURNERS.length,
    avgPnlPct: roiN > 0 ? (roiSum / roiN) * 100 : 0,
    recentSells,
    ownPnl, // per-wallet realized P&L, index-aligned
    // FIGHT FEATURES (Anthony 2026-10-08 00:45 EDT): rank and leader gap.
    // Each baby sees where it stands vs the other 15. Loser takes risks, winner protects.
    rank: [], // per-wallet rank 0-15 (0=worst, 15=best), index-aligned
    leaderGapUsd: [], // per-wallet USD behind leader (0=leader), index-aligned
  };
  // Compute ranks by P&L (descending)
  const indexed = ownPnl.map((pnl, idx) => ({ pnl, idx }));
  indexed.sort((a, b) => b.pnl - a.pnl);
  const leaderPnl = indexed.length > 0 ? indexed[0].pnl : 0;
  indexed.forEach((item, rank) => {
    fleet.rank[item.idx] = 15 - rank; // 15=best, 0=worst
    fleet.leaderGapUsd[item.idx] = Math.max(0, leaderPnl - item.pnl);
  });
  if (log) log(`fleet: ${holdingCount}/16 holding, avgPnl $${fleet.avgPnlUsd.toFixed(4)}, avgRoi ${fleet.avgPnlPct.toFixed(1)}%, sells10m ${recentSells}`);
  return fleet;
}

export { computeFleetStats };
