// src/kv.js — Timeouts + KV access (kvGet / kvPut / kvPutCritical). All state goes through these three.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

// ------------------------------------------------------------------ timeouts (review) ---
// WREN: `Promise.race([work, new Promise(... setTimeout(reject, ms))])` leaves the timer
// running after `work` wins. On Cloudflare that is harmless; in the LOCAL runner (Node)
// every live timer keeps the process alive. The 120s batch timers kept each
// run-tick.mjs process alive ~2 minutes after the tick finished, holding the flock —
// so the "1-minute" fleet actually ticked every 2-3 minutes. Always clear the timer.
function raceTimeout(promise, ms, message) {
  let timer;
  const t = new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(message)), ms); });
  return Promise.race([promise, t]).finally(() => clearTimeout(timer));
}

// ------------------------------------------------------------------ KV helpers ---
async function kvGet(env, key, fallback = null) {
  try {
    const raw = await env.TRADER_KV.get(key);
    return raw === null ? fallback : JSON.parse(raw);
  } catch (e) {
    return fallback;
  }
}
async function kvPut(env, key, val) {
  await env.TRADER_KV.put(key, JSON.stringify(val));
}

// Retry wrapper for CRITICAL writes (position records). A failed position write
// after an onchain buy = orphan tokens the bot doesn't know it holds.
// (Anthony 2026-10-07 16:15: orphan at 20:11Z — buy tx landed, KV write failed.)
async function kvPutCritical(env, key, val, log, attempts = 3) {
  let lastErr = null;
  for (let a = 1; a <= attempts; a++) {
    try {
      await env.TRADER_KV.put(key, JSON.stringify(val));
      if (a > 1 && log) log(`kvPutCritical ${key} succeeded on attempt ${a}`);
      return;
    } catch (e) {
      lastErr = e;
      if (log) log(`kvPutCritical ${key} attempt ${a}/${attempts} failed: ${String(e.message || e).slice(0, 80)}`);
      if (a < attempts) await new Promise(r => setTimeout(r, 1000 * a));
    }
  }
  throw new Error(`kvPutCritical ${key} failed after ${attempts} attempts: ${String(lastErr?.message || lastErr).slice(0, 120)}`);
}

export { raceTimeout, kvGet, kvPut, kvPutCritical };
