// src/market.js — Pool price math, 24h low, spike attribution, swap flow, depth, TWAP, volatility.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { encodeAbiParameters, keccak256 } from 'viem';
import { BOTTOM_MIN_BOUNCE_PCT, BOTTOM_MIN_LOW_AGE_MS, BRAWL, BURNERS, FLEET_SW, LOW_SANITY_MAX_RATIO, LOW_WINDOW_MS, NEAR_LOW_PCT, ORBX_WALLET, OWNER_EOA, POOLMANAGER, POOL_KEY, SPIKE_ATTRIB_BLOCKS, SPIKE_ATTRIB_MAX_TX, STATEVIEW, STATEVIEW_ABI, SWAP_LOOKBACK_BLOCKS, SWAP_TOPIC0, TWAP_WINDOW_MS, WETH, WHALE_BRAWL } from './config.js';
import { raceTimeout } from './kv.js';
// ------------------------------------------------------------------ pool math ---
let _poolId = null;
function poolId() {
  if (!_poolId) {
    _poolId = keccak256(
      encodeAbiParameters(
        [{ type: 'tuple', components: [
          { type: 'address', name: 'currency0' },
          { type: 'address', name: 'currency1' },
          { type: 'uint24', name: 'fee' },
          { type: 'int24', name: 'tickSpacing' },
          { type: 'address', name: 'hooks' },
        ] }],
        [[POOL_KEY.currency0, POOL_KEY.currency1, POOL_KEY.fee, POOL_KEY.tickSpacing, POOL_KEY.hooks]]
      )
    );
  }
  return _poolId;
}
// We track sq = sqrtPriceX96^2 as BigInt. Price of BRAWL in WETH = sq / 2^192.
// All signal math (dips, spikes) stays in BigInt — no float precision issues.
async function fetchPoolSq(publicClient) {
  const [sqrtPriceX96] = await publicClient.readContract({
    address: STATEVIEW, abi: STATEVIEW_ABI, functionName: 'getSlot0', args: [poolId()],
  });
  return sqrtPriceX96 * sqrtPriceX96; // BigInt
}
function sqToWethPerBrawl(sq) {
  // float, for USD display only — signals use BigInt sq directly
  return Number(sq) / Number(2n ** 192n);
}
// dipBps > 0 means price fell. spikeBps > 0 means price rose.
const dipBps = (highSq, nowSq) => (highSq > 0n ? Number(((highSq - nowSq) * 10000n) / highSq) : 0);
const riseBps = (oldSq, nowSq) => (oldSq > 0n ? Number(((nowSq - oldSq) * 10000n) / oldSq) : 0);

// ------------------------------------------------------------------ 24h low (review) ---
// WREN, READ THIS: the old rule was "keep the stored low until it is 24h old or price
// goes below it, then reset it to the CURRENT price". Three failures came out of that:
//   1. Every reset and every new low set low = now, so "% above 24h low" was 0 and the
//      BOTTOM signal fired on every down-tick of a downtrend (the 9% win rate).
//   2. One corrupt read (pool not yet initialised, an inverted/other pool's price under
//      the same KV key) stuck for 24h and produced "7e29% above low".
//   3. After 24h the low jumped to spot even if price was far above the real recent low.
// rollLow24 fixes 2 and 3: corrupt lows are discarded, expired lows are rebuilt from the
// price buckets we actually have. bottomSignal (below) fixes 1.
// Returns {sq: string, ts: number} where ts = when THIS low was printed.
function rollLow24(stored, nowSq, now, buckets) {
  const fromBuckets = () => {
    let best = { sq: nowSq, ts: now };
    for (const b of buckets || []) {
      const bsq = BigInt(b.sq);
      if (bsq <= 0n || now - b.ts > LOW_WINDOW_MS) continue;
      if (bsq * LOW_SANITY_MAX_RATIO < nowSq) continue; // same sanity rule as below
      if (bsq < best.sq) best = { sq: bsq, ts: b.ts };
    }
    return { sq: best.sq.toString(), ts: best.ts };
  };
  if (!stored || stored.sq == null) return fromBuckets();
  const lowSq = BigInt(stored.sq);
  if (lowSq <= 0n || lowSq * LOW_SANITY_MAX_RATIO < nowSq) return fromBuckets(); // corrupt
  if (now - stored.ts > LOW_WINDOW_MS) return fromBuckets();                     // expired
  if (nowSq < lowSq) return { sq: nowSq.toString(), ts: now };                   // new low
  return { sq: lowSq.toString(), ts: stored.ts };
}
// BOTTOM BUY: buy the HIGHER LOW, not the new low. Price must be off the low by
// BOTTOM_MIN_BOUNCE_PCT..NEAR_LOW_PCT and the low must not have been broken for
// BOTTOM_MIN_LOW_AGE_MS. This is what "support held" means to a human trader.
function bottomSignal(aboveLowPct, lowAgeMs) {
  return aboveLowPct >= BOTTOM_MIN_BOUNCE_PCT && aboveLowPct <= NEAR_LOW_PCT
    && lowAgeMs >= BOTTOM_MIN_LOW_AGE_MS;
}

// ------------------------------------------------------------------ PLUS ULTRA senses ---
// (Anthony 2026-10-07 23:07: "superhuman eyes and ears, plus ultra")
// All functions are advisory and fail-soft: any RPC failure returns null/neutral
// and the NN falls back to neutral feature values. Senses never break the tick.

// EYES #3+#6: swap flow from PoolManager Swap events (last ~10 min).
// Address-only getLogs (Reth rejects topics arrays — TOOLS.md), client-side filter
// (review) UNISWAP V4 SIGN CONVENTION — verified on real Base txs (test/fixtures/v4-swaps.json):
// Swap.amount0/amount1 are deltas FOR THE SWAPPER (not the pool, unlike V3).
//   amount > 0 -> the trader RECEIVED that currency (bought it)
//   amount < 0 -> the trader PAID that currency in (sold it)
// BRAWL is currency0, so amount0 > 0 = trader BOUGHT BRAWL. (The original code had this
// backwards, so buyVol/sellVol and whale direction — NN F[33]/F[36] — were inverted.)
// Returns {buyVol, sellVol, whaleNetBrawl} in BRAWL units, or null on failure.
// (Wren 2026-10-08: spike-pass fix) Attribute a price spike: was the dominant buy
// volume in the last ~2 min from the owner/fleet? Returns { ownerDriven, detail }.
// Fails OPEN (ownerDriven=false) on any RPC error — an unattributable spike is
// treated as an outside big buyer, which is the original intent of the pass.
async function isOwnerDrivenSpike(publicClient, log) {
  const ownerSet = new Set(
    [OWNER_EOA, ORBX_WALLET, FLEET_SW, ...BURNERS].map((a) => a.toLowerCase())
  );
  try {
    const curBlock = await publicClient.getBlockNumber();
    const fromBlock = curBlock > BigInt(SPIKE_ATTRIB_BLOCKS) ? curBlock - BigInt(SPIKE_ATTRIB_BLOCKS) : 0n;
    const logs = await raceTimeout(
      publicClient.getLogs({ address: POOLMANAGER, fromBlock, toBlock: 'latest' }),
      15000, 'spike attribution getLogs timeout');
    const pid = poolId().toLowerCase();
    let swaps = [];
    for (const l of logs) {
      if (!l.topics || l.topics[0]?.toLowerCase() !== SWAP_TOPIC0) continue;
      if (l.topics[1]?.toLowerCase() !== pid) continue; // not our pool
      const dh = l.data.startsWith('0x') ? l.data.slice(2) : l.data;
      if (dh.length < 384) continue;
      let amount0 = BigInt('0x' + dh.slice(0, 64));
      if (amount0 >= 2n ** 255n) amount0 -= 2n ** 256n; // int128 sign-extended
      // (review) V4 deltas are the TRADER's: amount0 > 0 = trader received BRAWL = a BUY.
      // This read `brawl < 0` (V3 convention) and so attributed SELLS, missing the
      // owner's own buys — the fleet would have sold into Anthony's pump anyway.
      const brawl = Number(amount0) / 1e18;
      if (brawl > 0) swaps.push({ tx: l.transactionHash, buyVol: brawl });
    }
    // (review) keep the MOST RECENT buys (the ones that made the spike); the old loop
    // broke after the first 12 in the window, i.e. the oldest.
    swaps = swaps.slice(-SPIKE_ATTRIB_MAX_TX);
    if (!swaps.length) return { ownerDriven: false, detail: 'no buys in window' };
    let ownerBuy = 0, totalBuy = 0;
    for (const s of swaps) {
      totalBuy += s.buyVol;
      try {
        const tx = await raceTimeout(
          publicClient.getTransaction({ hash: s.tx }), 10000, 'spike attribution tx timeout');
        const from = (tx && tx.from ? String(tx.from) : '').toLowerCase();
        if (from && ownerSet.has(from)) ownerBuy += s.buyVol;
      } catch (e) { /* one bad lookup doesn't kill attribution */ }
    }
    const frac = totalBuy > 0 ? ownerBuy / totalBuy : 0;
    log(`spike attribution: owner/fleet bought ${ownerBuy.toFixed(1)} of ${totalBuy.toFixed(1)} BRAWL in window (${(frac * 100).toFixed(0)}%)`);
    return { ownerDriven: frac >= 0.5, detail: `${(frac * 100).toFixed(0)}% owner/fleet` };
  } catch (e) {
    log(`spike attribution failed (${String(e.message || e).slice(0, 80)}) — treating as outside buyer (fail open)`);
    return { ownerDriven: false, detail: 'attribution failed' };
  }
}

async function fetchSwapFlow(publicClient, log) {
  try {
    const curBlock = await publicClient.getBlockNumber();
    const fromBlock = curBlock > BigInt(SWAP_LOOKBACK_BLOCKS) ? curBlock - BigInt(SWAP_LOOKBACK_BLOCKS) : 0n;
    const logs = await publicClient.getLogs({ address: POOLMANAGER, fromBlock, toBlock: 'latest' });
    const pid = poolId().toLowerCase();
    let buyVol = 0, sellVol = 0, whaleNet = 0, n = 0;
    for (const l of logs) {
      if (!l.topics || l.topics[0]?.toLowerCase() !== SWAP_TOPIC0) continue;
      if (l.topics[1]?.toLowerCase() !== pid) continue; // not our pool
      const dh = l.data.startsWith('0x') ? l.data.slice(2) : l.data;
      if (dh.length < 384) continue;
      const words = [];
      for (let k = 0; k < 6; k++) words.push(BigInt('0x' + dh.slice(k * 64, (k + 1) * 64)));
      // int128 sign-extended to 256 bits in the ABI encoding
      let amount0 = words[0];
      if (amount0 >= 2n ** 255n) amount0 -= 2n ** 256n;
      const brawl = Number(amount0) / 1e18; // signed BRAWL for the TRADER (+ = bought)
      if (brawl > 0) buyVol += brawl; else sellVol += -brawl;
      if (Math.abs(brawl) > WHALE_BRAWL) whaleNet += brawl; // + = whales net buying
      n++;
    }
    log(`swap flow: ${n} swaps/10m | buy ${buyVol.toFixed(1)} / sell ${sellVol.toFixed(1)} BRAWL | whale net ${whaleNet >= 0 ? '+' : ''}${whaleNet.toFixed(1)}`);
    return { buyVol, sellVol, whaleNetBrawl: whaleNet };
  } catch (e) {
    log(`swap flow failed (${e.message || e}) — volume/whale features neutral`);
    return null;
  }
}

// EYES #4: 2%-depth market-impact estimate from pool liquidity.
// For concentrated liquidity near the current tick: Δy ≈ L · Δ(sqrtP), and a 2%
// price move needs Δ(sqrtP)/sqrtP ≈ 1% (P = sqrtP², so dP/P = 2·d(sqrtP)/sqrtP).
// With sqrtP = sqrt(P) from the float price: depth(WETH) ≈ L · 0.01 · sqrt(P) / 1e18.
// A wallet whose position is 1.0× this depth would eat ~2% slippage exiting all
// at once. Returns WETH, or null on failure.
async function fetchDepth2pctWeth(publicClient, priceWeth, log) {
  try {
    const liq = await publicClient.readContract({
      address: STATEVIEW, abi: STATEVIEW_ABI, functionName: 'getLiquidity', args: [poolId()],
    });
    const depth = Number(liq) * 0.01 * Math.sqrt(priceWeth) / 1e18;
    if (depth > 0 && isFinite(depth)) {
      log(`depth: 2%-move ≈ ${depth.toFixed(4)} WETH (L=${liq.toString()})`);
      return depth;
    }
    return null;
  } catch (e) {
    log(`depth read failed (${e.message || e}) — market-impact feature neutral`);
    return null;
  }
}

// EYES #2: 10-min time-weighted average price (manipulation-resistant).
// Smart money watches TWAP, not the spot print a single trade can push.
function computeTwapSq(buckets, now) {
  try {
    if (!buckets || buckets.length < 2) return null;
    const start = now - TWAP_WINDOW_MS;
    let acc = 0n, total = 0n;
    for (let k = 0; k < buckets.length; k++) {
      const t0 = Math.max(buckets[k].ts, start);
      const t1 = k + 1 < buckets.length ? buckets[k + 1].ts : now;
      if (t1 <= t0 || t1 <= start) continue;
      const dt = BigInt(Math.round(t1 - t0));
      acc += buckets[k].sq * dt;
      total += dt;
    }
    if (total === 0n) return null;
    return acc / total;
  } catch (e) { return null; }
}

// EARS #8: annualized volatility from 1-min log returns (last 60 min).
// Not just "price moved" — HOW FAST. Fast = opportunity or danger.
function computePriceVelAnn(buckets, now) {
  try {
    if (!buckets || buckets.length < 3) return 0;
    const rets = [];
    for (let k = 1; k < buckets.length; k++) {
      const dt = buckets[k].ts - buckets[k - 1].ts;
      if (dt <= 0 || dt > 5 * 60e3) continue;
      if (now - buckets[k].ts > 60 * 60e3) continue;
      const a = buckets[k - 1].sq, b = buckets[k].sq;
      if (a <= 0n || b <= 0n) continue;
      rets.push(Math.log(Number(b) / Number(a))); // sq is linear in price (review fix: was 0.5*log)
    }
    if (rets.length < 2) return 0;
    const m = rets.reduce((s, v) => s + v, 0) / rets.length;
    const sd = Math.sqrt(rets.reduce((s, v) => s + (v - m) * (v - m), 0) / rets.length);
    return sd * Math.sqrt(525600); // per-minute stdev → annualized
  } catch (e) { return 0; }
}

export { _poolId, poolId, fetchPoolSq, sqToWethPerBrawl, dipBps, riseBps, rollLow24, bottomSignal, isOwnerDrivenSpike, fetchSwapFlow, fetchDepth2pctWeth, computeTwapSq, computePriceVelAnn };
