// src/nn.js — The small neural net: init, load/save, forward, one SGD step.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { kvGet, kvPut } from './kv.js';
import { rngNext } from './qtable.js';
// ------------------------------------------------------------------ neural net ---
// Small MLP: 38 -> 24 (ReLU) -> 16 (ReLU) -> 3 (Sigmoid) = [buyScore, buySize, sellScore]
// Pure JS, zero deps. ~1,387 params. Inference <1ms. Per-wallet weights in KV.
// v1: advisory layer on top of the bandit (veto + sizing + early sell).
// v2 (2026-10-07 23:05 EDT): +1 input (F[32] regret) — 33 inputs. Weights re-init.
// v3 (2026-10-07 23:07 EDT): PLUS ULTRA senses +5 inputs (F[33] volume ratio,
//     F[34] market impact, F[35] gas spike, F[36] whale flow, F[37] price velocity)
//     — 38 inputs. Weights re-init.
// v4 (2026-10-07 23:37 EDT): swing-cycle +1 input (F[38] time-since-sell)
//     — 39 inputs. Weights re-init.
// v5 (2026-10-07 23:41 EDT): trader-needs audit +5 inputs (F[39] trend efficiency,
//     F[40] level pressure, F[41] win rate, F[42] tilt, F[43] drawdown)
//     — 44 inputs. Weights re-init.
// Design: NN-DESIGN.md (Anthony 2026-10-07 14:28: "bigger hidden layer... perfect trader").
const NN_IN = 48, NN_H1 = 24, NN_H2 = 16, NN_OUT = 3;
const NN_LR = 0.01;             // online SGD learning rate (conservative)
const NN_VER = 8;               // bump to re-init all weights (v8: 48 inputs, F[46] rank + F[47] leader gap — FIGHT)
const NN_BUY_GATE = 0.35;       // veto buys when buyScore < this
const NN_SELL_TRIGGER = 0.70;   // early-exit when sellScore > this (and profit bar met)
const NN_COIN = 'brawl';       // weight namespace per coin (transfer learning in v2)

const nnKey = (i) => `nn:weights:${NN_COIN}:${i}`;
const nnPendingKey = (i) => `nn:pending:${i}`;

// Xavier uniform init using the wallet's seeded RNG for reproducibility.
function nnInitWeights(rngState) {
  const xavier = (fanIn, fanOut) => {
    const lim = Math.sqrt(6 / (fanIn + fanOut));
    return () => (rngNext(rngState) * 2 - 1) * lim;
  };
  const mk = (rows, cols) => {
    const g = xavier(cols, rows);
    const m = new Array(rows);
    for (let r = 0; r < rows; r++) { m[r] = new Array(cols); for (let c = 0; c < cols; c++) m[r][c] = g(); }
    return m;
  };
  const zeros = (n) => new Array(n).fill(0);
  return {
    w1: mk(NN_H1, NN_IN), b1: zeros(NN_H1),
    w2: mk(NN_H2, NN_H1), b2: zeros(NN_H2),
    w3: mk(NN_OUT, NN_H2), b3: zeros(NN_OUT),
    ver: NN_VER,
  };
}
async function nnLoad(env, i, rngState) {
  let w = await kvGet(env, nnKey(i), null);
  if (!w) {
    w = nnInitWeights(rngState);
    await kvPut(env, nnKey(i), w);
  } else if (w.ver !== NN_VER) {
    // NETWORK SURGERY (Anthony 2026-10-08: "do it properly, not hammering").
    // Instead of wiping on version bump, preserve learned weights and grow.
    // v6 (45 inputs) → v7 (46 inputs): expand w1 rows from 45→46 cols, new col = 0.
    // The new F[45] input starts with zero weight (no effect), learns gradually.
    // Old 45 inputs keep their learned weights. No amnesia.
    if (w.ver === 6 && NN_VER === 7 && w.w1 && w.w1.length === NN_H1 && w.w1[0].length === 45) {
      for (let r = 0; r < NN_H1; r++) {
        w.w1[r].push(0); // new F[45] input weight starts at 0
      }
      w.ver = NN_VER;
      await kvPut(env, nnKey(i), w);
    } else if (w.ver === 7 && NN_VER === 8 && w.w1 && w.w1.length === NN_H1 && w.w1[0].length === 46) {
      // v7 (46 inputs) → v8 (48 inputs): add F[46] rank + F[47] leader gap, both start at 0.
      for (let r = 0; r < NN_H1; r++) {
        w.w1[r].push(0); // F[46] rank
        w.w1[r].push(0); // F[47] leader gap
      }
      w.ver = NN_VER;
      await kvPut(env, nnKey(i), w);
    } else {
      // Unknown version jump — full re-init (safe fallback)
      w = nnInitWeights(rngState);
      await kvPut(env, nnKey(i), w);
    }
  }
  return w;
}
async function nnSave(env, i, w) {
  await kvPut(env, nnKey(i), w);
}

const relu = (x) => (x > 0 ? x : 0);
const sigmoid = (x) => 1 / (1 + Math.exp(-Math.max(-30, Math.min(30, x))));

// Forward pass. Returns {out:[buyScore,buySize,sellScore], cache} — cache holds
// intermediates for backprop.
function nnForward(w, x) {
  const z1 = new Array(NN_H1), a1 = new Array(NN_H1);
  for (let r = 0; r < NN_H1; r++) {
    let s = w.b1[r];
    const wr = w.w1[r];
    for (let c = 0; c < NN_IN; c++) s += wr[c] * x[c];
    z1[r] = s; a1[r] = relu(s);
  }
  const z2 = new Array(NN_H2), a2 = new Array(NN_H2);
  for (let r = 0; r < NN_H2; r++) {
    let s = w.b2[r];
    const wr = w.w2[r];
    for (let c = 0; c < NN_H1; c++) s += wr[c] * a1[c];
    z2[r] = s; a2[r] = relu(s);
  }
  const out = new Array(NN_OUT);
  const z3 = new Array(NN_OUT);
  for (let r = 0; r < NN_OUT; r++) {
    let s = w.b3[r];
    const wr = w.w3[r];
    for (let c = 0; c < NN_H2; c++) s += wr[c] * a2[c];
    z3[r] = s; out[r] = sigmoid(s);
  }
  return { out, cache: { x, z1, a1, z2, a2, z3 } };
}

// One SGD step. target = [tBuyScore, tBuySize, tSellScore], mask = [m0,m1,m2]
// (mask 0 = don't train that output this step).
function nnTrain(w, cache, target, mask) {
  const { x, z1, a1, z2, a2, z3 } = cache;
  const lr = NN_LR;
  // Output layer deltas: dL/dz3 = (out - t) * sigmoid'(z3) * mask
  const d3 = new Array(NN_OUT);
  for (let r = 0; r < NN_OUT; r++) {
    const o = sigmoid(z3[r]);
    d3[r] = mask[r] ? (o - target[r]) * o * (1 - o) : 0;
  }
  // Gradients for w3, b3
  for (let r = 0; r < NN_OUT; r++) {
    if (d3[r] === 0) continue;
    w.b3[r] -= lr * d3[r];
    const wr = w.w3[r];
    for (let c = 0; c < NN_H2; c++) wr[c] -= lr * d3[r] * a2[c];
  }
  // Backprop to layer 2
  const d2 = new Array(NN_H2).fill(0);
  for (let c = 0; c < NN_H2; c++) {
    let s = 0;
    for (let r = 0; r < NN_OUT; r++) s += w.w3[r][c] * d3[r];
    d2[c] = s * (z2[c] > 0 ? 1 : 0);
  }
  for (let r = 0; r < NN_H2; r++) {
    if (d2[r] === 0) continue;
    w.b2[r] -= lr * d2[r];
    const wr = w.w2[r];
    for (let c = 0; c < NN_H1; c++) wr[c] -= lr * d2[r] * a1[c];
  }
  // Backprop to layer 1
  const d1 = new Array(NN_H1).fill(0);
  for (let c = 0; c < NN_H1; c++) {
    let s = 0;
    for (let r = 0; r < NN_H2; r++) s += w.w2[r][c] * d2[r];
    d1[c] = s * (z1[c] > 0 ? 1 : 0);
  }
  for (let r = 0; r < NN_H1; r++) {
    if (d1[r] === 0) continue;
    w.b1[r] -= lr * d1[r];
    const wr = w.w1[r];
    for (let c = 0; c < NN_IN; c++) wr[c] -= lr * d1[r] * x[c];
  }
  return w;
}

export { NN_IN, NN_H1, NN_H2, NN_OUT, NN_LR, NN_VER, NN_BUY_GATE, NN_SELL_TRIGGER, NN_COIN, nnKey, nnPendingKey, nnInitWeights, nnLoad, nnSave, relu, sigmoid, nnForward, nnTrain };
