// src/patterns.js — Pump/dump pattern memory and the leaderboard.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { BOARD_LOG_MS, BURNERS } from './config.js';
import { kvGet, kvPut } from './kv.js';
// ------------------------------------------------------- pattern learning ---
// Track the coin's pump/dump cycles so the bot learns THIS coin's rhythm.
// A "swing" is a >5% move from the last recorded extreme; we log its size,
// direction, and duration, then maintain rolling averages in KV.
const SWING_PCT = 5;
async function updatePatterns(env, prevSq, nowSq, now, log) {
  let pat = (await kvGet(env, 'pattern', null)) || {
    pumps: [], dumps: [],
    avgPumpPct: 0, avgDumpPct: 0, avgCycleMs: 0,
    lastExtremeSq: nowSq.toString(), lastExtremeTs: now, lastExtremeDir: null,
    swingTs: [], // timestamps of >5% swings (for swings1h feature)
  };
  if (!pat.swingTs) pat.swingTs = [];
  const lastSq = BigInt(pat.lastExtremeSq);
  if (lastSq === 0n) { pat.lastExtremeSq = nowSq.toString(); pat.lastExtremeTs = now; }
  else {
    const moveBps = nowSq >= lastSq
      ? Number((nowSq - lastSq) * 10000n / lastSq)
      : -Number((lastSq - nowSq) * 10000n / lastSq);
    const movePct = moveBps / 100;
    if (Math.abs(movePct) >= SWING_PCT) {
      const dir = movePct > 0 ? 'pump' : 'dump';
      const durMs = now - pat.lastExtremeTs;
      if (dir === 'pump') {
        pat.pumps.push(movePct); if (pat.pumps.length > 20) pat.pumps.shift();
        pat.avgPumpPct = pat.pumps.reduce((a, b) => a + b, 0) / pat.pumps.length;
      } else {
        pat.dumps.push(Math.abs(movePct)); if (pat.dumps.length > 20) pat.dumps.shift();
        pat.avgDumpPct = pat.dumps.reduce((a, b) => a + b, 0) / pat.dumps.length;
      }
      // Cycle = time between consecutive extremes (pump->dump or dump->pump).
      if (pat.lastExtremeDir && pat.lastExtremeDir !== dir) {
        pat.avgCycleMs = pat.avgCycleMs === 0 ? durMs : pat.avgCycleMs * 0.8 + durMs * 0.2;
        log(`PATTERN: ${dir} ${Math.abs(movePct).toFixed(1)}% in ${Math.round(durMs / 60000)}m | avg pump ${pat.avgPumpPct.toFixed(1)}% / dump ${pat.avgDumpPct.toFixed(1)}% / cycle ${Math.round(pat.avgCycleMs / 60000)}m`);
      }
      pat.lastExtremeSq = nowSq.toString();
      pat.lastExtremeTs = now;
      pat.lastExtremeDir = dir;
      pat.swingTs.push(now);
      await kvPut(env, 'pattern', pat);
    }
  }
  // Prune swings older than 1h; expose count for the NN.
  pat.swingTs = pat.swingTs.filter(t => now - t <= 3600e3);
  pat.swings1h = pat.swingTs.length;
  return pat;
}

// ------------------------------------------------------------------ leaderboard ---
async function maybeLogLeaderboard(env, log) {
  const last = (await kvGet(env, 'meta:lastBoardLog', 0));
  const now = Date.now();
  const rows = [];
  for (let i = 0; i < BURNERS.length; i++) {
    const s = (await kvGet(env, `wallet:${i}:stats`)) || { points: 0, trades: 0, pnlUsd: 0 };
    rows.push({ i, points: s.points || 0, pnlUsd: s.pnlUsd || 0, trades: s.trades || 0,
      avgRoi: s.avgRoi || 0, profitPerHourUsd: s.profitPerHourUsd || 0 });
  }
  rows.sort((a, b) => b.points - a.points);
  await kvPut(env, 'leaderboard', rows);
  if (now - last >= BOARD_LOG_MS) {
    log('=== LEADERBOARD (24h) ===');
    rows.forEach((r, rank) =>
      log(`#${rank + 1} w${r.i}: ${r.points}pts | pnl $${r.pnlUsd.toFixed(4)} | ${r.trades} trades | avgROI ${(r.avgRoi * 100).toFixed(1)}% | $/h $${r.profitPerHourUsd.toFixed(2)}`));
    await kvPut(env, 'meta:lastBoardLog', now);
  }
  return rows;
}

export { SWING_PCT, updatePatterns, maybeLogLeaderboard };
