// src/qtable.js — Seeded RNG, combo keys, Q-table shape and migrations. Q-table FORMAT lives here — do not change it casually.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { CD_GRID, CD_MAX, CD_MIN, DUMP_GRID, MARGIN_GRID, SEED_BASE, SEED_STEP, SIZE_GRID, VALUE_GRID } from './config.js';
// ------------------------------------------------------- seeded RNG (mulberry32) ---
// Persistent per-wallet: store {s} in KV so exploration is reproducible across ticks.
function rngNext(st) {
  let s = st.s | 0;
  s = (s + 0x6D2B79F5) | 0;
  let t = Math.imul(s ^ (s >>> 15), 1 | s);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  st.s = s;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
function seedParams(i) {
  // One-shot deterministic seeding for wallet i's heterogeneous params.
  const st = { s: (SEED_BASE + i * SEED_STEP) >>> 0 };
  const dip = 30 + rngNext(st) * 30;         // 30-60% (matches DUMP_GRID range; legacy log-only field)
  const margin = 1 + rngNext(st) * 4;       // 1-5%
  const size = 60 + rngNext(st) * 20;       // 60-80% of post-reserve balance (Anthony 2026-10-07 14:11)
  const cooldownMin = 5 + rngNext(st) * 10;  // 5-15 min
  return { dip, margin, size, cooldownMin, rngState: st };
}
const snapDump = (d) => DUMP_GRID.reduce((a, b) => (Math.abs(b - d) < Math.abs(a - d) ? b : a));
const snapValue = (v) => VALUE_GRID.reduce((a, b) => (Math.abs(b - v) < Math.abs(a - v) ? b : a));
const snapMargin = (m) => MARGIN_GRID.reduce((a, b) => (Math.abs(b - m) < Math.abs(a - m) ? b : a));
const snapSize = (s) => SIZE_GRID.reduce((a, b) => (Math.abs(b - s) < Math.abs(a - s) ? b : a));
const comboKey = (dump, value, margin, size, cd) => `${dump}_${value}_${margin}_${size}_cd${cd}`;
// Visible non-signal baseline (2026-10-08): orphan closes whose buy-time regime can't
// be reconstructed still get honest Q signal here instead of being dropped or, worse,
// credited to the poisoned 'orphan_0_0_0' key. It lives IN the table (accumulates Q
// visibly) but can NEVER drive bandit selection — selectCombo skips keys whose
// parseCombo fields are non-finite (see below). Never silently mapped to a real combo.
const BASELINE_UNATTRIBUTED_KEY = 'baseline_unattributed';
function blankQTable() {
  const q = {};
  for (const du of DUMP_GRID) for (const v of VALUE_GRID) for (const m of MARGIN_GRID) for (const s of SIZE_GRID) for (const c of CD_GRID) q[comboKey(du, v, m, s, c)] = 0;
  q[BASELINE_UNATTRIBUTED_KEY] = 0; // 433rd key: flagged non-signal baseline, never selectable
  return q;
}
const snapCd = (c) => CD_GRID.reduce((a, b) => (Math.abs(b - c) < Math.abs(a - c) ? b : a));
// One-time in-place migration of 4-dim Q-tables (pre-cd) to 5-dim: the learned Q
// value moves to the cd variant nearest the wallet's seeded cooldown; the other
// cd variants start at 0 so epsilon-greedy explores them naturally. Learned Q is
// never reset by this migration.
function migrateQTableCd(q, seedCdMin) {
  const keys = Object.keys(q);
  if (!keys.length || keys.some((k) => /_cd\d+$/.test(k))) return q;
  const near = snapCd(seedCdMin);
  const nq = {};
  for (const k of keys) {
    const Q = q[k];
    for (const c of CD_GRID) nq[`${k}_cd${c}`] = (c === near ? Q : 0);
  }
  return nq;
}
const parseCombo = (k) => {
  const parts = String(k).split('_');
  const nums = parts.map(Number);
  let cd = 11; // default for legacy 4-dim keys and orphan keys
  if (parts.length >= 5) {
    const m = /^cd(\d+(?:\.\d+)?)$/.exec(parts[4]);
    if (m) cd = Number(m[1]);
  }
  return {
    dump: nums[0], value: nums[1], margin: nums[2], size: (nums[3] || 70), cd,
  };
};
const clampCd = (c) => Math.min(CD_MAX, Math.max(CD_MIN, Number.isFinite(c) ? c : 11));

export { rngNext, seedParams, snapDump, snapValue, snapMargin, snapSize, comboKey, BASELINE_UNATTRIBUTED_KEY, blankQTable, snapCd, migrateQTableCd, parseCombo, clampCd };
