// src/sell.js — executeSell — MONEY PATH. Gas bar, spike own-target gate, broadcast, P&L.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { formatEther } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { heartbeatPts, recordClose } from './close.js';
import { BRAWL, BURNERS, ERC20_ABI, FIRST_OUT_BONUS, FIRST_OUT_CROWD_THRESH, FIRST_OUT_WINDOW_MS, RUNNER_DUST_USD, SELL_PROFIT_MULT } from './config.js';
import { ensureSellApproval, getQuote, resolveSellPermits, sendRawTx, txCostUsd, waitReceipt } from './execution.js';
import { kvGet, kvPut } from './kv.js';
// ------------------------------------------------------------------ sell ---
async function executeSell(ctx, i, position, reason, log, fraction = 1.0) {
  const { env, publicClient, ethUsd, dryRun } = ctx;
  const addr = BURNERS[i];

  const bal = await publicClient.readContract({
    address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
  });
  if (bal === 0n) {
    log('position record exists but BRAWL balance is 0 — clearing stale position');
    await kvPut(env, `wallet:${i}:position`, null);
    return null;
  }

  // Partial-sale sizing (Anthony 2026-10-07 15:23): on big positions take a
  // tranche and keep a runner. Integer math only — no float wei.
  //
  // WHALE SAFEGUARD (Anthony 2026-10-07 23:35 EDT, loosened 23:38 EDT): w0 holds 55% of supply.
  // Anthony: "slippage of price crashing is fine... thats kinda going to happen on most coins"
  // Don't over-protect. Cap only at extreme impact (>10x = ~20% slippage). Let them learn.
  // Real traders deal with slippage. If w0 dumps and crashes it, that's the lesson.
  let effFraction = fraction;
  try {
    const priceWeth = ctx.priceWeth;
    const depth2pct = ctx.depth2pctWeth;
    if (priceWeth && depth2pct && depth2pct > 0) {
      const posWeth = (Number(bal) / 1e18) * priceWeth;
      const impact = posWeth / depth2pct; // 1.0 = 2% slippage on full exit
      if (impact > 10.0) {
        const maxFrac = 10.0 / impact;
        if (effFraction > maxFrac) {
          log(`WHALE SAFEGUARD: capping sell ${(effFraction*100).toFixed(0)}% → ${(maxFrac*100).toFixed(0)}% (impact ${impact.toFixed(1)}x would cause ~${(impact*2).toFixed(0)}% slippage)`);
          effFraction = maxFrac;
        }
      }
    }
  } catch (e) { /* safeguard is advisory; never block a sell on error */ }
  const fracBps = Math.max(1, Math.min(10000, Math.round(effFraction * 10000)));
  const sellWei = fracBps >= 10000 ? bal : (bal * BigInt(fracBps)) / 10000n;
  if (sellWei === 0n) { log('sell amount rounds to zero — skip'); return null; }
  const frac = Number(sellWei) / Number(bal); // realized fraction, USD math only

  let q = await getQuote(env, {
    tokenIn: { type: 'erc20', address: BRAWL },
    tokenOut: { type: 'eth' },
    amountInWei: sellWei, sender: addr, log,
  });
  const account = privateKeyToAccount(env[`BURNER_KEY_${i}`]);
  // Permit2: the quote's sell calldata carries a REPLACE_WITH_PERMIT_SIGNATURE placeholder.
  // Sign EIP-712 PermitSingle and re-quote so the API returns final executable calldata.
  q = await resolveSellPermits(env, publicClient, account, q, sellWei, log);
  const target = q.call.target;
  log(`sell quote: target=${target} amountOut=${formatEther(BigInt(q.quote.amountOut))} ETH`);

  // Gas estimate for profitability math (before approval txs muddy it).
  const estGas = await publicClient.estimateGas({
    account: addr, to: target, data: q.call.data, value: 0n,
  }).catch(() => 300000n);
  const gasPrice = await publicClient.getGasPrice();
  const sellGasUsdEst = Number(formatEther(estGas * gasPrice)) * ethUsd;
  const sellValueUsdEst = Number(formatEther(BigInt(q.quote.amountOut))) * ethUsd;
  // Realized portion only: scale cost basis by the fraction actually sold.
  const costUsd = position.buyCostUsd * frac;
  const costGasUsd = position.buyGasUsd * frac;
  const profitEst = sellValueUsdEst - costUsd - costGasUsd - sellGasUsdEst;
  log(`profit est: sell $${sellValueUsdEst.toFixed(4)} - buy $${costUsd.toFixed(4)} - buyGas $${costGasUsd.toFixed(4)} - sellGas $${sellGasUsdEst.toFixed(4)} = $${profitEst.toFixed(4)}${frac < 1 ? ` (${(frac * 100).toFixed(0)}% tranche)` : ''}`);

  // CORE RULE (Anthony 2026-10-07): the sale itself must clear 1.5x ITS gas cost.
  // profit = sell - frac*buy - frac*buyGas - sellGas must clear 1.5 * (frac*buyGas + sellGas).
  // Exempt reasons: 'stop-loss' and 'max-hold' knowingly exit at a loss — the 1.5x gate
  // is INTENTIONALLY bypassed for them (deadlock breakers: an underwater wallet that
  // can never sell can never learn). Stop-loss is the precedent.
  const totalGasUsd = costGasUsd + sellGasUsdEst;
  const minProfit = SELL_PROFIT_MULT * totalGasUsd;
  if (profitEst < minProfit && reason !== 'stop-loss' && reason !== 'max-hold') {
    log(`SKIP sell (${reason}): profit $${profitEst.toFixed(4)} < 1.5x gas ($${minProfit.toFixed(4)})`);
    return null;
  }
  // (Wren 2026-10-08: spike-pass fix) 'spike' exits must ALSO clear the wallet's
  // own margin target — the old spike pass let any holding wallet sell at just
  // the 1.5x-gas bar, which is how 16 wallets synchronized into one tick.
  if (reason === 'spike') {
    // (review) margin on the cost of the fraction actually being sold (costUsd is
    // fraction-scaled). With the full buyCostUsd, a whale-capped partial sell needed
    // the WHOLE position's margin from a fraction of the position.
    const marginUsd = costUsd * (Number(position.marginAtOpen) || 0) / 100;
    const ownTarget = Math.max(minProfit, marginUsd);
    if (profitEst < ownTarget) {
      log(`SKIP sell (spike): profit $${profitEst.toFixed(4)} < own target $${ownTarget.toFixed(4)} (max(1.5x gas, margin))`);
      return null;
    }
  }

  await ensureSellApproval(publicClient, account, target, sellWei, env, log, dryRun, ctx.signal);
  if (dryRun) { log('DRY_RUN: skip sell broadcast'); return null; }

  const ethBefore = await publicClient.getBalance({ address: addr });
  const { hash, gasPrice: gp } = await sendRawTx(publicClient, account, {
    to: target, data: q.call.data, value: 0n,
  }, log, { signal: ctx.signal });
  // Receipt poll with balance-delta fallback (publicnode archive bug can kill
  // eth_getTransactionReceipt; never leave a ghost position or drop a profit).
  let rc = null;
  try {
    rc = await waitReceipt(publicClient, hash, log);
    if (rc && rc.status !== '0x1') throw new Error(`sell reverted: ${hash}`);
    if (!rc) throw new Error('receipt unavailable — balance-delta fallback');
  } catch (e) {
    if (!String(e.message || '').startsWith('sell reverted')) {
      log(`waitReceipt failed (${String(e.message).slice(0, 80)}) — balance-delta fallback`);
      // Retry the balance check: the tx often lands 10-40s after the receipt
      // poll gives up (2026-10-07 18:55 EDT: 11 spike-sells declared dead then
      // confirmed onchain seconds later — dropped P&L across the fleet).
      let balCheck = 0n, confirmed = false;
      const expectedMax = bal - sellWei + sellWei / 100n; // partial-aware, 1% tolerance
      for (let attempt = 0; attempt < 6; attempt++) {
        balCheck = await publicClient.readContract({
          address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
        }).catch(() => bal);
        if (balCheck <= expectedMax) { confirmed = true; break; }
        if (attempt < 5) await new Promise((r) => setTimeout(r, 10000));
      }
      if (!confirmed) throw new Error(`sell unconfirmed after 60s: no receipt and balance ${balCheck} wei > expected ${expectedMax} wei`);
      log(`RECEIPT-FALLBACK: sell confirmed via balance delta (now ${balCheck} wei), proceeding without receipt`);
    } else throw e;
  }
  const ethAfter = await publicClient.getBalance({ address: addr });
  const gasUsedFallback = rc ? BigInt(rc.gasUsed) : estGas;
  const sellGasUsd = txCostUsd(gasUsedFallback, gp, ethUsd);
  // Actual received = ETH balance delta minus the sell tx's own gas (already out of ethAfter).
  // ethAfter = ethBefore - sellGas + sellValue  =>  sellValue = ethAfter - ethBefore + sellGas
  const sellValueUsd = (Number(formatEther(ethAfter - ethBefore)) * ethUsd) + sellGasUsd;
  // Realized portion only (fraction-scaled cost basis).
  const profitUsd = sellValueUsd - costUsd - costGasUsd - sellGasUsd;

  const sellTs = Date.now();
  const holdHours = (sellTs - position.buyTs) / 3600000;
  // #4 FIRST-OUT BONUS (2026-10-07 23:05 EDT): if fleet crowdedness > 0.9 and
  // no sells in the last 30 min, this wallet is breaking the Mexican standoff.
  // Computed pre-close (this sell hasn't hit fleet:sellLog yet, so 0 recent = first).
  let firstOutBonus = 0;
  try {
    const crowded = ctx.fleet ? (ctx.fleet.holdingCount / 16) : 0;
    if (crowded > FIRST_OUT_CROWD_THRESH) {
      const sellLog = (await kvGet(env, 'fleet:sellLog', [])) || [];
      const cutoff30 = sellTs - FIRST_OUT_WINDOW_MS;
      const recentSells30 = sellLog.filter((ts) => ts > cutoff30).length;
      if (recentSells30 === 0) {
        // Proportional: sell 50% = 250pts, sell 100% = 500pts. Partial exits count. (Anthony 2026-10-07 23:33 EDT)
        firstOutBonus = Math.round(FIRST_OUT_BONUS * fraction);
        log(`FIRST-OUT: crowdedness ${crowded.toFixed(2)} > ${FIRST_OUT_CROWD_THRESH}, first sell in 30m (${(fraction*100).toFixed(0)}% of position) — bonus ${firstOutBonus}pts queued`);
      }
    }
  } catch (e) { /* first-out check is advisory */ }
  const rc0 = await recordClose(env, i, position, {
    profitUsd, sellGasUsd, costUsd, costGasUsd, holdHours, hash, reason, firstOutBonus,
    heartbeatBonus: heartbeatPts(ctx), publicClient,
  }, log);
  const { reward, roi, stats, oldQ, creditedKey } = rc0;
  const newQ = rc0.newQ;
  // ---- Deferred ruthlessness scoring (2026-10-07 23:05 EDT, superintelligence #1/#2/#3) ----
  // Store sell context; runTick's scorePendingSells() evaluates 10 min later:
  //   #1 top-tick: price dropped >=5% after sell -> +dropPct*500
  //   #2 loss-cut: sold at loss, price dropped further -> +dropPct*300
  //   #3 FOMO: someone bought within 2 min at higher price -> +200
  try {
    await kvPut(env, `wallet:${i}:pendingSell`, {
      sellTs, sellSq: ctx.nowSq.toString(), roi, reason, scored: false,
    });
  } catch (e) { /* deferred scoring is advisory */ }
  // Swing-cycle (2026-10-07 23:37 EDT): remember this sell's price. When the
  // wallet buys back in lower, executeBuy awards the SWING BONUS. Overwrites on
  // every sell — the most recent exit is the re-entry benchmark.
  try {
    await kvPut(env, `wallet:${i}:lastSell`, { ts: sellTs, sq: ctx.nowSq.toString() });
  } catch (e) { /* lastSell is advisory — never block the sell */ }

  // Runner accounting (Anthony 2026-10-07 15:23): on a partial sale, keep the
  // remainder with proportionally scaled cost basis — it keeps trailing/stop-loss
  // logic on later ticks. Dust remainder (<$0.01 est. value) closes fully.
  const runnerWei = await publicClient.readContract({
    address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
  }).catch(() => 0n);
  if (fracBps >= 10000 || runnerWei === 0n) {
    await kvPut(env, `wallet:${i}:position`, null);
    log(`SOLD (${reason}) 100%: profit $${profitUsd.toFixed(4)} ROI ${(roi * 100).toFixed(1)}% (${reward}pts) | Q[${creditedKey}] ${oldQ.toFixed(2)} -> ${newQ.toFixed(2)} | tx ${hash} | avgROI ${(stats.avgRoi * 100).toFixed(1)}% $/h $${stats.profitPerHourUsd.toFixed(2)} | wallet points now ${stats.points}`);
  } else {
    const runnerFrac = Number(runnerWei) / Number(bal);
    const runnerValueUsd = sellValueUsd * runnerFrac; // proportional estimate
    if (runnerValueUsd < RUNNER_DUST_USD) {
      await kvPut(env, `wallet:${i}:position`, null);
      log(`SOLD (${reason}): runner dust ($${runnerValueUsd.toFixed(4)}) — closed fully | profit $${profitUsd.toFixed(4)} ROI ${(roi * 100).toFixed(1)}% (${reward}pts) | tx ${hash} | avgROI ${(stats.avgRoi * 100).toFixed(1)}% $/h $${stats.profitPerHourUsd.toFixed(2)}`);
    } else {
      const runnerPos = {
        ...position,
        amountWei: runnerWei.toString(),
        buyCostUsd: position.buyCostUsd * runnerFrac,
        buyGasUsd: position.buyGasUsd * runnerFrac,
        buyTx: hash, // latest touch; buyTs keeps original age for stop-loss clock
        ethBalPostBuy: ethAfter.toString(), // re-baseline: partial proceeds already in ethAfter
      };
      await kvPut(env, `wallet:${i}:position`, runnerPos);
      log(`SOLD (${reason}) ${(frac * 100).toFixed(0)}% tranche: profit $${profitUsd.toFixed(4)} ROI ${(roi * 100).toFixed(1)}% (${reward}pts) | runner ${formatEther(runnerWei)} BRAWL (cost $${runnerPos.buyCostUsd.toFixed(4)}) | tx ${hash} | avgROI ${(stats.avgRoi * 100).toFixed(1)}% $/h $${stats.profitPerHourUsd.toFixed(2)} | wallet points now ${stats.points}`);
    }
  }
  await kvPut(env, `wallet:${i}:lastTrade`, Date.now());
  return { profitUsd, reward, fraction: frac };
}

export { executeSell };
