// src/shaping.js — Points-only bonuses/penalties (never touch Q): ruthlessness, cash drag, tournament.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { BURNERS, FOMO_BONUS, FOMO_WINDOW_MS, LOSS_CUT_BONUS_PER_PCT, TOP_TICK_BONUS_PER_PCT, TOP_TICK_DROP_PCT, TOP_TICK_WINDOW_MS, TOURNAMENT_BOT_PENALTY, TOURNAMENT_INTERVAL_MS, TOURNAMENT_TOP_BONUS } from './config.js';
import { kvGet, kvPut } from './kv.js';
// ------------------------------------------------------------------ ruthlessness scoring ---
// Deferred bonuses (2026-10-07 23:05 EDT, superintelligence #1/#2/#3).
// Called once per tick in runTick. For each wallet with an unscored pendingSell
// older than 10 min, evaluates:
//   #1 TOP-TICK: price dropped >=5% since the sell -> bonus = dropPct * 500.
//        You called the top. Ruthless and right.
//   #2 LOSS-CUT: sold at a loss (roi < 0) and price dropped further ->
//        bonus = dropPct * 300. Cutting losers early is discipline.
//   #3 FOMO-EXPLOIT: another wallet bought within 2 min after your sell at a
//        HIGHER price -> bonus = 200. You sold into their FOMO. Predatory.
// Bonuses go straight to stats.points (not the Q-table — they're post-hoc style
// rewards, not attributable to the entry combo).
async function scorePendingSells(env, nowSq, log) {
  if (!nowSq || nowSq <= 0n) return;
  const now = Date.now();
  for (let i = 0; i < BURNERS.length; i++) {
    let pending = null;
    try { pending = await kvGet(env, `wallet:${i}:pendingSell`, null); } catch (e) { continue; }
    if (!pending || pending.scored) continue;
    if (now - pending.sellTs < TOP_TICK_WINDOW_MS) continue; // not ripe yet
    try {
      const sellSq = BigInt(pending.sellSq);
      const sN = Number(sellSq), nN = Number(nowSq);
      let totalBonus = 0;
      const parts = [];
      // #1 + #2: price drop since sell
      if (nN < sN) {
        const dropPct = ((sN - nN) / sN) * 100;
        if (dropPct >= TOP_TICK_DROP_PCT) {
          const b = Math.round(dropPct * TOP_TICK_BONUS_PER_PCT);
          totalBonus += b;
          parts.push(`TOP-TICK +${b} (${dropPct.toFixed(1)}% drop in 10m)`);
        }
        if (pending.roi < 0 && dropPct > 0) {
          const b = Math.round(dropPct * LOSS_CUT_BONUS_PER_PCT);
          totalBonus += b;
          parts.push(`LOSS-CUT +${b} (sold at ${(pending.roi * 100).toFixed(1)}%, dropped ${dropPct.toFixed(1)}% more)`);
        }
      }
      // #3: FOMO — did anyone buy within 2 min after this sell at a higher price?
      try {
        const buyLog = (await kvGet(env, 'fleet:buyLog', [])) || [];
        const fomoBuy = buyLog.find((b) =>
          b.ts > pending.sellTs &&
          b.ts <= pending.sellTs + FOMO_WINDOW_MS &&
          b.walletIdx !== i &&
          BigInt(b.priceSq) > sellSq
        );
        if (fomoBuy) {
          totalBonus += FOMO_BONUS;
          parts.push(`FOMO-EXPLOIT +${FOMO_BONUS} (w${fomoBuy.walletIdx} bought higher within 2m)`);
        }
      } catch (e) { /* FOMO check advisory */ }
      if (totalBonus > 0) {
        const stats = (await kvGet(env, `wallet:${i}:stats`, null)) || { points: 0 };
        stats.points = (stats.points || 0) + totalBonus;
        await kvPut(env, `wallet:${i}:stats`, stats);
        log(`[w${i}] RUTHLESSNESS BONUS +${totalBonus}pts: ${parts.join('; ')}`);
      } else {
        log(`[w${i}] pending sell scored: no ruthlessness bonus (price held)`);
      }
      pending.scored = true;
      await kvPut(env, `wallet:${i}:pendingSell`, pending);
    } catch (e) {
      log(`[w${i}] pending-sell scoring failed (${e.message}) — marking scored to avoid retry loop`);
      try { pending.scored = true; await kvPut(env, `wallet:${i}:pendingSell`, pending); } catch (e2) {}
    }
  }
}

// ------------------------------------------------------------------ cash drag ---
// Swing-cycle (2026-10-07 23:37 EDT): sitting in cash during a rally bleeds.
// If a wallet has NO position, HAS traded before, and BRAWL is up 5%+ in the
// last hour — it's missing the move. -50pts per application, max once per wallet
// per 15 min (per-wallet cooldown prevents -50/min runaway while the rally holds).
// Teaches: stay invested in uptrends, don't sit flat after selling the bottom.
const CASH_DRAG_PENALTY = 50;
const CASH_DRAG_RALLY_PCT = 5;
const CASH_DRAG_COOLDOWN_MS = 15 * 60e3;
async function applyCashDrag(env, buckets, nowSq, now, log) {
  if (!nowSq || nowSq <= 0n || !buckets || buckets.length === 0) return;
  // Price ~1h ago from bucket history.
  const t1h = now - 3600e3;
  let sq1h = null;
  for (let k = buckets.length - 1; k >= 0; k--) {
    if (buckets[k].ts <= t1h) { sq1h = buckets[k].sq; break; }
  }
  if (!sq1h || sq1h <= 0n) return; // no 1h history yet — can't judge the rally
  const nN = Number(nowSq), hN = Number(sq1h);
  const rallyPct = ((nN - hN) / hN) * 100;
  if (rallyPct < CASH_DRAG_RALLY_PCT) return; // no rally — no drag
  for (let i = 0; i < BURNERS.length; i++) {
    try {
      const position = await kvGet(env, `wallet:${i}:position`, null);
      if (position) continue; // holding — not in cash
      const stats = (await kvGet(env, `wallet:${i}:stats`, null)) || { trades: 0, points: 0 };
      if ((stats.trades || 0) <= 0) continue; // brand new — hasn't learned to trade yet
      const lastDrag = (await kvGet(env, `wallet:${i}:lastCashDrag`, 0)) || 0;
      if (now - lastDrag < CASH_DRAG_COOLDOWN_MS) continue; // cooldown — no runaway
      stats.points = (stats.points || 0) - CASH_DRAG_PENALTY;
      await kvPut(env, `wallet:${i}:stats`, stats);
      await kvPut(env, `wallet:${i}:lastCashDrag`, now);
      log(`[w${i}] CASH DRAG: -${CASH_DRAG_PENALTY}pts (flat during +${rallyPct.toFixed(1)}% 1h rally, ${stats.trades} trades)`);
    } catch (e) { /* cash drag is advisory — never block the tick */ }
  }
}

// ------------------------------------------------------------------ tournament ---
// Zero-sum arena ranking (2026-10-07 23:05 EDT, superintelligence #6).
// Every 24h, rank all 16 by avg ROI. Top 3 get bonuses, bottom 3 get penalties.
// They're not just trading the market — they're trading EACH OTHER.
async function maybeRunTournament(env, log) {
  const now = Date.now();
  const last = (await kvGet(env, 'arena:lastTournament', 0)) || 0;
  if (now - last < TOURNAMENT_INTERVAL_MS) return;
  const rows = [];
  for (let i = 0; i < BURNERS.length; i++) {
    const st = (await kvGet(env, `wallet:${i}:stats`, null)) || {};
    rows.push({ i, avgRoi: st.avgRoi || 0, trades: st.trades || 0, points: st.points || 0 });
  }
  rows.sort((a, b) => b.avgRoi - a.avgRoi);
  const applied = [];
  for (let rank = 0; rank < 3 && rank < rows.length; rank++) {
    const r = rows[rank];
    const bonus = TOURNAMENT_TOP_BONUS[rank];
    const st = (await kvGet(env, `wallet:${r.i}:stats`, null)) || { points: 0 };
    st.points = (st.points || 0) + bonus;
    await kvPut(env, `wallet:${r.i}:stats`, st);
    applied.push(`w${r.i} #${rank + 1} +${bonus}`);
  }
  for (let k = 0; k < 3 && k < rows.length; k++) {
    const r = rows[rows.length - 1 - k];
    // Don't penalize wallets that never traded (no data, not failure).
    if (r.trades === 0) continue;
    const penalty = TOURNAMENT_BOT_PENALTY[k];
    const st = (await kvGet(env, `wallet:${r.i}:stats`, null)) || { points: 0 };
    st.points = (st.points || 0) - penalty;
    await kvPut(env, `wallet:${r.i}:stats`, st);
    applied.push(`w${r.i} #${rows.length - k} -${penalty}`);
  }
  const board = rows.map((r, idx) => `#${idx + 1} w${r.i} ${(r.avgRoi * 100).toFixed(1)}%`).join(' | ');
  log(`TOURNAMENT (24h): ${applied.join(', ')} || ${board}`);
  await kvPut(env, 'arena:lastTournament', now);
}

export { scorePendingSells, CASH_DRAG_PENALTY, CASH_DRAG_RALLY_PCT, CASH_DRAG_COOLDOWN_MS, applyCashDrag, maybeRunTournament };
