// src/tick.js — runTick — the whole tick: price, safety gates, shared senses, spike pass, wallets.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { createPublicClient, http } from 'viem';
import { base } from 'viem/chains';
import { BRAWL, BURNERS, CIRCUIT_HALT_MS, CIRCUIT_MOVE_PCT, DUMP_GRID, HIGH_WINDOW_MS, ORPHAN_MAX_HOLD_MS, QUIET_MOVE_BPS, SPIKE_MAX_EXITS_PER_TICK, SPIKE_PCT, VALUE_GRID, WETH, setBurners, setDumpGrid, setValueGrid } from './config.js';
import { fetchEthUsd } from './ethusd.js';
import { computeFleetStats } from './fleet.js';
import { kvGet, kvPut, raceTimeout } from './kv.js';
import { bottomSignal, computePriceVelAnn, computeTwapSq, dipBps, fetchDepth2pctWeth, fetchPoolSq, fetchSwapFlow, isOwnerDrivenSpike, riseBps, rollLow24, sqToWethPerBrawl } from './market.js';
import { maybeLogLeaderboard, updatePatterns } from './patterns.js';
import { comboKey } from './qtable.js';
import { executeSell } from './sell.js';
import { applyCashDrag, maybeRunTournament, scorePendingSells } from './shaping.js';
import { processWallet } from './wallet.js';
// ------------------------------------------------------------------ tick ---
async function runTick(env, log) {
  const now = Date.now();
  const dryRun = env.DRY_RUN === 'true';
  const RPC_URLS = (env.RPC_URLS || env.RPC_URL || 'https://mainnet.base.org').split(',').map(s => s.trim()).filter(Boolean);
  if (env.BURNER_ADDRESSES) setBurners(env.BURNER_ADDRESSES.split(',').map((a) => a.trim()));
  // Threshold-grid override (fork tournament / experiments ONLY). Changing the grid on
  // live state wipes every Q-table via the QGRID_VER check below — never set these on
  // the live fleet without meaning to. e.g. DUMP_GRID="5,10,15,20" VALUE_GRID="10,20,30"
  if (env.DUMP_GRID) setDumpGrid(env.DUMP_GRID.split(',').map(Number));
  if (env.VALUE_GRID) setValueGrid(env.VALUE_GRID.split(',').map(Number));
  if (dryRun) log('*** DRY_RUN mode — no broadcasts ***');

  // Try each RPC in order; use the first that serves the price read.
  let publicClient = null, nowSq = null, rpcUsed = null;
  let lastErr = null;
  // RPC SELECTION TIMEOUT (2026-10-08): during egress wedges, even viem's 15s
  // timeout can hang at TCP/CONNECT. Cap the entire selection loop at 60s —
  // 3 RPCs x 15s + overhead. If we can't get a price in 60s, SAFE-ABORT.
  const RPC_SELECT_TIMEOUT_MS = 60000;
  const rpcSelectStart = Date.now();
  for (const rpcUrl of RPC_URLS) {
    if (Date.now() - rpcSelectStart > RPC_SELECT_TIMEOUT_MS) {
      lastErr = new Error(`RPC selection timeout after ${RPC_SELECT_TIMEOUT_MS}ms`);
      break;
    }
    try {
      const pc = createPublicClient({ chain: base, transport: http(rpcUrl, { timeout: 15000 }) });
      const sq = await raceTimeout(fetchPoolSq(pc), 20000, `fetchPoolSq timeout on ${rpcUrl}`);
      publicClient = pc; nowSq = sq; rpcUsed = rpcUrl;
      break;
    } catch (e) { lastErr = e; }
  }
  if (!publicClient) {
    // SAFE-ABORT (not FATAL): without a price we cannot trade. The babies stay
    // blind rather than trade blind. This is the system working as designed.
    // (Anthony 2026-10-08: "they can never be blind. they can never fail.")
    log(`SAFE-ABORT: pool price read failed on all RPCs (${RPC_URLS.length} tried, last: ${lastErr && lastErr.message}) — tick skipped, no trades`);
    return;
  }
  log(`rpc: ${rpcUsed}`);
  const priceWeth = sqToWethPerBrawl(nowSq);

  // PLUS ULTRA #10 (2026-10-07 23:07): circuit breaker — a >20%/min move trips a
  // 5-min all-trading halt. Ruthless, not reckless: in a flash move quotes are stale
  // and the 1.5x-gate math is fiction. Price history still updates during the halt.
  const trip = await kvGet(env, 'circuit:tripped', null);
  if (trip && now >= trip.until) {
    await kvPut(env, 'circuit:tripped', null); // expired — resume trading
    log('circuit breaker expired — resuming');
  } else if (trip) {
    log(`CIRCUIT BREAKER: tripped ${(trip.movePct)}% at ${new Date(trip.ts).toISOString()} — cooling until ${new Date(trip.until).toISOString()}, trading paused`);
    let qb = await kvGet(env, 'price:buckets', []);
    qb.push({ ts: now, sq: nowSq.toString() });
    if (qb.length > 300) qb = qb.slice(-300);
    await kvPut(env, 'price:buckets', qb);
    await kvPut(env, 'price:tick', { sq: nowSq.toString(), ts: now, prevMoveBps: 0 });
    log('tick complete (circuit-breaker)');
    return;
  }

  // 2b) Quiet-tick listener (Anthony 2026-10-07 13:41 EDT): on dead ticks (<0.50% move
  // since last tick) just update price history and exit — no ETH/USD fetch, no trading,
  // no gas wasted. The 1-min cron becomes an efficient listener.
  const prev = await kvGet(env, 'price:tick', null);
  const prevSq = prev ? BigInt(prev.sq) : nowSq;
  const moveBps = prev ? riseBps(prevSq, nowSq) : 0; // signed bps, + = price up
  // PLUS ULTRA #10: trip the breaker on a >20% one-minute move. The 10-20% band
  // still gets the spike-sell treatment (3b); beyond 20% we halt everything —
  // no FOMO buys into a vertical pump, no panic dumps into a flash crash.
  if (prev && Math.abs(moveBps) / 100 > CIRCUIT_MOVE_PCT) {
    await kvPut(env, 'circuit:tripped', {
      ts: now, until: now + CIRCUIT_HALT_MS, movePct: Number((moveBps / 100).toFixed(1)),
    });
    log(`CIRCUIT BREAKER TRIPPED: ${(moveBps / 100).toFixed(1)}% in ~1 min — halting all trading for 5 min`);
    let tqb = await kvGet(env, 'price:buckets', []);
    tqb.push({ ts: now, sq: nowSq.toString() });
    if (tqb.length > 300) tqb = tqb.slice(-300);
    await kvPut(env, 'price:buckets', tqb);
    await kvPut(env, 'price:tick', { sq: nowSq.toString(), ts: now, prevMoveBps: moveBps });
    if (prev) await kvPut(env, 'price:tickPrev', { sq: prev.sq, ts: prev.ts });
    log('tick complete (circuit-breaker tripped)');
    return;
  }
  if (prev && Math.abs(moveBps) < QUIET_MOVE_BPS) {
    let qHigh = await kvGet(env, 'price:high1h', null);
    if (!qHigh || now - qHigh.ts > HIGH_WINDOW_MS || nowSq > BigInt(qHigh.sq)) {
      qHigh = { sq: nowSq.toString(), ts: now };
    }
    const qLow = rollLow24(await kvGet(env, 'price:low24h', null), nowSq, now,
      (await kvGet(env, 'price:buckets', [])) || []);
    // WAKE-UP (Anthony 2026-10-07 14:26): a quiet tick is only quiet if price is NOT
    // sitting at value levels. If we're deep below the 1h high or near the 24h low, a
    // wallet's VALUE/BOTTOM buy signal may fire — fall through to full logic instead
    // of sleeping through a cheap market. Thresholds here are the most permissive
    // grid values so no wallet's learned gate gets blocked by the quiet exit.
    const qDipPct = dipBps(BigInt(qHigh.sq), nowSq) / 100;
    const qAboveLowPct = nowSq > BigInt(qLow.sq)
      ? Number((nowSq - BigInt(qLow.sq)) * 10000n / BigInt(qLow.sq)) / 100 : 0;
    const maybeValue = qDipPct >= Math.min(...VALUE_GRID) || bottomSignal(qAboveLowPct, now - qLow.ts);
    // HOLDING wake-up (2026-10-07 14:49): wallets with open positions must evaluate
    // exits every tick — a stable price can still be above a wallet's target. Without
    // this, a holding wallet sleeps through profitable exits on quiet ticks.
    let anyHolding = false;
    for (let wi = 0; wi < BURNERS.length && !anyHolding; wi++) {
      const hp = await kvGet(env, `wallet:${wi}:position`, null);
      if (hp) anyHolding = true;
    }
    if (!maybeValue && !anyHolding) {
      log(`quiet tick: ${(moveBps / 100).toFixed(2)}% move < 0.50% — price history updated, trading skipped`);
      await kvPut(env, 'price:tick', { sq: nowSq.toString(), ts: now, prevMoveBps: moveBps });
      if (prev) await kvPut(env, 'price:tickPrev', { sq: prev.sq, ts: prev.ts }); // 2-tick dump window
      await kvPut(env, 'price:high1h', qHigh);
      await kvPut(env, 'price:low24h', qLow);
      // Still record the bucket so NN features stay fresh on quiet ticks.
      let qb = await kvGet(env, 'price:buckets', []);
      qb.push({ ts: now, sq: nowSq.toString() });
      if (qb.length > 300) qb = qb.slice(-300);
      await kvPut(env, 'price:buckets', qb);
      log('tick complete (quiet)');
      return;
    }
    log(`wake-up: quiet tick but ${anyHolding ? 'a wallet is holding' : ''}${anyHolding && maybeValue ? ' and ' : ''}${maybeValue ? `price at value levels (${qDipPct.toFixed(1)}% below 1h high, ${qAboveLowPct.toFixed(1)}% above 24h low)` : ''} — running full logic`);
  }
  if (prev) log(`tick move: ${(moveBps / 100).toFixed(2)}% since last tick`);

  // 2) ETH/USD (needed for all USD math).
  const ethUsd = await fetchEthUsd(env, log, publicClient);
  if (!ethUsd) { log('no ETH/USD — aborting tick (safe)'); return; }
  const priceUsd = priceWeth * ethUsd;
  log(`price: ${priceWeth.toExponential(4)} WETH/BRAWL ($${priceUsd.toExponential(4)}) | ETH $${ethUsd}`);

  // 3) Price history: prev tick (spike) + 1h high (dip) + 24h low (selective entries).
  // (prev/prevSq/moveBps computed above for the quiet-tick check.)
  let high = await kvGet(env, 'price:high1h', null);
  if (!high || now - high.ts > HIGH_WINDOW_MS || nowSq > BigInt(high.sq)) {
    high = { sq: nowSq.toString(), ts: now };
  }
  // Rolling price buckets for NN multi-timeframe features (last 300 ticks ≈ 5h).
  let buckets = await kvGet(env, 'price:buckets', []);
  buckets.push({ ts: now, sq: nowSq.toString() });
  if (buckets.length > 300) buckets = buckets.slice(-300);
  await kvPut(env, 'price:buckets', buckets);
  const bucketsBig = buckets.map(b => ({ ts: b.ts, sq: BigInt(b.sq) }));
  const low24 = rollLow24(await kvGet(env, 'price:low24h', null), nowSq, now, buckets);
  // Previous tick's move (for acceleration feature). Stored on price:tick.
  const prevMoveBps = prev && prev.prevMoveBps != null ? prev.prevMoveBps : 0;
  await kvPut(env, 'price:tick', { sq: nowSq.toString(), ts: now, prevMoveBps: moveBps });
  if (prev) await kvPut(env, 'price:tickPrev', { sq: prev.sq, ts: prev.ts }); // 2-tick dump window
  await kvPut(env, 'price:high1h', high);
  await kvPut(env, 'price:low24h', low24);
  const highSq = BigInt(high.sq);
  const low24Sq = BigInt(low24.sq);

  // 3c) Pattern learning: track significant moves (>5%) to learn pump/dump cycles.
  // Stores in KV: {pumps: [...], dumps: [...], avgPumpPct, avgDumpPct, avgCycleMs, lastExtreme}
  const pattern = await updatePatterns(env, prevSq, nowSq, now, log);

  // NN shared per-tick data: gas price (one read, reused by all wallets).
  let gasPriceWei = 0n;
  try { gasPriceWei = await publicClient.getGasPrice(); } catch (e) { /* leave 0 */ }
  // PLUS ULTRA #5b: gas spike — tanh((gwei - lastTickGwei)/5). The 1.5x profit gate
  // is gas-sensitive; spiking gas means re-time the exit. Stored per tick in KV.
  let gasSpike = 0;
  try {
    const gweiNow = Number(gasPriceWei) / 1e9;
    const gasLast = await kvGet(env, 'gas:last', null);
    if (gasLast && gasLast.gwei > 0 && gweiNow > 0) {
      gasSpike = Math.tanh((gweiNow - gasLast.gwei) / 5);
      if (Math.abs(gasSpike) > 0.3) log(`gas spike: ${gasLast.gwei.toFixed(2)} → ${gweiNow.toFixed(2)} gwei (F[35]=${gasSpike.toFixed(2)})`);
    }
    if (gweiNow > 0) await kvPut(env, 'gas:last', { gwei: gweiNow, ts: now });
  } catch (e) { /* gas spike is advisory */ }
  // PLUS ULTRA senses (2026-10-07 23:07): computed once per tick, shared via ctx.
  // EYES #1 (slot0 direct) is already the price path — fastest possible, no HTTP.
  const twapSq = computeTwapSq(bucketsBig, now);                 // EYES #2
  if (twapSq) {
    const twapDivBps = nowSq >= twapSq
      ? Number((nowSq - twapSq) * 10000n / twapSq) : -Number((twapSq - nowSq) * 10000n / twapSq);
    log(`twap(10m): spot ${twapDivBps >= 0 ? '+' : ''}${(twapDivBps / 100).toFixed(2)}% vs TWAP`);
  }
  const swapFlow = await fetchSwapFlow(publicClient, log);       // EYES #3 + EARS #6
  const depth2pctWeth = await fetchDepth2pctWeth(publicClient, priceWeth, log); // EYES #4
  const priceVelAnn = computePriceVelAnn(bucketsBig, now);       // EARS #8
  if (priceVelAnn > 0) log(`price velocity: ${(priceVelAnn * 100).toFixed(0)}% annualized`);
  // EARS #7 (mempool snipe detector): deferred — no mempool API is wired in this
  // environment, and polling one would add an HTTP dependency to the hot path.
  // Revisit when a reliable mempool feed exists; the feature slot is reserved.
  const ethUsdPrev = await kvGet(env, 'ethusd:prev1h', null);
  // DATA QUALITY (Anthony 2026-10-08 00:17 EDT): babies can NEVER be blind.
  // Track which critical reads succeeded. F[45] exposes this live.
  // 1.0 = all fresh, 0.0 = flying blind. Low quality → DO NOT TRADE.
  let dataQualityReads = 0, dataQualityTotal = 5;
  if (priceWeth && priceWeth > 0) dataQualityReads++;
  if (swapFlow) dataQualityReads++;
  if (depth2pctWeth && depth2pctWeth > 0) dataQualityReads++;
  if (ethUsd && ethUsd > 0) dataQualityReads++;
  if (gasPriceWei && gasPriceWei > 0n) dataQualityReads++;
  const dataQuality = dataQualityReads / dataQualityTotal;
  if (dataQuality < 1.0) log(`DATA QUALITY: ${dataQualityReads}/${dataQualityTotal} reads ok (${(dataQuality*100).toFixed(0)}%)`);
  const ctx = { env, publicClient, ethUsd, nowSq, prevSq, moveBps, prevMoveBps,
    highSq, low24Sq, low24Ts: low24.ts, priceWeth, priceUsd, now, dryRun, log,
    buckets: bucketsBig, pattern, gasPriceWei,
    ethUsdPrev1h: ethUsdPrev && now - ethUsdPrev.ts < 2 * 3600e3 ? ethUsdPrev.price : null,
    // PLUS ULTRA senses shared to all wallets:
    volumeStats: swapFlow ? { buyVol: swapFlow.buyVol, sellVol: swapFlow.sellVol } : null,
    whaleNetBrawl: swapFlow ? swapFlow.whaleNetBrawl : null,
    depth2pctWeth, gasSpike, priceVelAnn, twapSq, dataQuality };
  // Arena opponent-awareness (2026-10-07 22:00 EDT): fleet posture computed once
  // per tick, shared to all wallets via ctx.fleet. Each baby sees the competition.
  try {
    ctx.fleet = await computeFleetStats(env, log);
  } catch (e) {
    log(`fleet stats failed (${e.message}) — NN opponent features will use neutral fallbacks`);
    ctx.fleet = null;
  }
  // Snapshot ETH/USD hourly for the NN's eth_usd_ret_1h feature.
  const lastSnap = await kvGet(env, 'ethusd:snapTs', 0);
  if (now - lastSnap > 3600e3) {
    await kvPut(env, 'ethusd:prev1h', { price: ethUsd, ts: now });
    await kvPut(env, 'ethusd:snapTs', now);
  }

  // 3b) Spike listener (Anthony 2026-10-07 13:41 EDT): +10% in ONE tick (likely Anthony
  // or a big buyer) -> accelerated exit evaluation.
  // (Wren 2026-10-08: spike-pass fix) The old pass sold EVERY holding wallet in the
  // same tick at just the 1.5x-gas bar — the synchronized multi-wallet exit Anthony
  // banned for stop-losses. Now: (1) if the spike's dominant buy volume is the
  // owner/fleet, HOLD — never sell into our own buy; (2) only wallets whose OWN
  // target is met may exit (enforced in executeSell for reason 'spike'); (3) at most
  // SPIKE_MAX_EXITS_PER_TICK exits per tick, highest conviction first — the rest
  // are handled by the normal holding branch on this or later ticks. No KV queue:
  // the holding branch already evaluates every wallet's own target every tick.
  if (prev && moveBps >= SPIKE_PCT * 100) {
    log(`!!! SPIKE +${(moveBps / 100).toFixed(1)}% since last tick — accelerated exit evaluation`);
    const { ownerDriven, detail } = await isOwnerDrivenSpike(publicClient, log);
    if (ownerDriven) {
      log(`SPIKE HOLD: dominant buy volume is owner/fleet (${detail}) — will not sell into our own buy`);
      // (review) The hold must cover the per-wallet holding branch too: it runs in this
      // same tick and would otherwise take profit straight into the owner's buy.
      ctx.ownerSpikeHold = true;
    } else {
      // Rank holding wallets by rough conviction (estimated unrealized profit) so
      // the limited per-tick exits go to the strongest targets first.
      const cands = [];
      for (let i = 0; i < BURNERS.length; i++) {
        try {
          const position = await kvGet(env, `wallet:${i}:position`, null);
          if (!position || !position.amountWei) continue;
          const estValUsd = (Number(BigInt(position.amountWei)) / 1e18) * (priceWeth || 0) * (ethUsd || 0);
          const estProfit = estValUsd - (position.buyCostUsd || 0);
          cands.push({ i, position, estProfit });
        } catch (e) { log(`[w${i}] spike rank error: ${e.message}`); }
      }
      cands.sort((a, b) => b.estProfit - a.estProfit);
      const batch = cands.slice(0, SPIKE_MAX_EXITS_PER_TICK);
      log(`spike exits: ${cands.length} holding, evaluating top ${batch.length} this tick (rest via normal holding branch)`);
      for (const { i, position } of batch) {
        try {
          const r = await executeSell({ ...ctx, log }, i, position, 'spike', log)
            .catch((e) => { log(`[w${i}] spike sell error: ${e.message}`); return null; });
          if (r) log(`[w${i}] spike exit executed`);
          else log(`[w${i}] spike exit skipped (below own target or 1.5x bar)`);
        } catch (e) { log(`[w${i}] spike pass error: ${e.message}`); }
      }
    }
  }

  // MAX-HOLD precompute (2026-10-08 deadlock breaker): deterministically pick at most
  // ONE orphan max-hold exit for this tick, in wallet index order (first eligible
  // wins). The 4-way batch loop below runs processWallet concurrently, so the pick
  // must be made up-front and shared read-only via KV — two wallets can never both
  // match 'maxhold:exitWallet' in the same tick. Race-safe by construction: the loop
  // is a single sequential pass, the KV writes are awaited before any batch starts.
  // The actual exit still runs inside processWallet, so the data-quality blind gate
  // and the quote-failure HOLD both still apply — this precompute exits no one.
  let maxholdExit = -1;
  try {
    for (let i = 0; i < BURNERS.length; i++) {
      const p = await kvGet(env, `wallet:${i}:position`, null);
      if (p && p.comboKey && String(p.comboKey).startsWith('orphan') && (now - p.buyTs) >= ORPHAN_MAX_HOLD_MS) {
        maxholdExit = i;
        break;
      }
    }
    await kvPut(env, 'maxhold:exitWallet', maxholdExit);
    await kvPut(env, 'maxhold:exitTick', now);
    log(maxholdExit >= 0
      ? `MAX-HOLD: wallet ${maxholdExit} pre-picked for market exit this tick (orphan >= 8h)`
      : 'MAX-HOLD: none eligible');
  } catch (e) {
    log(`MAX-HOLD precompute failed (${e.message}) — no max-hold exits this tick`);
  }

  // 4) Wallets in parallel (4-way batches) — independent decisions, one failure never kills the tick.
  // (Anthony 2026-10-08 01:22 EDT "fix that": serial 16 wallets x ~15s each = 240s+ blew the 300s budget.
  // Each wallet uses its own KV keys; ctx market data is read-only. 4-way keeps RPC load sane.)
  //
  // HARD TIMEOUTS (Anthony 2026-10-08 01:42 EDT "make sure it doesnt go down during those issues"):
  // During egress wedges, RPC calls hang at TCP/CONNECT level beyond viem's 15s timeout.
  // Without hard timeouts, one hung wallet blocks its entire batch indefinitely.
  // Each wallet gets 45s max; each batch gets 120s max. Timeouts are logged, never fatal.
  const WALLET_CONCURRENCY = 4;
  const WALLET_TIMEOUT_MS = 45000;
  const BATCH_TIMEOUT_MS = 120000;
  const withTimeout = (promise, ms, label) => raceTimeout(promise, ms, `${label} timeout after ${ms}ms`);
  for (let batch = 0; batch < BURNERS.length; batch += WALLET_CONCURRENCY) {
    const ids = [];
    for (let k = 0; k < WALLET_CONCURRENCY && batch + k < BURNERS.length; k++) ids.push(batch + k);
    try {
      await withTimeout(
        Promise.all(ids.map(i => {
          // (2026-10-08: cooperative wallet deadline) Promise.race alone does NOT
          // cancel the loser — a timed-out processWallet kept running and could
          // broadcast AFTER the tick moved on (double-sell / phantom position
          // risk). Each wallet gets an AbortController: the timeout aborts it,
          // and sendRawTx refuses any post-deadline broadcast. In-flight
          // settlement (waitReceipt → recordClose) is NOT aborted — a broadcast
          // tx must always be accounted for, never orphaned.
          const ac = new AbortController();
          const wctx = Object.assign({}, ctx, { signal: ac.signal });
          const work = processWallet(wctx, i, log).catch(e => log(`[w${i}] TICK ERROR: ${e.message}`));
          let timer;
          const deadline = new Promise((_, reject) => {
            timer = setTimeout(() => {
              ac.abort();
              reject(new Error(`w${i} timeout after ${WALLET_TIMEOUT_MS}ms (aborted; settlement may still complete)`));
            }, WALLET_TIMEOUT_MS);
          });
          return Promise.race([work, deadline])
            .catch(e => log(`[w${i}] WALLET TIMEOUT: ${e.message}`))
            .finally(() => clearTimeout(timer));
        })),
        BATCH_TIMEOUT_MS,
        `batch ${batch / WALLET_CONCURRENCY}`
      );
    } catch (e) {
      log(`BATCH TIMEOUT: ${e.message} — continuing to next batch`);
    }
  }

  // 4b) Superintelligence post-pass (2026-10-07 23:05 EDT):
  //   - scorePendingSells: deferred ruthlessness bonuses (#1/#2/#3)
  //   - maybeRunTournament: daily zero-sum ranking (#6)
  //   - applyCashDrag: swing-cycle — flat wallets bleed during rallies (2026-10-07 23:37)
  try { await scorePendingSells(env, nowSq, log); } catch (e) { log(`ruthlessness scoring failed: ${e.message}`); }
  try { await maybeRunTournament(env, log); } catch (e) { log(`tournament failed: ${e.message}`); }
  try { await applyCashDrag(env, bucketsBig, nowSq, now, log); } catch (e) { log(`cash drag failed: ${e.message}`); }

  // 5) Leaderboard.
  await maybeLogLeaderboard(env, log);
  log('tick complete');
}

// Tick lock: prevents double-trades when two schedulers (Cloudflare cron +
// external ticker) fire concurrently. Best-effort via KV; 45s window.
async function acquireTickLock(env, log) {
  const now = Date.now();
  const last = (await kvGet(env, 'meta:tickLock', 0)) || 0;
  if (now - last < 45000) {
    log(`tick skipped: previous tick started ${Math.round((now - last) / 1000)}s ago (lock)`);
    return false;
  }
  try { await kvPut(env, 'meta:tickLock', now); } catch (e) { /* lock write failed: proceed, log covers it */ }
  return true;
}

export { runTick, acquireTickLock };
