// src/wallet.js — processWallet — one baby's decision each tick: exits when holding, signals when flat.
// Generated by a mechanical split of worker.js (behavior locked by test/golden.test.mjs).

import { formatEther } from 'viem';
import { selectCombo } from './bandit.js';
import { executeBuy } from './buy.js';
import { recordClose } from './close.js';
import { BOTTOM_MIN_BOUNCE_PCT, BOTTOM_MIN_LOW_AGE_MS, BRAWL, BURNERS, EPSILON, EPSILON_MAX, EPSILON_MIN, ERC20_ABI, HARD_STOP_PCT, NEAR_LOW_PCT, NN_MIN_TRAINED, ORPHAN_MAX_HOLD_MS, PARTIAL_SELL_FRACTION, PARTIAL_SELL_MIN_USD, QGRID_VER, RUNNER_DUST_USD, SEED_BASE, SEED_STEP, SELL_PROFIT_MULT, STABLE_MAX_DROP_PCT, walletStopLoss } from './config.js';
import { getQuote } from './execution.js';
import { buildFeatures } from './features.js';
import { kvGet, kvPut, kvPutCritical } from './kv.js';
import { bottomSignal, dipBps } from './market.js';
import { NN_BUY_GATE, NN_SELL_TRIGGER, nnForward, nnLoad, nnPendingKey } from './nn.js';
import { BASELINE_UNATTRIBUTED_KEY, blankQTable, clampCd, comboKey, migrateQTableCd, parseCombo, seedParams } from './qtable.js';
import { executeSell } from './sell.js';
// ------------------------------------------------------------------ per-wallet tick ---
async function processWallet(ctx, i, log0) {
  const { env, publicClient, ethUsd, nowSq, priceWeth, highSq, low24Sq, prevSq, moveBps, now } = ctx;
  const log = (m) => log0(`[w${i}] ${m}`);
  const addr = BURNERS[i];

  // NEVER BE BLIND: if data quality is too low, DO NOT TRADE (Anthony 2026-10-08 00:17 EDT).
  // This is a safety rail, not paternalism — trading on bad data is not "learning",
  // it's gambling. The NN sees F[45] and learns the pattern; this gate is the backstop.
  if (ctx.dataQuality != null && ctx.dataQuality < 0.6) {
    log(`DATA QUALITY ${(ctx.dataQuality*100).toFixed(0)}% < 60% — SKIPPING (blind, do not trade)`);
    return { skipped: 'blind' };
  }

  // Load state (defaults for first run).
  let seed = await kvGet(env, `wallet:${i}:seed`);
  if (!seed) {
    const sp = seedParams(i);
    seed = { dip: sp.dip, margin: sp.margin, size: sp.size, cooldownMin: sp.cooldownMin };
    await kvPut(env, `wallet:${i}:seed`, seed);
    await kvPut(env, `wallet:${i}:rng`, sp.rngState);
    await kvPut(env, `wallet:${i}:qtable`, blankQTable());
    await kvPut(env, `wallet:${i}:stats`, { points: 0, trades: 0, wins: 0, losses: 0, pnlUsd: 0, rewards: [] });
    log(`seeded: dip=${seed.dip.toFixed(1)}% margin=${seed.margin.toFixed(1)}% size=${seed.size.toFixed(0)}% cooldown=${seed.cooldownMin.toFixed(0)}m`);
  }
  let rngState = (await kvGet(env, `wallet:${i}:rng`)) || { s: (SEED_BASE + i * SEED_STEP) >>> 0 };
  let position = await kvGet(env, `wallet:${i}:position`, null);

  // Orphan-position reconciliation (Anthony 2026-10-07 14:39): a failed receipt poll
  // can leave an onchain BRAWL balance with no KV record. The bot must NEVER sit
  // flat on real tokens. Reconstruct conservatively — cost basis = current estimated
  // sell value — so it only sells once price has risen enough to clear 1.5x gas
  // from the reconciliation point. Safe: no double-buys (holding branch entered),
  // no forced loss (cost basis can't be below what we can currently get).
  if (!position) {
    const orphanBal = await publicClient.readContract({
      address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
    }).catch(() => 0n);
    if (orphanBal > 0n) {
      log(`ORPHAN POSITION: holding ${formatEther(orphanBal)} BRAWL with no KV record — reconstructing`);
      let orphanValueUsd = 0;
      try {
        const oq = await getQuote(env, {
          tokenIn: { type: 'erc20', address: BRAWL }, tokenOut: { type: 'eth' },
          amountInWei: orphanBal, sender: addr, log,
        });
        orphanValueUsd = Number(formatEther(BigInt(oq.quote.amountOut))) * ethUsd;
      } catch (e) { log(`orphan sell-quote failed (${e.message}) — will retry quote next tick`); }
      // (review) If executeBuy left a write-ahead record, this "orphan" is really our
      // own buy whose position write failed — keep its TRUE combo key and buy time.
      const wal = await kvGet(env, `wallet:${i}:pendingBuy`, null);
      const walOk = wal && wal.comboKey && (now - wal.ts) < 24 * 3600e3 && (wal.comboKey in blankQTable());
      if (walOk) log(`orphan matches write-ahead buy record (combo ${wal.comboKey}) — attribution preserved`);
      if (orphanValueUsd > 0) {
        // Snapshot current ETH as the stale-clear reconstruction baseline
        // (2026-10-07 18:52 EDT: w0's spike-sell confirmed 40s after the receipt
        // race declared it dead; without a baseline the P&L was dropped).
        const ethNow = await publicClient.getBalance({ address: addr }).catch(() => 0n);
        position = {
          buyCostUsd: orphanValueUsd, buyGasUsd: 0,
          amountWei: orphanBal.toString(), buyPriceWeth: null,
          comboKey: walOk ? wal.comboKey : 'orphan_0_0_0', marginAtOpen: walOk ? parseCombo(wal.comboKey).margin : 3,
          sizeAtOpen: walOk ? wal.sizePct : 0,
          buyTx: 'orphan-reconcile', buyTs: walOk ? wal.ts : now, reconciled: true,
          ethBalPostBuy: ethNow.toString(),
        };
        await kvPutCritical(env, `wallet:${i}:position`, position, log);
        if (walOk) await kvPut(env, `wallet:${i}:pendingBuy`, null);
        log(`reconciled: cost basis = current sell value $${orphanValueUsd.toFixed(4)} (flagged reconciled)`);
      } else {
        // Quote failed but we HOLD tokens — never leave position null. Record the
        // holding with zero basis so the bot manages (not re-buys) it; a later tick
        // with a working quote will refine the basis. (2026-10-07 16:15)
        position = {
          buyCostUsd: 0, buyGasUsd: 0,
          amountWei: orphanBal.toString(), buyPriceWeth: null,
          comboKey: 'orphan_0_0_0', marginAtOpen: 3, sizeAtOpen: 0,
          buyTx: 'orphan-reconcile-noquote', buyTs: now, reconciled: true, quoteFailed: true,
        };
        await kvPutCritical(env, `wallet:${i}:position`, position, log);
        log(`ORPHAN RECORDED WITHOUT QUOTE — manual review advised, basis $0`);
      }
    }
  }
  const lastTrade = (await kvGet(env, `wallet:${i}:lastTrade`, 0));
  // Swing-cycle: last sell context for F[38] time-since-sell and the swing bonus.
  // (2026-10-07 23:37 EDT) — teaches re-entry: "I sold at $X, price is now $Y < $X."
  const lastSell = await kvGet(env, `wallet:${i}:lastSell`, null);

  // RL grid versioning: reset stale Q-tables when the grid changes.
  let qtable = await kvGet(env, `wallet:${i}:qtable`, null);
  const qver = await kvGet(env, `wallet:${i}:qgridver`, 0);
  if (!qtable || qver !== QGRID_VER) {
    qtable = blankQTable();
    await kvPut(env, `wallet:${i}:qtable`, qtable);
    await kvPut(env, `wallet:${i}:qgridver`, QGRID_VER);
    log(`Q-table reset to grid v${QGRID_VER} (dump/value thresholds learnable)`);
  } else {
    // One-time in-place migration: 4-dim combos -> 5-dim with learnable cooldown.
    const migrated = migrateQTableCd(qtable, seed.cooldownMin);
    if (migrated !== qtable) {
      qtable = migrated;
      await kvPut(env, `wallet:${i}:qtable`, qtable);
      log(`Q-table migrated to 5-dim (${Object.keys(qtable).length} combos): learned Q kept on nearest-cd variant, other cds start at 0`);
    }
  }
  // In-place baseline upgrade (2026-10-08): tables created before the baseline key
  // get it at 0 WITHOUT resetting learned values. QGRID_VER is deliberately NOT
  // bumped — a bump would wipe all learned Q across the fleet.
  if (!(BASELINE_UNATTRIBUTED_KEY in qtable)) {
    qtable[BASELINE_UNATTRIBUTED_KEY] = 0;
    await kvPut(env, `wallet:${i}:qtable`, qtable);
    log(`Q-table: added ${BASELINE_UNATTRIBUTED_KEY} baseline key (in-place, learned values kept)`);
  }
  // #8 Adaptive exploration (2026-10-07 23:05 EDT): epsilon scales with the
  // fleet's recent learning velocity. Flatline -> explore more (break deadlocks).
  let dynEps = EPSILON;
  try {
    const avgR = await kvGet(env, 'arena:avgReward', null);
    if (avgR != null) {
      if (avgR < 10) dynEps = EPSILON * 2;
      else if (avgR > 100) dynEps = EPSILON * 0.9;
      dynEps = Math.max(EPSILON_MIN, Math.min(EPSILON_MAX, dynEps));
      if (dynEps !== EPSILON) log(`adaptive epsilon: ${dynEps.toFixed(2)} (avgReward ${avgR.toFixed(1)})`);
    }
  } catch (e) { /* adaptive epsilon is advisory — fall back to base */ }
  const ck = selectCombo(qtable, rngState, log, dynEps);
  await kvPut(env, `wallet:${i}:rng`, rngState); // persist advanced RNG state
  const parsed = parseCombo(ck);
  const activeDump = parsed.dump, activeValue = parsed.value, activeMargin = parsed.margin, activeSize = parsed.size;
  const activeCd = clampCd(parsed.cd);

  // Cooldown — LEARNABLE (Anthony 2026-10-07 15:32): the bandit combo carries the
  // cooldown, so the ROI×speed Q-update on every close teaches which re-entry
  // speed pays. Holding wallets are gated by the combo that OPENED the position;
  // flat wallets by the combo selected this tick.
  // (review) The cooldown now gates BUYS only. It used to run before the holding
  // branch too, so for 3-20 min after every buy a wallet could not evaluate ANY exit —
  // not the target, not the stop-loss. A coin that dumped right after entry was
  // unsellable until the timer ran out.
  const gateCd = activeCd;
  const cooldownMs = gateCd * 60 * 1000;
  if (!position && now - lastTrade < cooldownMs) {
    log(`cooldown: ${Math.round((cooldownMs - (now - lastTrade)) / 60000)}m left (cd${gateCd}, combo ${ck}) — skip`);
    return;
  }

  if (position) {
    // ---------------- HOLDING: evaluate exits ----------------

    // 1) Spike exits are handled by the tick-level pre-pass in runTick (immediately, in the
    // same invocation, before the wallet loop) — no per-wallet spike check needed here.
    // If a spike sell was skipped (not profitable), fall through to normal checks.

    // 2) Need a sell quote to evaluate target/stop-loss. Do it inside a helper to avoid
    //    duplicating quote logic: reuse executeSell's pre-check by inlining the math here.
    // 2026-10-08 02:50 EDT (baby-monitor v2 diaper change): a FAILED balance read
    // must NEVER be treated as zero. Degraded RPC (timeouts) funneled through the
    // old `.catch(() => 0n)` and the stale-clear below destroyed LIVE position
    // records — w8–w15 ping-ponged clear/reconstruct 4+ times on 2026-10-08
    // 02:57–06:45 UTC while their onchain balances never moved. Failed read =
    // UNKNOWN = HOLD this tick; only a CONFIRMED 0n may clear.
    let bal = null;
    try {
      bal = await publicClient.readContract({
        address: BRAWL, abi: ERC20_ABI, functionName: 'balanceOf', args: [addr],
      });
    } catch (e) {
      log(`balance read failed (${String((e && e.message) || e).slice(0, 80)}) — HOLD, not clearing (unknown ≠ 0)`);
    }
    if (bal === 0n) {
      // Stale-clear with profit reconstruction (Anthony 2026-10-07 15:25): the
      // position sold onchain but the sale was never recorded (receipt-poll gap).
      // If we have the post-buy ETH baseline, estimate proceeds from the balance
      // delta and record the close with the ROI reward instead of dropping it.
      // Otherwise log the dropped cost basis as UNKNOWN-profit — never pretend
      // nothing happened.
      let staleNote = 'no reconstruction baseline';
      try {
        if (position.ethBalPostBuy != null) {
          const ethNow = await publicClient.getBalance({ address: addr }).catch(() => 0n);
          const ethDelta = ethNow - BigInt(position.ethBalPostBuy);
          if (ethDelta > 0n) {
            const gp0 = await publicClient.getGasPrice().catch(() => 0n);
            const sellGasWei = 300000n * gp0; // estimate; receipt unavailable
            const sellGasUsd0 = Number(formatEther(sellGasWei)) * ethUsd;
            const sellValueUsd0 = Number(formatEther(ethDelta)) * ethUsd + sellGasUsd0;
            const profitUsd0 = sellValueUsd0 - position.buyCostUsd - position.buyGasUsd - sellGasUsd0;
            const holdHours0 = (Date.now() - position.buyTs) / 3600000;
            const rc0 = await recordClose(env, i, position, {
              profitUsd: profitUsd0, sellGasUsd: sellGasUsd0,
              costUsd: position.buyCostUsd, costGasUsd: position.buyGasUsd,
              holdHours: holdHours0, hash: position.buyTx || 'unknown', reason: 'stale-reconstruct',
              publicClient,
            }, log);
            staleNote = `reconstructed ~$${profitUsd0.toFixed(4)} (ROI ${(rc0.roi * 100).toFixed(1)}%, ${rc0.reward}pts, ESTIMATED)`;
          } else {
            staleNote = `UNKNOWN-profit: cost basis $${position.buyCostUsd.toFixed(4)} exited for unknown proceeds (ETH delta <= 0)`;
          }
        }
      } catch (e) { staleNote = `reconstruction failed: ${String(e.message).slice(0, 80)}`; }
      log(`no BRAWL balance — clearing stale position (${staleNote})`);
      await kvPut(env, `wallet:${i}:position`, null);
      return;
    }
    if (bal === null) return; // balance read failed above — can't price exits without a confirmed balance; HOLD this tick
    let profitEst = null;
    let sellGasUsd = 0; // declared OUTSIDE try — exit math below needs it (was a scoping bug: holding branch could never sell)
    let sellValueUsd = 0; // same scoping fix (2026-10-07 16:54: TICK ERROR on w9)
    try {
      const q = await getQuote(env, {
        tokenIn: { type: 'erc20', address: BRAWL }, tokenOut: { type: 'eth' },
        amountInWei: bal, sender: addr, log,
      });
      const estGas = await publicClient.estimateGas({ account: addr, to: q.call.target, data: q.call.data, value: 0n }).catch(() => 300000n);
      const gp = await publicClient.getGasPrice();
      sellValueUsd = Number(formatEther(BigInt(q.quote.amountOut))) * ethUsd;
      sellGasUsd = Number(formatEther(estGas * gp)) * ethUsd;
      profitEst = sellValueUsd - position.buyCostUsd - position.buyGasUsd - sellGasUsd;
      log(`holding ${formatEther(bal)} BRAWL | profitEst $${profitEst.toFixed(4)} (margin target $${(position.buyCostUsd * position.marginAtOpen / 100).toFixed(4)})`);
    } catch (e) {
      log(`sell-quote failed (${e.message}) — HOLD`);
      return;
    }

    // 3) Target exit: profit >= 1.5x total gas (Anthony 2026-10-07 — higher bar).
    const totalGasEst = position.buyGasUsd + sellGasUsd;
    // (review) The MARGIN dimension of the Q grid (1/3/5%) used to do NOTHING — it was
    // only printed. 1/3 of the 432 arms were copies of each other and split the data
    // 3 ways. Now the target is the larger of the gas bar and the combo's margin %.
    const marginUsd = position.buyCostUsd * (Number(position.marginAtOpen) || 0) / 100;
    const minProfit = Math.max(SELL_PROFIT_MULT * totalGasEst, marginUsd);
    // (review) Owner/fleet-driven spike this tick: no profit-taking into our own buy.
    // Risk exits (hard stop, stop-loss, max-hold) below are NOT blocked.
    if (ctx.ownerSpikeHold && profitEst >= minProfit) {
      log(`OWNER SPIKE HOLD: target met ($${profitEst.toFixed(4)}) but this spike is owner/fleet buying — not selling into it this tick`);
    } else if (profitEst >= minProfit) {
      // Tranche logic (Anthony 2026-10-07 15:23): big positions take 50% and keep
      // a runner; small ones dump 100% (an extra sell tx would eat the profit).
      // Dust runner (<$0.01) also goes 100%.
      let sellFrac = 1.0;
      if (sellValueUsd >= PARTIAL_SELL_MIN_USD && sellValueUsd * (1 - PARTIAL_SELL_FRACTION) >= RUNNER_DUST_USD) {
        sellFrac = PARTIAL_SELL_FRACTION;
      }
      log(`TARGET HIT: profit $${profitEst.toFixed(4)} >= max(1.5x gas, margin) $${minProfit.toFixed(4)} — ${sellFrac < 1 ? `taking ${(sellFrac * 100).toFixed(0)}% + runner (sell value $${sellValueUsd.toFixed(2)})` : 'selling ALL'}`);
      await executeSell(ctx, i, position, 'target', log, sellFrac).catch((e) => log(`sell error: ${e.message}`));
      await kvPut(env, `wallet:${i}:rng`, rngState);
      return;
    }

    // 3b) NN early-exit: the net scores every holding tick. If sellScore > 0.70 and
    // profit is positive (even below the 1.5x bar), the NN has learned this pattern
    // usually reverses — take the profit early. v1 advisory; bandit rules still primary.
    try {
      const nnw = await nnLoad(env, i, rngState);
      const ethBalNow = await publicClient.getBalance({ address: addr }).catch(() => 0n);
      const statsNow = (await kvGet(env, `wallet:${i}:stats`, null)) || { points: 0 };
      const feats = buildFeatures({
        buckets: ctx.buckets || [], nowSq, highSq, low24Sq, prevSq,
        moveBps, prevMoveBps: ctx.prevMoveBps, pattern: ctx.pattern,
        ethBal: ethBalNow, brawlBal: bal, position, stats: statsNow,
        gasPriceWei: ctx.gasPriceWei || 0n, ethUsd,
        ethUsdPrev1h: ctx.ethUsdPrev1h, now,
        unrealizedPnlPct: position.buyCostUsd > 0 ? (profitEst / position.buyCostUsd) * 100 : 0,
        fleet: ctx.fleet, walletIdx: i,
        // PLUS ULTRA senses (shared per-tick via ctx)
        volumeStats: ctx.volumeStats, depth2pctWeth: ctx.depth2pctWeth,
        positionWeth: Number(BigInt(position.amountWei)) / 1e18 * priceWeth,
        gasSpike: ctx.gasSpike, whaleNetBrawl: ctx.whaleNetBrawl, priceVelAnn: ctx.priceVelAnn,
        lastSell, // swing-cycle: F[38] time-since-sell
        dataQuality: ctx.dataQuality, // F[45] NEVER BE BLIND
      });
      const { out } = nnForward(nnw, feats);
      const sellScore = out[2];
      log(`NN: sellScore=${sellScore.toFixed(3)} (trigger ${NN_SELL_TRIGGER})`);
      // (2026-10-08: train/serve skew fix) the sell head INFERS on these
      // holding-time features but used to TRAIN on buy-time features. Stash the
      // latest holding-time vector; recordClose trains the sell head on it.
      try { await kvPut(env, `nn:sellfeat:${i}`, { features: feats, ts: now }); } catch (e) { /* advisory */ }
      const nnLive = (nnw.nTrained || 0) >= NN_MIN_TRAINED;
      if (!nnLive) log(`NN not trusted yet (${nnw.nTrained || 0}/${NN_MIN_TRAINED} trained closes) — early-exit disabled`);
      if (nnLive && sellScore > NN_SELL_TRIGGER && profitEst > 0 && !ctx.ownerSpikeHold) {
        log(`NN EARLY EXIT: sellScore ${sellScore.toFixed(3)} > ${NN_SELL_TRIGGER}, profit $${profitEst.toFixed(4)} > 0 — selling`);
        await executeSell(ctx, i, position, 'nn-early', log).catch((e) => log(`sell error: ${e.message}`));
        await kvPut(env, `wallet:${i}:rng`, rngState);
        return;
      }
    } catch (e) {
      log(`NN sell-score failed (${e.message}) — continuing with bandit rules`);
    }

    // 4) Stop-loss: per-wallet desync'd threshold (see walletStopLoss) — down X%+
    // and held Yh+ -> sell anyway (RL learns from the negative reward).
    const heldMs = now - position.buyTs;
    const underwaterPct = position.buyCostUsd > 0 ? (profitEst / position.buyCostUsd) * 100 : 0;
    const sl = walletStopLoss(i);
    if (underwaterPct <= -HARD_STOP_PCT) {
      log(`HARD STOP: ${underwaterPct.toFixed(1)}% <= -${HARD_STOP_PCT}% (no time gate) — selling`);
      await executeSell(ctx, i, position, 'stop-loss', log).catch((e) => log(`sell error: ${e.message}`));
      await kvPut(env, `wallet:${i}:rng`, rngState);
      return;
    }
    if (underwaterPct <= -sl.pct && heldMs >= sl.holdMs) {
      log(`STOP-LOSS: ${underwaterPct.toFixed(1)}% <= -${sl.pct.toFixed(1)}% (w${i} threshold) after ${(heldMs / 3600000).toFixed(1)}h >= ${(sl.holdMs / 3600000).toFixed(1)}h — selling at loss (discipline)`);
      await executeSell(ctx, i, position, 'stop-loss', log).catch((e) => log(`sell error: ${e.message}`));
      await kvPut(env, `wallet:${i}:rng`, rngState);
      return;
    }

    // 4b) MAX-HOLD exit (2026-10-08 deadlock breaker): orphan positions older than
    // 8h from entry exit at market. The 1.5x gate is INTENTIONALLY bypassed here —
    // orphan cost basis is a reconstruction fiction, so the gate would freeze the
    // wallet forever; stop-loss is the precedent for knowing exits at a loss.
    // Safety: (a) the data-quality blind gate at the top of processWallet already
    // applied — no bypass; (b) the fresh sell quote above failed => the branch
    // already returned, so sellValueUsd/sellGasUsd are valid; (c) only the wallet
    // pre-picked by runTick's deterministic precompute (maxhold:exitWallet) can
    // fire — one exit per tick even across the 4-way batch; (d) executeSell
    // re-reads balanceOf fresh and recordClose verifies before clearing —
    // UNKNOWN-on-timeout: executeSell throws, the catch logs, the position is
    // NOT cleared. Never clear a position without a confirmed sell.
    const maxholdIdx = await kvGet(env, 'maxhold:exitWallet', -1);
    if (maxholdIdx === i && position.comboKey && String(position.comboKey).startsWith('orphan')
        && (now - position.buyTs) >= ORPHAN_MAX_HOLD_MS) {
      log(`MAX-HOLD: orphan position held ${Math.round((now - position.buyTs) / 3600000)}h >= 8h — exiting at market (1.5x gate bypassed, precedent: stop-loss)`);
      await executeSell(ctx, i, position, 'max-hold', log, 1.0).catch((e) => log(`max-hold sell error: ${e.message}`));
      await kvPut(env, `wallet:${i}:rng`, rngState);
      return;
    }

    log(`HOLD (profitEst $${profitEst.toFixed(4)}, underwater ${underwaterPct.toFixed(1)}%, held ${Math.round(heldMs / 60000)}m)`);
    await kvPut(env, `wallet:${i}:rng`, rngState);
    return;
  }

  // ---------------- FLAT: three buy signals (Anthony 2026-10-07 14:26) ----------------
  // The bot must recognize "price is low", not just "price crashed suddenly".
  // 1. CRASH BUY: sudden dump >= learned dump threshold (DUMP_GRID) in 1-2 ticks.
  // 2. VALUE BUY: price >= learned value threshold (VALUE_GRID) below the 1h high AND
  //    stable this tick (drop < STABLE_MAX_DROP_PCT) — cheap and settling, not mid-crash.
  // 3. BOTTOM BUY: price within NEAR_LOW_PCT of the 24h low.
  // ANY one fires. The bandit learns which thresholds actually make money.
  const dBps = dipBps(highSq, nowSq);
  const dPct = dBps / 100;
  const tickDropPct = moveBps < 0 ? -moveBps / 100 : 0; // this tick's drop
  const tickPrev = await kvGet(env, 'price:tickPrev', null);
  const twoTickDropPct = tickPrev && BigInt(tickPrev.sq) > nowSq
    ? Number((BigInt(tickPrev.sq) - nowSq) * 10000n / BigInt(tickPrev.sq)) / 100 : 0;
  // How far above the 24h low are we? (0% = at the low).
  const aboveLowBps = nowSq > low24Sq ? Number((nowSq - low24Sq) * 10000n / low24Sq) : 0;
  const aboveLowPct = aboveLowBps / 100;
  const nearLow = aboveLowPct <= NEAR_LOW_PCT;

  // (combo already selected pre-gate above: ck / activeDump / activeValue / activeMargin / activeSize / activeCd)
  const dumpThr = activeDump, valueThr = activeValue; // (aliases for the signal math below)
  log(`buy check: tick ${tickDropPct.toFixed(1)}% / 2-tick ${twoTickDropPct.toFixed(1)}% | 1h-high dip ${dPct.toFixed(2)}% | ${aboveLowPct.toFixed(1)}% above 24h low${nearLow ? ' (NEAR LOW)' : ''} (combo ${ck})`);

  const crashBuy = tickDropPct >= dumpThr || twoTickDropPct >= dumpThr;
  // PLUS ULTRA EYES #2: TWAP confirmation — a "value" buy must actually sit at or
  // below the 10-min TWAP (2% tolerance). Buying above TWAP isn't value, it's chasing.
  const belowTwap = ctx.twapSq ? nowSq <= ctx.twapSq * 102n / 100n : true;
  const valueBuy = dPct >= valueThr && tickDropPct < STABLE_MAX_DROP_PCT && belowTwap;
  // (review) see bottomSignal(): the low must have held 30 min and price must have
  // bounced >= 2% off it. Buying AT a fresh low was the 9%-win-rate falling knife.
  const bottomBuy = bottomSignal(aboveLowPct, now - (ctx.low24Ts || now));
  if (!crashBuy && !valueBuy && !bottomBuy) {
    log(`no buy signal (need: dump>=${dumpThr}% | >=${valueThr}% below 1h high & stable | ${BOTTOM_MIN_BOUNCE_PCT}-${NEAR_LOW_PCT}% above a 24h low that held ${BOTTOM_MIN_LOW_AGE_MS / 60e3}m) — skip`);
    return;
  }
  const sig = crashBuy ? `CRASH ${Math.max(tickDropPct, twoTickDropPct).toFixed(1)}% dump`
    : valueBuy ? `VALUE ${dPct.toFixed(1)}% below 1h high, stable`
    : `BOTTOM within ${aboveLowPct.toFixed(1)}% of 24h low`;

  // NN buy gate (v1 advisory): score the setup. Veto if buyScore < gate.
  // If it passes, the NN's continuous buySize overrides the bandit's discrete grid.
  let nnSizePct = activeSize;
  try {
    const nnw = await nnLoad(env, i, rngState);
    const ethBalNow = await publicClient.getBalance({ address: addr }).catch(() => 0n);
    const statsNow = (await kvGet(env, `wallet:${i}:stats`, null)) || { points: 0 };
    const feats = buildFeatures({
      buckets: ctx.buckets || [], nowSq, highSq, low24Sq, prevSq,
      moveBps, prevMoveBps: ctx.prevMoveBps, pattern: ctx.pattern,
      ethBal: ethBalNow, brawlBal: 0n, position: null, stats: statsNow,
      gasPriceWei: ctx.gasPriceWei || 0n, ethUsd,
      ethUsdPrev1h: ctx.ethUsdPrev1h, now,
      unrealizedPnlPct: 0,
      fleet: ctx.fleet, walletIdx: i,
      // PLUS ULTRA senses (shared per-tick via ctx); flat wallet → no market impact
      volumeStats: ctx.volumeStats, depth2pctWeth: ctx.depth2pctWeth, positionWeth: 0,
      gasSpike: ctx.gasSpike, whaleNetBrawl: ctx.whaleNetBrawl, priceVelAnn: ctx.priceVelAnn,
      lastSell, // swing-cycle: F[38] time-since-sell
      dataQuality: ctx.dataQuality, // F[45] NEVER BE BLIND
    });
    const fwd = nnForward(nnw, feats);
    const buyScore = fwd.out[0];
    const nnLive = (nnw.nTrained || 0) >= NN_MIN_TRAINED;
    // Continuous size: 10% + 90% * buySize output → [10%, 100%]. Only once trusted;
    // an untrained net would size from random weights (could go 100% all-in).
    const nnRawSize = Math.round(10 + 90 * fwd.out[1]);
    nnSizePct = nnLive ? nnRawSize : activeSize;
    log(`NN: buyScore=${buyScore.toFixed(3)} (gate ${NN_BUY_GATE}) size=${nnRawSize}% (bandit ${activeSize}%)${nnLive ? '' : ` — advisory only, ${nnw.nTrained || 0}/${NN_MIN_TRAINED} trained closes`}`);
    if (nnLive && buyScore < NN_BUY_GATE) {
      log(`NN VETO: buyScore ${buyScore.toFixed(3)} < ${NN_BUY_GATE} — skipping bandit buy signal (${sig})`);
      return;
    }
    // Snapshot features for online training when this trade closes.
    await kvPut(env, nnPendingKey(i), {
      features: feats, buySizePct: nnSizePct, buyTs: now,
      comboKey: ck,
    });
  } catch (e) {
    log(`NN buy-gate failed (${e.message}) — proceeding with bandit signal`);
  }
  log(`BUY SIGNAL — ${sig} — sizing ${nnSizePct}% (NN)`);
  try {
    await executeBuy(ctx, i, { key: ck, dump: dumpThr, value: valueThr, margin: activeMargin, size: nnSizePct, cd: activeCd }, dPct, log);
  } catch (e) {
    log(`buy error: ${e.message}`);
  }
}

export { processWallet };
